/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.ethica.esf.service.persistence.ESFArticle_ESFUserPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFArticle_ESFUser service. Represents a row in the &quot;ESFArticle_ESFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFArticle_ESFUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFArticle_ESFUserImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFArticle_ESFUser
 * @see com.ethica.esf.model.impl.ESFArticle_ESFUserImpl
 * @see com.ethica.esf.model.impl.ESFArticle_ESFUserModelImpl
 * @generated
 */
public interface ESFArticle_ESFUserModel extends BaseModel<ESFArticle_ESFUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f article_ e s f user model instance should use the {@link ESFArticle_ESFUser} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f article_ e s f user.
	 *
	 * @return the primary key of this e s f article_ e s f user
	 */
	public ESFArticle_ESFUserPK getPrimaryKey();

	/**
	 * Sets the primary key of this e s f article_ e s f user.
	 *
	 * @param primaryKey the primary key of this e s f article_ e s f user
	 */
	public void setPrimaryKey(ESFArticle_ESFUserPK primaryKey);

	/**
	 * Returns the esf article ID of this e s f article_ e s f user.
	 *
	 * @return the esf article ID of this e s f article_ e s f user
	 */
	public long getEsfArticleId();

	/**
	 * Sets the esf article ID of this e s f article_ e s f user.
	 *
	 * @param esfArticleId the esf article ID of this e s f article_ e s f user
	 */
	public void setEsfArticleId(long esfArticleId);

	/**
	 * Returns the esf user ID of this e s f article_ e s f user.
	 *
	 * @return the esf user ID of this e s f article_ e s f user
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f article_ e s f user.
	 *
	 * @param esfUserId the esf user ID of this e s f article_ e s f user
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f article_ e s f user.
	 *
	 * @return the esf user uuid of this e s f article_ e s f user
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f article_ e s f user.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f article_ e s f user
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the xxxl qty of this e s f article_ e s f user.
	 *
	 * @return the xxxl qty of this e s f article_ e s f user
	 */
	public long getXxxlQty();

	/**
	 * Sets the xxxl qty of this e s f article_ e s f user.
	 *
	 * @param xxxlQty the xxxl qty of this e s f article_ e s f user
	 */
	public void setXxxlQty(long xxxlQty);

	/**
	 * Returns the xxl qty of this e s f article_ e s f user.
	 *
	 * @return the xxl qty of this e s f article_ e s f user
	 */
	public long getXxlQty();

	/**
	 * Sets the xxl qty of this e s f article_ e s f user.
	 *
	 * @param xxlQty the xxl qty of this e s f article_ e s f user
	 */
	public void setXxlQty(long xxlQty);

	/**
	 * Returns the xl qty of this e s f article_ e s f user.
	 *
	 * @return the xl qty of this e s f article_ e s f user
	 */
	public long getXlQty();

	/**
	 * Sets the xl qty of this e s f article_ e s f user.
	 *
	 * @param xlQty the xl qty of this e s f article_ e s f user
	 */
	public void setXlQty(long xlQty);

	/**
	 * Returns the l qty of this e s f article_ e s f user.
	 *
	 * @return the l qty of this e s f article_ e s f user
	 */
	public long getLQty();

	/**
	 * Sets the l qty of this e s f article_ e s f user.
	 *
	 * @param lQty the l qty of this e s f article_ e s f user
	 */
	public void setLQty(long lQty);

	/**
	 * Returns the m qty of this e s f article_ e s f user.
	 *
	 * @return the m qty of this e s f article_ e s f user
	 */
	public long getMQty();

	/**
	 * Sets the m qty of this e s f article_ e s f user.
	 *
	 * @param mQty the m qty of this e s f article_ e s f user
	 */
	public void setMQty(long mQty);

	/**
	 * Returns the s qty of this e s f article_ e s f user.
	 *
	 * @return the s qty of this e s f article_ e s f user
	 */
	public long getSQty();

	/**
	 * Sets the s qty of this e s f article_ e s f user.
	 *
	 * @param sQty the s qty of this e s f article_ e s f user
	 */
	public void setSQty(long sQty);

	/**
	 * Returns the xs qty of this e s f article_ e s f user.
	 *
	 * @return the xs qty of this e s f article_ e s f user
	 */
	public long getXsQty();

	/**
	 * Sets the xs qty of this e s f article_ e s f user.
	 *
	 * @param xsQty the xs qty of this e s f article_ e s f user
	 */
	public void setXsQty(long xsQty);

	/**
	 * Returns the xxs qty of this e s f article_ e s f user.
	 *
	 * @return the xxs qty of this e s f article_ e s f user
	 */
	public long getXxsQty();

	/**
	 * Sets the xxs qty of this e s f article_ e s f user.
	 *
	 * @param xxsQty the xxs qty of this e s f article_ e s f user
	 */
	public void setXxsQty(long xxsQty);

	/**
	 * Returns the other qty of this e s f article_ e s f user.
	 *
	 * @return the other qty of this e s f article_ e s f user
	 */
	public long getOtherQty();

	/**
	 * Sets the other qty of this e s f article_ e s f user.
	 *
	 * @param otherQty the other qty of this e s f article_ e s f user
	 */
	public void setOtherQty(long otherQty);

	/**
	 * Returns the total qty of this e s f article_ e s f user.
	 *
	 * @return the total qty of this e s f article_ e s f user
	 */
	public long getTotalQty();

	/**
	 * Sets the total qty of this e s f article_ e s f user.
	 *
	 * @param totalQty the total qty of this e s f article_ e s f user
	 */
	public void setTotalQty(long totalQty);

	/**
	 * Returns the description of this e s f article_ e s f user.
	 *
	 * @return the description of this e s f article_ e s f user
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f article_ e s f user.
	 *
	 * @param description the description of this e s f article_ e s f user
	 */
	public void setDescription(String description);

	/**
	 * Returns the delivery date of this e s f article_ e s f user.
	 *
	 * @return the delivery date of this e s f article_ e s f user
	 */
	public Date getDeliveryDate();

	/**
	 * Sets the delivery date of this e s f article_ e s f user.
	 *
	 * @param deliveryDate the delivery date of this e s f article_ e s f user
	 */
	public void setDeliveryDate(Date deliveryDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFArticle_ESFUser esfArticle_ESFUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFArticle_ESFUser> toCacheModel();

	@Override
	public ESFArticle_ESFUser toEscapedModel();

	@Override
	public ESFArticle_ESFUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}