/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFArticle service. Represents a row in the &quot;ESFArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFArticleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFArticleImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFArticle
 * @see com.ethica.esf.model.impl.ESFArticleImpl
 * @see com.ethica.esf.model.impl.ESFArticleModelImpl
 * @generated
 */
public interface ESFArticleModel extends BaseModel<ESFArticle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f article model instance should use the {@link ESFArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f article.
	 *
	 * @return the primary key of this e s f article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f article.
	 *
	 * @param primaryKey the primary key of this e s f article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf article ID of this e s f article.
	 *
	 * @return the esf article ID of this e s f article
	 */
	public long getEsfArticleId();

	/**
	 * Sets the esf article ID of this e s f article.
	 *
	 * @param esfArticleId the esf article ID of this e s f article
	 */
	public void setEsfArticleId(long esfArticleId);

	/**
	 * Returns the code of this e s f article.
	 *
	 * @return the code of this e s f article
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f article.
	 *
	 * @param code the code of this e s f article
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this e s f article.
	 *
	 * @return the name of this e s f article
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f article.
	 *
	 * @param name the name of this e s f article
	 */
	public void setName(String name);

	/**
	 * Returns the description of this e s f article.
	 *
	 * @return the description of this e s f article
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f article.
	 *
	 * @param description the description of this e s f article
	 */
	public void setDescription(String description);

	/**
	 * Returns the xxxl qty of this e s f article.
	 *
	 * @return the xxxl qty of this e s f article
	 */
	public long getXxxlQty();

	/**
	 * Sets the xxxl qty of this e s f article.
	 *
	 * @param xxxlQty the xxxl qty of this e s f article
	 */
	public void setXxxlQty(long xxxlQty);

	/**
	 * Returns the xxl qty of this e s f article.
	 *
	 * @return the xxl qty of this e s f article
	 */
	public long getXxlQty();

	/**
	 * Sets the xxl qty of this e s f article.
	 *
	 * @param xxlQty the xxl qty of this e s f article
	 */
	public void setXxlQty(long xxlQty);

	/**
	 * Returns the xl qty of this e s f article.
	 *
	 * @return the xl qty of this e s f article
	 */
	public long getXlQty();

	/**
	 * Sets the xl qty of this e s f article.
	 *
	 * @param xlQty the xl qty of this e s f article
	 */
	public void setXlQty(long xlQty);

	/**
	 * Returns the l qty of this e s f article.
	 *
	 * @return the l qty of this e s f article
	 */
	public long getLQty();

	/**
	 * Sets the l qty of this e s f article.
	 *
	 * @param lQty the l qty of this e s f article
	 */
	public void setLQty(long lQty);

	/**
	 * Returns the m qty of this e s f article.
	 *
	 * @return the m qty of this e s f article
	 */
	public long getMQty();

	/**
	 * Sets the m qty of this e s f article.
	 *
	 * @param mQty the m qty of this e s f article
	 */
	public void setMQty(long mQty);

	/**
	 * Returns the s qty of this e s f article.
	 *
	 * @return the s qty of this e s f article
	 */
	public long getSQty();

	/**
	 * Sets the s qty of this e s f article.
	 *
	 * @param sQty the s qty of this e s f article
	 */
	public void setSQty(long sQty);

	/**
	 * Returns the xs qty of this e s f article.
	 *
	 * @return the xs qty of this e s f article
	 */
	public long getXsQty();

	/**
	 * Sets the xs qty of this e s f article.
	 *
	 * @param xsQty the xs qty of this e s f article
	 */
	public void setXsQty(long xsQty);

	/**
	 * Returns the xxs qty of this e s f article.
	 *
	 * @return the xxs qty of this e s f article
	 */
	public long getXxsQty();

	/**
	 * Sets the xxs qty of this e s f article.
	 *
	 * @param xxsQty the xxs qty of this e s f article
	 */
	public void setXxsQty(long xxsQty);

	/**
	 * Returns the other qty of this e s f article.
	 *
	 * @return the other qty of this e s f article
	 */
	public long getOtherQty();

	/**
	 * Sets the other qty of this e s f article.
	 *
	 * @param otherQty the other qty of this e s f article
	 */
	public void setOtherQty(long otherQty);

	/**
	 * Returns the total qty of this e s f article.
	 *
	 * @return the total qty of this e s f article
	 */
	public long getTotalQty();

	/**
	 * Sets the total qty of this e s f article.
	 *
	 * @param totalQty the total qty of this e s f article
	 */
	public void setTotalQty(long totalQty);

	/**
	 * Returns the disabled of this e s f article.
	 *
	 * @return the disabled of this e s f article
	 */
	public boolean getDisabled();

	/**
	 * Returns <code>true</code> if this e s f article is disabled.
	 *
	 * @return <code>true</code> if this e s f article is disabled; <code>false</code> otherwise
	 */
	public boolean isDisabled();

	/**
	 * Sets whether this e s f article is disabled.
	 *
	 * @param disabled the disabled of this e s f article
	 */
	public void setDisabled(boolean disabled);

	/**
	 * Returns the esf article type ID of this e s f article.
	 *
	 * @return the esf article type ID of this e s f article
	 */
	public long getEsfArticleTypeId();

	/**
	 * Sets the esf article type ID of this e s f article.
	 *
	 * @param esfArticleTypeId the esf article type ID of this e s f article
	 */
	public void setEsfArticleTypeId(long esfArticleTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFArticle esfArticle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFArticle> toCacheModel();

	@Override
	public ESFArticle toEscapedModel();

	@Override
	public ESFArticle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}