
package it.ethica.esf.util;

public class ActionKeys
	extends com.liferay.portal.security.permission.ActionKeys {

	
	/* ESFOrganizzationAdminPortlet*/
	public static final String ESFORGANIZATIONADMIN_ADD = "ESFORGANIZATIONADMIN_ADD";
	public static final String ESFORGANIZATIONADMIN_VIEW = "ESFORGANIZATIONADMIN_VIEW";
	public static final String ESFORGANIZATIONADMIN_VIEW_CHILD = "ESFORGANIZATIONADMIN_VIEW_CHILD";
	public static final String ESFORGANIZATIONADMIN_UPDATE_INFO = "ESFORGANIZATIONADMIN_UPDATE_INFO";
	public static final String ESFORGANIZATIONADMIN_VIEW_ACTION = "ESFORGANIZATIONADMIN_VIEW_ACTION";
	
	/* ESFSportAssociationPortlet*/
	public static final String ESFSPORTASSOCIATOIN_ADD = "ESFSPORTASSOCIATOIN_ADD";
	public static final String ESFSPORTASSOCIATOIN_VIEW = "ESFSPORTASSOCIATOIN_VIEW";
	
	
	/* ESFCardPortlet*/
	public static final String ESFCARD_CREATE = "ESFCARD_CREATE";
	public static final String ESFCARD_ASSIGN = "ESFCARD_ASSIGN";
	public static final String ESFCARD_SELECT = "ESFCARD_SELECT";
	public static final String ESFCARD_VIEW   = "ESFCARD_VIEW";
	
	/* ESFUserAdminPortlet*/
	public static final String ESFUSERADMIN_ADD = "ESFUSERADMIN_ADD";
	public static final String ESFUSERADMIN_VIEW = "ESFUSERADMIN_VIEW";
	public static final String ESFUSERADMIN_UPDATE = "ESFUSERADMIN_UPDATE";
	public static final String ESFUSERADMIN_ASSIGN_CARD = "ESFUSERADMIN_ASSIGN_CARD";
	
	/* ESFShooterPortlet*/
	public static final String ESFSHOOTER_ADD = "ESFSHOOTER_ADD";
	public static final String ESFSHOOTER_VIEW = "ESFSHOOTER_VIEW";
	public static final String ESFSHOOTER_UPDATE = "ESFSHOOTER_UPDATE";
	public static final String ESFSHOOTER_DOC_ADD = "ESFSHOOTER_DOC_ADD";
	public static final String ESFSHOOTER_DOC_UPDATE = "ESFSHOOTER_DOC_UPDATE";	
	public static final String ESFSHOOTER_GUN_ADD ="ESFSHOOTER_GUN_ADD";
	public static final String ESFSHOOTER_GUN_VIEW_ACTION="ESFSHOOTER_GUN_VIEW_ACTION";
	public static final String ESFSHOOTER_GUN_UPDATE="ESFSHOOTER_GUN_UPDATE";
	public static final String ESFSHOOTER_GUN_DELETE="ESFSHOOTER_GUN_DELETE";	
	public static final String ESFSHOOTER_GUN_CANE_ADD="ESFSHOOTER_GUN_CANE_ADD";
	public static final String ESFSHOOTER_GUN_CANE_VIEW_ACTION="ESFSHOOTER_GUN_CANE_VIEW_ACTION";
	public static final String ESFSHOOTER_GUN_CANE_UPDATE="ESFSHOOTER_GUN_CANE_UPDATE";
	public static final String ESFSHOOTER_GUN_CANE_DELETE="ESFSHOOTER_GUN_CANE_DELETE";
	public static final String ESFSHOOTER_GUN_CATRIDGE_ADD="ESFSHOOTER_GUN_CATRIDGE_ADD";
	public static final String ESFSHOOTER_GUN_CATRIDGE_VIEW_ACTION="ESFSHOOTER_GUN_CATRIDGE_VIEW_ACTION";
	public static final String ESFSHOOTER_GUN_CATRIDGE_DELETE="ESFSHOOTER_GUN_CATRIDGE_DELETE";
	public static final String ESFSHOOTER_ROLE_VIEW_ACTION="ESFSHOOTER_ROLE_VIEW_ACTION";
	public static final String ESFSHOOTER_ROLE_ASSIGN="ESFSHOOTER_ROLE_ASSIGN";
	public static final String ESFSHOOTER_ROLE_DELETE="ESFSHOOTER_ROLE_DELETE";
	public static final String ESFSHOOTER_CHANGE_CARD="ESFSHOOTER_CHANGE_CARD";
	public static final String ESFSHOOTER_REMOVE_CARD="ESFSHOOTER_REMOVE_CARD";
	public static final String ESFSHOOTER_VIEW_CURRICULUM="ESFSHOOTER_VIEW_CURRICULUM";
	
	
	
	/* ESFNatonialDelegationPortlet*/
	public static final String ESFNATIONALDELEGATION_ADD = "ESFNATIONALDELEGATION_ADD";
	public static final String ESFNATIONALDELEGATION_VIEW = "ESFNATIONALDELEGATION_VIEW";
	public static final String ESFNATIONALDELEGATION_UPDATE = "ESFNATIONALDELEGATION_UPDATE";
	public static final String ESFNATIONALDELEGATION_ADD_EX_SHOOTER = "ESFNATIONALDELEGATION_ADD_EX_SHOOTER";
	public static final String ESFNATIONALDELEGATION_SHOOTER_VIEW = "ESFNATIONALDELEGATION_SHOOTER_VIEW";
	public static final String ESFNATIONALDELEGATION_SHOOTER_UPDATE = "ESFNATIONALDELEGATION_SHOOTER_UPDATE";
	public static final String ESFNATIONALDELEGATION_SHOOTER_UPDATE_CARD = "ESFNATIONALDELEGATION_SHOOTER_UPDATE_CARD";
	public static final String ESFNATIONALDELEGATION_UPDATE_START_END_DATE="ESFNATIONALDELEGATION_UPDATE_START_END_DATE";
	public static final String ESFNATIONALDELEGATION_UPDATE_DELIBEDELIB_DATE="ESFNATIONALDELEGATION_UPDATE_DELIBEDELIB_DATE";
	public static final String ESFNATIONALDELEGATION_DELETE="ESFNATIONALDELEGATION_DELETE";
	public static final String ESFNATIONALDELEGATION_VIEW_ACTION="ESFNATIONALDELEGATION_VIEW_ACTION";
	public static final String ESFNATIONALDELEGATION_DOC_ADD="ESFNATIONALDELEGATION_DOC_ADD";
	public static final String ESFNATIONALDELEGATION_DOC_UPDATE="ESFNATIONALDELEGATION_DOC_UPDATE";
	public static final String ESFNATIONALDELEGATION_ROLE_DELETE="ESFNATIONALDELEGATION_ROLE_DELETE";
	public static final String ESFNATIONALDELEGATION_ROLE_VIEW_ACTION="ESFNATIONALDELEGATION_ROLE_VIEW_ACTION";
	public static final String ESFNATIONALDELEGATION_ROLE_ASSIGN="ESFNATIONALDELEGATION_ROLE_ASSIGN";
	public static final String ESFNATIONALDELEGATION_GUN_ADD="ESFNATIONALDELEGATION_GUN_ADD";
	public static final String ESFNATIONALDELEGATION_GUN_CANE_ADD="ESFNATIONALDELEGATION_GUN_CANE_ADD";
	public static final String ESFNATIONALDELEGATION_GUN_CATRIDGE_ADD="ESFNATIONALDELEGATION_GUN_CATRIDGE_ADD";
	public static final String ESFNATIONALDELEGATION_GUN_CATRIDGE_VIEW ="ESFNATIONALDELEGATION_GUN_CATRIDGE_ADD";
	public static final String ESFNATIONALDELEGATION_GUN_VIEW="ESFNATIONALDELEGATION_GUN_VIEW";
	public static final String ESFNATIONALDELEGATION_GUN_CANE_VIEW="ESFNATIONALDELEGATION_GUN_CANE_VIEW";
	public static final String ESFNATIONALDELEGATION_ADD_EX_SHOOTER_DOUBLE_TRAP = "ESFNATIONALDELEGATION_ADD_EX_SHOOTER_DOUBLE_TRAP";
	public static final String ESFNATIONALDELEGATION_ADD_EX_SHOOTER_FOSSA_OLIMPICA__TRAP = "ESFNATIONALDELEGATION_ADD_EX_SHOOTER_FOSSA_OLIMPICA__TRAP";
	public static final String ESFNATIONALDELEGATION_ADD_EX_SHOOTER_SKEET = "ESFNATIONALDELEGATION_ADD_EX_SHOOTER_SKEET";
	
	/* ESFNatonialMatchPortlet*/
	public static final String ESFNATIONALMATCH_ADD = "ESFNATIONALMATCH_ADD";
	public static final String ESFNATIONALMATCH_ADD_EX_SHOOTER_DOUBLE_TRAP = "ESFNATIONALMATCH_ADD_EX_SHOOTER_DOUBLE_TRAP";
	public static final String ESFNATIONALMATCH_ADD_EX_SHOOTER_SKEET = "ESFNATIONALMATCH_ADD_EX_SHOOTER_SKEET";
	public static final String ESFNATIONALMATCH_ADD_EX_SHOOTER_FOSSA_OLIMPICA = "ESFNATIONALMATCH_ADD_EX_SHOOTER_FOSSA_OLIMPICA";
	public static final String ESFNATIONALMATCH_VIEW_ACTION="ESFNATIONALMATCH_VIEW_ACTION";
	public static final String ESFNATIONALMATCH_VIEW_MATCH="ESFNATIONALMATCH_VIEW_MATCH";
	public static final String ESFNATIONALMATCH_VIEW_FILE="ESFNATIONALMATCH_VIEW_FILE";
	public static final String ESFNATIONALMATCH_UPLOAD_FILE="ESFNATIONALMATCH_UPLOAD_FILE";
	public static final String ESFNATIONALMATCH_VIEW_ADD_DESCRIPTION="ESFNATIONALMATCH_VIEW_ADD_DESCRIPTION";
	public static final String ESFNATIONALMATCH_VIEW_ADD_MATCH_TYPE="ESFNATIONALMATCH_VIEW_ADD_MATCH_TYPE";
	public static final String ESFNATIONALMATCH_VIEW_ADD_ASSOCIATION="ESFNATIONALMATCH_VIEW_ADD_ASSOCIATION";
	public static final String ESFNATIONALMATCH_VIEW_DELETE_ASSOCIATION="ESFNATIONALMATCH_VIEW_DELETE_ASSOCIATION";
	public static final String ESFNATIONALMATCH_UPDATE="ESFNATIONALMATCH_UPDATE";
	public static final String ESFNATIONALMATCH_VIEW_STAFF="ESFNATIONALMATCH_VIEW_STAFF";
	public static final String ESFNATIONALMATCH_EDIT_STAFF="ESFNATIONALMATCH_EDIT_STAFF";
	public static final String ESFNATIONALMATCH_DELETE_STAFF="ESFNATIONALMATCH_DELETE_STAFF";	
	public static final String ESFNATIONALMATCH_VIEW_RESULT="ESFNATIONALMATCH_VIEW_RESULT";
	public static final String ESFNATIONALMATCH_UPDATE_RESULT="ESFNATIONALMATCH_UPDATE_RESULT";	
	public static final String ESFNATIONALMATCH_VIEW_SHOOTER="ESFNATIONALMATCH_VIEW_SHOOTER";
	public static final String ESFNATIONALMATCH_EDIT_SHOOTER_DELETE="ESFNATIONALMATCH_EDIT_SHOOTER_DELETE";
	public static final String ESFNATIONALMATCH_EDIT_SHOOTER_ADD="ESFNATIONALMATCH_EDIT_SHOOTER_ADD";	
	public static final String ESFNATIONALMATCH_EDIT_SHOOTER_ADD_DOC="ESFNATIONALMATCH_EDIT_SHOOTER_ADD_DOC";
	public static final String ESFNATIONALMATCH_EDIT_SHOOTER_UPDATE="ESFNATIONALMATCH_EDIT_SHOOTER_UPDATE";	
	public static final String ESFNATIONALMATCH_EDIT_SHOOTER_CHANGE_CARD="ESFNATIONALMATCH_EDIT_SHOOTER_CHANGE_CARD";
	public static final String ESFNATIONALMATCH_VIEW_NATIONAL_SHOOTER="ESFNATIONALMATCH_VIEW_NATIONAL_SHOOTER";
	public static final String ESFNATIONALMATCH_EDIT_NATIONAL_SHOOTER_DELETE="ESFNATIONALMATCH_EDIT_NATIONAL_SHOOTER_DELETE";
	public static final String ESFNATIONALMATCH_EDIT_NATIONAL_SHOOTER_ADD="ESFNATIONALMATCH_EDIT_NATIONAL_SHOOTER_ADD";
	public static final String ESFNATIONALMATCH_DELETE="ESFNATIONALMATCH_DELETE";
	public static final String ESFNATIONALMATCH_MANAGEMENT="ESFNATIONALMATCH_MANAGEMENT";
	public static final String ESFNATIONALMATCH_UPDATE_ITINERARY="ESFNATIONALMATCH_UPDATE_ITINERARY";
	public static final String ESFNATIONALMATCH_ITINERARY_ADD_DEPARTURE="ESFNATIONALMATCH_ITINERARY_ADD_DEPARTURE";	
	public static final String ESFNATIONALMATCH_ITINERARY_UPDATE_DEPARTURE="ESFNATIONALMATCH_ITINERARY_UPDATE_DEPARTURE";
	public static final String ESFNATIONALMATCH_ITINERARY_DELETE_DEPARTURE="ESFNATIONALMATCH_ITINERARY_DELETE_DEPARTURE";
	public static final String ESFNATIONALMATCH_ITINERARY_DELETE_USER_FROM_DEPARTURE="ESFNATIONALMATCH_ITINERARY_DELETE_USER_FROM_DEPARTURE";
	public static final String ESFNATIONALMATCH_ITINERARY_ADD_USER_FROM_DEPARTURE="ESFNATIONALMATCH_ITINERARY_ADD_USER_FROM_DEPARTURE";
	public static final String ESFNATIONALMATCH_ITINERARY_ADD_AIRPORT="ESFNATIONALMATCH_ITINERARY_ADD_AIRPORT";
	public static final String ESFNATIONALMATCH_ITINERARY_ADD_ITINERARY="ESFNATIONALMATCH_ITINERARY_ADD_ITINERARY";
	public static final String ESFNATIONALMATCH_DOC_UPDATE="ESFNATIONALMATCH_DOC_UPDATE";
	public static final String ESFNATIONALMATCH_ROLE_DELETE="ESFNATIONALMATCH_ROLE_DELETE";
	public static final String ESFNATIONALMATCH_ROLE_VIEW_ACTION="ESFNATIONALMATCH_ROLE_VIEW_ACTION";
	public static final String ESFNATIONALMATCH_ROLE_ASSIGN="ESFNATIONALMATCH_ROLE_ASSIGN";
	public static final String ESFNATIONALMATCH_GUN_ADD="ESFNATIONALMATCH_GUN_ADD";
	public static final String ESFNATIONALMATCH_GUN_CANE_ADD="ESFNATIONALMATCH_GUN_CANE_ADD";
	public static final String ESFNATIONALMATCH_GUN_CATRIDGE_ADD="ESFNATIONALMATCH_GUN_CATRIDGE_ADD";
	public static final String ESFNATIONALMATCH_GUN_VIEW="ESFNATIONALMATCH_GUN_VIEW";
	public static final String ESFNATIONALMATCH_GUN_CANE_VIEW="ESFNATIONALMATCH_GUN_CANE_VIEW";
	public static final String ESFNATIONALMATCH_GUN_CATRIDGE_VIEW="ESFNATIONALMATCH_GUN_CATRIDGE_VIEW";
	public static final String ESFNATIONALMATCH_GENERATE_DOCUEMNT="ESFNATIONALMATCH_GENERATE_DOCUEMNT";
	
	
	/* ESFNormalMatchPortlet*/
	public static final String ESFNORMALMATCH_ADD = "ESFNORMALMATCH_ADD";
	public static final String ESFNORMALMATCH_VIEW_ACTION = "ESFNORMALMATCH_VIEW_ACTION";
	public static final String ESFNORMALMATCH_VIEW = "ESFNORMALMATCH_VIEW";
	public static final String ESFNORMALMATCH_VIEW_STAFF = "ESFNORMALMATCH_VIEW_STAFF";	
	public static final String ESFNORMALMATCH_UPDATE_STAFF_ADD = "ESFNORMALMATCH_UPDATE_STAFF_ADD";	
	public static final String ESFNORMALMATCH_UPDATE_STAFF_REMOVE = "ESFNORMALMATCH_UPDATE_STAFF_REMOVE";	
	public static final String ESFNORMALMATCH_VIEW_RESULT = "ESFNORMALMATCH_VIEW_RESULT";
	public static final String ESFNORMALMATCH_DELETE = "ESFNORMALMATCH_DELETE";
	public static final String ESFNORMALMATCH_MATCHTYPE_ADD = "ESFNORMALMATCH_MATCHTYPE_ADD";
	public static final String ESFNORMALMATCH_DESCRIPTION_ADD = "ESFNORMALMATCH_DESCRIPTION_ADD";
	public static final String ESFNORMALMATCH_UPDATE = "ESFNORMALMATCH_UPDATE";
	public static final String ESFNORMALMATCH_UPLOAD_RESULT = "ESFNORMALMATCH_UPLOAD_RESULT";
	
	
	/* ESFOrganizationDisplay */
	public static final String ESFORGANIZATIONDISPLAY_UPDATE = "ESFORGANIZATIONDISPLAY_UPDATE";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_CODE = "ESFORGANIZATIONDISPLAY_UPDATE_CODE";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_NAME= "ESFORGANIZATIONDISPLAY_UPDATE_NAME";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_FIELD = "ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_FIELD";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_LEGAL = "ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_LEGAL";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_MAIL= "ESFORGANIZATIONDISPLAY_UPDATE_ADDRESS_MAIL";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_AFFILIATION = "ESFORGANIZATIONDISPLAY_UPDATE_AFFILIATION";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_FISCAL_CODE = "ESFORGANIZATIONDISPLAY_UPDATE_FISCAL_CODE";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_STATE = "ESFORGANIZATIONDISPLAY_UPDATE_STATE";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_CONI = "ESFORGANIZATIONDISPLAY_UPDATE_CONI";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_MORE_DEATILS = "ESFORGANIZATIONDISPLAY_UPDATE_MORE_DEATILS";
	public static final String ESFORGANIZATIONDISPLAY_UPDATE_ASSOCIATED_COMPANY = "ESFORGANIZATIONDISPLAY_UPDATE_ASSOCIATED_COMPANY";
	
	
	
	/* ESFBDO */
	public static final String ESFBDO_UPDATE = "ESFBDO_UPDATE";
	public static final String ESFBDO_UPDATE_ADD = "ESFBDO_UPDATE_ADD";
	public static final String ESFBDO_UPDATE_REMOVE = "ESFBDO_UPDATE_REMOVE";
	
	
	/* ESFField */
	public static final String ESFFIELD_ADD = "ESFFIELD_ADD";
	public static final String ESFFIELD_VIEW_ACTION_ENABLE = "ESFFIELD_VIEW_ACTION_ENABLE";
	public static final String ESFFIELD_VIEW_ACTION_DISABLE = "ESFFIELD_VIEW_ACTION_DISABLE";
	public static final String ESFFIELD_UPDATE = "ESFFIELD_UPDATE";
	public static final String ESFFIELD_GIVEWAY = "ESFFIELD_GIVEWAY";
	public static final String ESFFIELD_RETURN_GIVEWAY = "ESFFIELD_RETURN_GIVEWAY";
	public static final String ESFFIELD_UPDATE_STATE = "ESFFIELD_UPDATE_STATE";
	
	
	/* ESFOrganizationUnitService */
	public static final String ESFORGANIZATIONUNITSERVICE_ADD = "ESFORGANIZATIONUNITSERVICE_ADD";
	public static final String ESFORGANIZATIONUNITSERVICE_VIEW_ACTION = "ESFORGANIZATIONUNITSERVICE_VIEW_ACTION";
	public static final String ESFORGANIZATIONUNITSERVICE_UPDATE = "ESFORGANIZATIONUNITSERVICE_UPDATE";
	public static final String ESFORGANIZATIONUNITSERVICE_DELETE = "ESFORGANIZATIONUNITSERVICE_DELETE";

	
	/* ESFGun */
	public static final String ESFGUN_ADD = "ESFGUN_ADD";
	public static final String ESFGUNCATEGORIZTION_ADD = "ESFGUNCATEGORIZTION_ADD";
	public static final String ESFGUN_VIEW_ACTION = "ESFGUN_VIEW_ACTION";
	public static final String ESFGUN_UPDATE = "ESFGUN_UPDATE";
	public static final String ESFGUN_DELETE = "ESFGUN_DELETE";
	public static final String ESFGUN_ASSIGN = "ESFGUN_ASSIGN";
	public static final String ESFGUN_PERMISSION = "ESFGUN_PERMISSION";
	
	
	/* ESFSHOOTERCATEGORY */
	public static final String ESFSHOOTERCATEGORY_ADD = "ESFSHOOTERCATEGORY_ADD";
	public static final String ESFSHOOTERCATEGORY_ACTION_VIEW = "ESFSHOOTERCATEGORY_ACTION_VIEW";
	public static final String ESFSHOOTERCATEGORY_UPDATE = "ESFSHOOTERCATEGORY_UPDATE";
	public static final String ESFSHOOTERCATEGORY_DELETE = "ESFSHOOTERCATEGORY_DELETE";
	
	
	/* ESFGUNCATEGORIZATION */
	public static final String ESFGUNCATEGORIZZATION_ADD = "ESFGUNCATEGORIZZATION_ADD";
	public static final String ESFGUNCATEGORIZZATION__ACTION_VIEW = "ESFGUNCATEGORIZZATION__ACTION_VIEW";
	public static final String ESFGUNCATEGORIZZATION__UPDATE = "ESFGUNCATEGORIZZATION__UPDATE";
	public static final String ESFGUNCATEGORIZZATION__DELETE = "ESFGUNCATEGORIZZATION__DELETE";
	public static final String ESFGUNCATEGORIZZATION__VIEW = "ESFGUNCATEGORIZZATION__VIEW";
	public static final String ESFGUNCATEGORIZZATION__PERMISSION = "ESFGUNCATEGORIZZATION__PERMISSION";
	
	
	/* ESFCONFIGURATIONSTATE */
	public static final String ESFCONFIGURATIONSTATE_ADD = "ESFCONFIGURATIONSTATE_ADD";
	public static final String ESFCONFIGURATIONSTATE_VIEW_ACTION = "ESFCONFIGURATIONSTATE_VIEW_ACTION";
	public static final String ESFCONFIGURATIONSTATE_UPDATE = "ESFCONFIGURATIONSTATE_UPDATE";
	public static final String ESFCONFIGURATIONSTATE_DELETE = "ESFCONFIGURATIONSTATE_DELETE";
	public static final String ESFCONFIGURATIONSTATE_ASSIGN = "ESFCONFIGURATIONSTATE_ASSIGN";
	
	
	/* ESFDESCRIPTION */
	public static final String ESFDESCRIPTION_ADD = "ESFDESCRIPTION_ADD";
	public static final String ESFDESCRIPTION_VIEW_ACTION = "ESFDESCRIPTION_VIEW_ACTION";
	public static final String ESFDESCRIPTION_DELETE = "ESFDESCRIPTION_DELETE";
	public static final String ESFDESCRIPTION_UPDATE = "ESFDESCRIPTION_UPDATE";
	
	
	/* ESFELECTRONIC */
	public static final String ESFELECTRONIC_ADD = "ESFELECTRONIC_ADD";
	public static final String ESFELECTRONIC_VIEW_ACTION = "ESFELECTRONIC_VIEW_ACTION";
	public static final String ESFELECTRONIC_UPDATE = "ESFELECTRONIC_UPDATE";
	public static final String ESFELECTRONIC_DELETE = "ESFELECTRONIC_DELETE";
	public static final String ESFELECTRONIC_PERMISSION = "ESFELECTRONIC_PERMISSION";
	
	
	/* ESFBRAND */
	public static final String ESFBRAND_ADD = "ESFBRAND_ADD";
	public static final String ESFBRAND_VIEW_ACTION = "ESFBRAND_VIEW_ACTION";
	public static final String ESFBRAND_UPDATE = "ESFBRAND_UPDATE";
	public static final String ESFBRAND_DELETE = "ESFBRAND_DELETE";
	public static final String ESFBRAND_PERMISSION = "ESFBRAND_PERMISSION";
	
	
	/* ESFSHOOTERQUALIFICATION */
	public static final String ESFSHOOTERQUALIFICATION_ADD = "ESFSHOOTERQUALIFICATION_ADD";
	public static final String ESFSHOOTERQUALIFICATION_VIEW_ACTION = "ESFSHOOTERQUALIFICATION_VIEW_ACTION";
	public static final String ESFSHOOTERQUALIFICATION_UPDATE = "ESFSHOOTERQUALIFICATION_UPDATE";
	public static final String ESFSHOOTERQUALIFICATION_DELETE = "ESFSHOOTERQUALIFICATION_DELETE";
	
	
	/* ESFUSERROLE */
	public static final String ESFUSERROLE_ADD = "ESFUSERROLE_ADD";
	public static final String ESFUSERROLE_EDIT = "ESFUSERROLE_EDIT";
	public static final String ESFUSERROLE_STATE = "ESFUSERROLE_STATE";
	public static final String ESFUSERROLE_ASSIGN = "ESFUSERROLE_ASSIGN";
	public static final String ESFUSERROLE_PERMISSION = "ESFUSERROLE_PERMISSION";
	public static final String ESFUSERROLE_DEFINEPERMISSION = "ESFUSERROLE_DEFINEPERMISSION";
	public static final String ESFUSERROLE_VIEWACTION = "ESFUSERROLE_VIEWACTION";
	
	
	/* ESFUNITSERVICE */
	public static final String ESFUNITSERVICE_ADD = "ESFUNITSERVICE_ADD";
	public static final String ESFUNITSERVICE_VIEW_ACTION = "ESFUNITSERVICE_VIEW_ACTION";
	public static final String ESFUNITSERVICE_UPDATE = "ESFUNITSERVICE_UPDATE";
	public static final String ESFUNITSERVICE_DELETE = "ESFUNITSERVICE_DELETE";
	public static final String ESFUNITSERVICE_PERMISSION = "ESFUNITSERVICE_PERMISSION";
	
	/* ESFMATCHTYPE */
	public static final String ESFMATCHTYPE_ADD = "ESFMATCHTYPE_ADD";
	public static final String ESFMATCHTYPE_VIEW_ACTION = "ESFMATCHTYPE_VIEW_ACTION";
	public static final String ESFMATCHTYPE_UPDATE = "ESFMATCHTYPE_UPDATE";
	public static final String ESFMATCHTYPE_DELETE = "ESFMATCHTYPE_DELETE";
	
	
	/* ESFSPORTTYPE*/
	public static final String ESFSPORTTYPE_ADD = "ESFSPORTTYPE_ADD";
	public static final String ESFSPORTTYPE_VIEW_ACTION = "ESFSPORTTYPE_VIEW_ACTION";
	public static final String ESFSPORTTYPE_UPDATE = "ESFSPORTTYPE_UPDATE";
	public static final String ESFSPORTTYPE_DELETE = "ESFSPORTTYPE_DELETE";
	public static final String ESFSPORTTYPE_PERMISSION = "ESFSPORTTYPE_PERMISSION";
	
	/*ESFShooterPass*/
	public static final String ESFGENERATE_PASS = "ESFGENERATE_PASS";
	
	
}