/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFMatchResult service. Represents a row in the &quot;ESFMatchResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFMatchResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFMatchResultImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFMatchResult
 * @see it.ethica.esf.model.impl.ESFMatchResultImpl
 * @see it.ethica.esf.model.impl.ESFMatchResultModelImpl
 * @generated
 */
public interface ESFMatchResultModel extends BaseModel<ESFMatchResult>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f match result model instance should use the {@link ESFMatchResult} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f match result.
	 *
	 * @return the primary key of this e s f match result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f match result.
	 *
	 * @param primaryKey the primary key of this e s f match result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf match result ID of this e s f match result.
	 *
	 * @return the esf match result ID of this e s f match result
	 */
	public long getEsfMatchResultId();

	/**
	 * Sets the esf match result ID of this e s f match result.
	 *
	 * @param esfMatchResultId the esf match result ID of this e s f match result
	 */
	public void setEsfMatchResultId(long esfMatchResultId);

	/**
	 * Returns the group ID of this e s f match result.
	 *
	 * @return the group ID of this e s f match result
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f match result.
	 *
	 * @param groupId the group ID of this e s f match result
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f match result.
	 *
	 * @return the company ID of this e s f match result
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f match result.
	 *
	 * @param companyId the company ID of this e s f match result
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f match result.
	 *
	 * @return the user ID of this e s f match result
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f match result.
	 *
	 * @param userId the user ID of this e s f match result
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f match result.
	 *
	 * @return the user uuid of this e s f match result
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f match result.
	 *
	 * @param userUuid the user uuid of this e s f match result
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f match result.
	 *
	 * @return the user name of this e s f match result
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f match result.
	 *
	 * @param userName the user name of this e s f match result
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f match result.
	 *
	 * @return the create date of this e s f match result
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f match result.
	 *
	 * @param createDate the create date of this e s f match result
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f match result.
	 *
	 * @return the modified date of this e s f match result
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f match result.
	 *
	 * @param modifiedDate the modified date of this e s f match result
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the esf match ID of this e s f match result.
	 *
	 * @return the esf match ID of this e s f match result
	 */
	public long getEsfMatchId();

	/**
	 * Sets the esf match ID of this e s f match result.
	 *
	 * @param esfMatchId the esf match ID of this e s f match result
	 */
	public void setEsfMatchId(long esfMatchId);

	/**
	 * Returns the esf partecipant ID of this e s f match result.
	 *
	 * @return the esf partecipant ID of this e s f match result
	 */
	public long getEsfPartecipantId();

	/**
	 * Sets the esf partecipant ID of this e s f match result.
	 *
	 * @param esfPartecipantId the esf partecipant ID of this e s f match result
	 */
	public void setEsfPartecipantId(long esfPartecipantId);

	/**
	 * Returns the card code of this e s f match result.
	 *
	 * @return the card code of this e s f match result
	 */
	@AutoEscape
	public String getCardCode();

	/**
	 * Sets the card code of this e s f match result.
	 *
	 * @param cardCode the card code of this e s f match result
	 */
	public void setCardCode(String cardCode);

	/**
	 * Returns the general class position of this e s f match result.
	 *
	 * @return the general class position of this e s f match result
	 */
	public int getGeneralClassPosition();

	/**
	 * Sets the general class position of this e s f match result.
	 *
	 * @param generalClassPosition the general class position of this e s f match result
	 */
	public void setGeneralClassPosition(int generalClassPosition);

	/**
	 * Returns the category class position of this e s f match result.
	 *
	 * @return the category class position of this e s f match result
	 */
	public int getCategoryClassPosition();

	/**
	 * Sets the category class position of this e s f match result.
	 *
	 * @param categoryClassPosition the category class position of this e s f match result
	 */
	public void setCategoryClassPosition(int categoryClassPosition);

	/**
	 * Returns the category name of this e s f match result.
	 *
	 * @return the category name of this e s f match result
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this e s f match result.
	 *
	 * @param categoryName the category name of this e s f match result
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the qualification of this e s f match result.
	 *
	 * @return the qualification of this e s f match result
	 */
	@AutoEscape
	public String getQualification();

	/**
	 * Sets the qualification of this e s f match result.
	 *
	 * @param qualification the qualification of this e s f match result
	 */
	public void setQualification(String qualification);

	/**
	 * Returns the first of this e s f match result.
	 *
	 * @return the first of this e s f match result
	 */
	public int getFirst();

	/**
	 * Sets the first of this e s f match result.
	 *
	 * @param first the first of this e s f match result
	 */
	public void setFirst(int first);

	/**
	 * Returns the second of this e s f match result.
	 *
	 * @return the second of this e s f match result
	 */
	public int getSecond();

	/**
	 * Sets the second of this e s f match result.
	 *
	 * @param second the second of this e s f match result
	 */
	public void setSecond(int second);

	/**
	 * Returns the third of this e s f match result.
	 *
	 * @return the third of this e s f match result
	 */
	public int getThird();

	/**
	 * Sets the third of this e s f match result.
	 *
	 * @param third the third of this e s f match result
	 */
	public void setThird(int third);

	/**
	 * Returns the fourth of this e s f match result.
	 *
	 * @return the fourth of this e s f match result
	 */
	public int getFourth();

	/**
	 * Sets the fourth of this e s f match result.
	 *
	 * @param fourth the fourth of this e s f match result
	 */
	public void setFourth(int fourth);

	/**
	 * Returns the fifth of this e s f match result.
	 *
	 * @return the fifth of this e s f match result
	 */
	public int getFifth();

	/**
	 * Sets the fifth of this e s f match result.
	 *
	 * @param fifth the fifth of this e s f match result
	 */
	public void setFifth(int fifth);

	/**
	 * Returns the total of this e s f match result.
	 *
	 * @return the total of this e s f match result
	 */
	public int getTotal();

	/**
	 * Sets the total of this e s f match result.
	 *
	 * @param total the total of this e s f match result
	 */
	public void setTotal(int total);

	/**
	 * Returns the first play off of this e s f match result.
	 *
	 * @return the first play off of this e s f match result
	 */
	public int getFirstPlayOff();

	/**
	 * Sets the first play off of this e s f match result.
	 *
	 * @param firstPlayOff the first play off of this e s f match result
	 */
	public void setFirstPlayOff(int firstPlayOff);

	/**
	 * Returns the second play off of this e s f match result.
	 *
	 * @return the second play off of this e s f match result
	 */
	public int getSecondPlayOff();

	/**
	 * Sets the second play off of this e s f match result.
	 *
	 * @param secondPlayOff the second play off of this e s f match result
	 */
	public void setSecondPlayOff(int secondPlayOff);

	/**
	 * Returns the third play off of this e s f match result.
	 *
	 * @return the third play off of this e s f match result
	 */
	public int getThirdPlayOff();

	/**
	 * Sets the third play off of this e s f match result.
	 *
	 * @param thirdPlayOff the third play off of this e s f match result
	 */
	public void setThirdPlayOff(int thirdPlayOff);

	/**
	 * Returns the total after play off of this e s f match result.
	 *
	 * @return the total after play off of this e s f match result
	 */
	public int getTotalAfterPlayOff();

	/**
	 * Sets the total after play off of this e s f match result.
	 *
	 * @param totalAfterPlayOff the total after play off of this e s f match result
	 */
	public void setTotalAfterPlayOff(int totalAfterPlayOff);

	/**
	 * Returns the next first play off of this e s f match result.
	 *
	 * @return the next first play off of this e s f match result
	 */
	public int getNextFirstPlayOff();

	/**
	 * Sets the next first play off of this e s f match result.
	 *
	 * @param nextFirstPlayOff the next first play off of this e s f match result
	 */
	public void setNextFirstPlayOff(int nextFirstPlayOff);

	/**
	 * Returns the next second play off of this e s f match result.
	 *
	 * @return the next second play off of this e s f match result
	 */
	public int getNextSecondPlayOff();

	/**
	 * Sets the next second play off of this e s f match result.
	 *
	 * @param nextSecondPlayOff the next second play off of this e s f match result
	 */
	public void setNextSecondPlayOff(int nextSecondPlayOff);

	/**
	 * Returns the next total play off of this e s f match result.
	 *
	 * @return the next total play off of this e s f match result
	 */
	public int getNextTotalPlayOff();

	/**
	 * Sets the next total play off of this e s f match result.
	 *
	 * @param nextTotalPlayOff the next total play off of this e s f match result
	 */
	public void setNextTotalPlayOff(int nextTotalPlayOff);

	/**
	 * Returns the fiscal code of this e s f match result.
	 *
	 * @return the fiscal code of this e s f match result
	 */
	@AutoEscape
	public String getFiscalCode();

	/**
	 * Sets the fiscal code of this e s f match result.
	 *
	 * @param fiscalCode the fiscal code of this e s f match result
	 */
	public void setFiscalCode(String fiscalCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFMatchResult esfMatchResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFMatchResult> toCacheModel();

	@Override
	public ESFMatchResult toEscapedModel();

	@Override
	public ESFMatchResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}