/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFMatchType service. Represents a row in the &quot;ESFMatchType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFMatchTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFMatchTypeImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFMatchType
 * @see it.ethica.esf.model.impl.ESFMatchTypeImpl
 * @see it.ethica.esf.model.impl.ESFMatchTypeModelImpl
 * @generated
 */
public interface ESFMatchTypeModel extends BaseModel<ESFMatchType>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f match type model instance should use the {@link ESFMatchType} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f match type.
	 *
	 * @return the primary key of this e s f match type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f match type.
	 *
	 * @param primaryKey the primary key of this e s f match type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf match type ID of this e s f match type.
	 *
	 * @return the esf match type ID of this e s f match type
	 */
	public long getEsfMatchTypeId();

	/**
	 * Sets the esf match type ID of this e s f match type.
	 *
	 * @param esfMatchTypeId the esf match type ID of this e s f match type
	 */
	public void setEsfMatchTypeId(long esfMatchTypeId);

	/**
	 * Returns the group ID of this e s f match type.
	 *
	 * @return the group ID of this e s f match type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f match type.
	 *
	 * @param groupId the group ID of this e s f match type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f match type.
	 *
	 * @return the company ID of this e s f match type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f match type.
	 *
	 * @param companyId the company ID of this e s f match type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f match type.
	 *
	 * @return the user ID of this e s f match type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f match type.
	 *
	 * @param userId the user ID of this e s f match type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f match type.
	 *
	 * @return the user uuid of this e s f match type
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f match type.
	 *
	 * @param userUuid the user uuid of this e s f match type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f match type.
	 *
	 * @return the user name of this e s f match type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f match type.
	 *
	 * @param userName the user name of this e s f match type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f match type.
	 *
	 * @return the create date of this e s f match type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f match type.
	 *
	 * @param createDate the create date of this e s f match type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f match type.
	 *
	 * @return the modified date of this e s f match type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f match type.
	 *
	 * @param modifiedDate the modified date of this e s f match type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this e s f match type.
	 *
	 * @return the name of this e s f match type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f match type.
	 *
	 * @param name the name of this e s f match type
	 */
	public void setName(String name);

	/**
	 * Returns the is category qualification of this e s f match type.
	 *
	 * @return the is category qualification of this e s f match type
	 */
	public boolean getIsCategoryQualification();

	/**
	 * Returns <code>true</code> if this e s f match type is is category qualification.
	 *
	 * @return <code>true</code> if this e s f match type is is category qualification; <code>false</code> otherwise
	 */
	public boolean isIsCategoryQualification();

	/**
	 * Sets whether this e s f match type is is category qualification.
	 *
	 * @param isCategoryQualification the is category qualification of this e s f match type
	 */
	public void setIsCategoryQualification(boolean isCategoryQualification);

	/**
	 * Returns the is national of this e s f match type.
	 *
	 * @return the is national of this e s f match type
	 */
	public boolean getIsNational();

	/**
	 * Returns <code>true</code> if this e s f match type is is national.
	 *
	 * @return <code>true</code> if this e s f match type is is national; <code>false</code> otherwise
	 */
	public boolean isIsNational();

	/**
	 * Sets whether this e s f match type is is national.
	 *
	 * @param isNational the is national of this e s f match type
	 */
	public void setIsNational(boolean isNational);

	/**
	 * Returns the code of this e s f match type.
	 *
	 * @return the code of this e s f match type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f match type.
	 *
	 * @param code the code of this e s f match type
	 */
	public void setCode(String code);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFMatchType esfMatchType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFMatchType> toCacheModel();

	@Override
	public ESFMatchType toEscapedModel();

	@Override
	public ESFMatchType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}