/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFPartecipantInfo service. Represents a row in the &quot;ESFPartecipantInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFPartecipantInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFPartecipantInfoImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFPartecipantInfo
 * @see it.ethica.esf.model.impl.ESFPartecipantInfoImpl
 * @see it.ethica.esf.model.impl.ESFPartecipantInfoModelImpl
 * @generated
 */
public interface ESFPartecipantInfoModel extends BaseModel<ESFPartecipantInfo>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f partecipant info model instance should use the {@link ESFPartecipantInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f partecipant info.
	 *
	 * @return the primary key of this e s f partecipant info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f partecipant info.
	 *
	 * @param primaryKey the primary key of this e s f partecipant info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf partecipant info ID of this e s f partecipant info.
	 *
	 * @return the esf partecipant info ID of this e s f partecipant info
	 */
	public long getEsfPartecipantInfoId();

	/**
	 * Sets the esf partecipant info ID of this e s f partecipant info.
	 *
	 * @param esfPartecipantInfoId the esf partecipant info ID of this e s f partecipant info
	 */
	public void setEsfPartecipantInfoId(long esfPartecipantInfoId);

	/**
	 * Returns the group ID of this e s f partecipant info.
	 *
	 * @return the group ID of this e s f partecipant info
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f partecipant info.
	 *
	 * @param groupId the group ID of this e s f partecipant info
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f partecipant info.
	 *
	 * @return the company ID of this e s f partecipant info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f partecipant info.
	 *
	 * @param companyId the company ID of this e s f partecipant info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f partecipant info.
	 *
	 * @return the user ID of this e s f partecipant info
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f partecipant info.
	 *
	 * @param userId the user ID of this e s f partecipant info
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f partecipant info.
	 *
	 * @return the user uuid of this e s f partecipant info
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f partecipant info.
	 *
	 * @param userUuid the user uuid of this e s f partecipant info
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f partecipant info.
	 *
	 * @return the user name of this e s f partecipant info
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f partecipant info.
	 *
	 * @param userName the user name of this e s f partecipant info
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f partecipant info.
	 *
	 * @return the create date of this e s f partecipant info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f partecipant info.
	 *
	 * @param createDate the create date of this e s f partecipant info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f partecipant info.
	 *
	 * @return the modified date of this e s f partecipant info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f partecipant info.
	 *
	 * @param modifiedDate the modified date of this e s f partecipant info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the is portal user of this e s f partecipant info.
	 *
	 * @return the is portal user of this e s f partecipant info
	 */
	public boolean getIsPortalUser();

	/**
	 * Returns <code>true</code> if this e s f partecipant info is is portal user.
	 *
	 * @return <code>true</code> if this e s f partecipant info is is portal user; <code>false</code> otherwise
	 */
	public boolean isIsPortalUser();

	/**
	 * Sets whether this e s f partecipant info is is portal user.
	 *
	 * @param isPortalUser the is portal user of this e s f partecipant info
	 */
	public void setIsPortalUser(boolean isPortalUser);

	/**
	 * Returns the esf user ID of this e s f partecipant info.
	 *
	 * @return the esf user ID of this e s f partecipant info
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f partecipant info.
	 *
	 * @param esfUserId the esf user ID of this e s f partecipant info
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f partecipant info.
	 *
	 * @return the esf user uuid of this e s f partecipant info
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f partecipant info.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f partecipant info
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the protocol of this e s f partecipant info.
	 *
	 * @return the protocol of this e s f partecipant info
	 */
	public long getProtocol();

	/**
	 * Sets the protocol of this e s f partecipant info.
	 *
	 * @param protocol the protocol of this e s f partecipant info
	 */
	public void setProtocol(long protocol);

	/**
	 * Returns the first name of this e s f partecipant info.
	 *
	 * @return the first name of this e s f partecipant info
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this e s f partecipant info.
	 *
	 * @param firstName the first name of this e s f partecipant info
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this e s f partecipant info.
	 *
	 * @return the last name of this e s f partecipant info
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this e s f partecipant info.
	 *
	 * @param lastName the last name of this e s f partecipant info
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the place of birth of this e s f partecipant info.
	 *
	 * @return the place of birth of this e s f partecipant info
	 */
	@AutoEscape
	public String getPlaceOfBirth();

	/**
	 * Sets the place of birth of this e s f partecipant info.
	 *
	 * @param placeOfBirth the place of birth of this e s f partecipant info
	 */
	public void setPlaceOfBirth(String placeOfBirth);

	/**
	 * Returns the date of birth of this e s f partecipant info.
	 *
	 * @return the date of birth of this e s f partecipant info
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this e s f partecipant info.
	 *
	 * @param dateOfBirth the date of birth of this e s f partecipant info
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the residence city of this e s f partecipant info.
	 *
	 * @return the residence city of this e s f partecipant info
	 */
	@AutoEscape
	public String getResidenceCity();

	/**
	 * Sets the residence city of this e s f partecipant info.
	 *
	 * @param residenceCity the residence city of this e s f partecipant info
	 */
	public void setResidenceCity(String residenceCity);

	/**
	 * Returns the province of this e s f partecipant info.
	 *
	 * @return the province of this e s f partecipant info
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this e s f partecipant info.
	 *
	 * @param province the province of this e s f partecipant info
	 */
	public void setProvince(String province);

	/**
	 * Returns the zip of this e s f partecipant info.
	 *
	 * @return the zip of this e s f partecipant info
	 */
	public int getZip();

	/**
	 * Sets the zip of this e s f partecipant info.
	 *
	 * @param zip the zip of this e s f partecipant info
	 */
	public void setZip(int zip);

	/**
	 * Returns the address of this e s f partecipant info.
	 *
	 * @return the address of this e s f partecipant info
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this e s f partecipant info.
	 *
	 * @param address the address of this e s f partecipant info
	 */
	public void setAddress(String address);

	/**
	 * Returns the phon number of this e s f partecipant info.
	 *
	 * @return the phon number of this e s f partecipant info
	 */
	@AutoEscape
	public String getPhonNumber();

	/**
	 * Sets the phon number of this e s f partecipant info.
	 *
	 * @param phonNumber the phon number of this e s f partecipant info
	 */
	public void setPhonNumber(String phonNumber);

	/**
	 * Returns the email of this e s f partecipant info.
	 *
	 * @return the email of this e s f partecipant info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this e s f partecipant info.
	 *
	 * @param email the email of this e s f partecipant info
	 */
	public void setEmail(String email);

	/**
	 * Returns the maritial status of this e s f partecipant info.
	 *
	 * @return the maritial status of this e s f partecipant info
	 */
	@AutoEscape
	public String getMaritialStatus();

	/**
	 * Sets the maritial status of this e s f partecipant info.
	 *
	 * @param maritialStatus the maritial status of this e s f partecipant info
	 */
	public void setMaritialStatus(String maritialStatus);

	/**
	 * Returns the fiscal code of this e s f partecipant info.
	 *
	 * @return the fiscal code of this e s f partecipant info
	 */
	@AutoEscape
	public String getFiscalCode();

	/**
	 * Sets the fiscal code of this e s f partecipant info.
	 *
	 * @param fiscalCode the fiscal code of this e s f partecipant info
	 */
	public void setFiscalCode(String fiscalCode);

	/**
	 * Returns the passport of this e s f partecipant info.
	 *
	 * @return the passport of this e s f partecipant info
	 */
	@AutoEscape
	public String getPassport();

	/**
	 * Sets the passport of this e s f partecipant info.
	 *
	 * @param passport the passport of this e s f partecipant info
	 */
	public void setPassport(String passport);

	/**
	 * Returns the released by of this e s f partecipant info.
	 *
	 * @return the released by of this e s f partecipant info
	 */
	@AutoEscape
	public String getReleasedBy();

	/**
	 * Sets the released by of this e s f partecipant info.
	 *
	 * @param releasedBy the released by of this e s f partecipant info
	 */
	public void setReleasedBy(String releasedBy);

	/**
	 * Returns the passport release date of this e s f partecipant info.
	 *
	 * @return the passport release date of this e s f partecipant info
	 */
	public Date getPassportReleaseDate();

	/**
	 * Sets the passport release date of this e s f partecipant info.
	 *
	 * @param passportReleaseDate the passport release date of this e s f partecipant info
	 */
	public void setPassportReleaseDate(Date passportReleaseDate);

	/**
	 * Returns the passport expiration date of this e s f partecipant info.
	 *
	 * @return the passport expiration date of this e s f partecipant info
	 */
	public Date getPassportExpirationDate();

	/**
	 * Sets the passport expiration date of this e s f partecipant info.
	 *
	 * @param passportExpirationDate the passport expiration date of this e s f partecipant info
	 */
	public void setPassportExpirationDate(Date passportExpirationDate);

	/**
	 * Returns the european card number of this e s f partecipant info.
	 *
	 * @return the european card number of this e s f partecipant info
	 */
	@AutoEscape
	public String getEuropeanCardNumber();

	/**
	 * Sets the european card number of this e s f partecipant info.
	 *
	 * @param europeanCardNumber the european card number of this e s f partecipant info
	 */
	public void setEuropeanCardNumber(String europeanCardNumber);

	/**
	 * Returns the european card release date of this e s f partecipant info.
	 *
	 * @return the european card release date of this e s f partecipant info
	 */
	public Date getEuropeanCardReleaseDate();

	/**
	 * Sets the european card release date of this e s f partecipant info.
	 *
	 * @param europeanCardReleaseDate the european card release date of this e s f partecipant info
	 */
	public void setEuropeanCardReleaseDate(Date europeanCardReleaseDate);

	/**
	 * Returns the european card expiration date of this e s f partecipant info.
	 *
	 * @return the european card expiration date of this e s f partecipant info
	 */
	public Date getEuropeanCardExpirationDate();

	/**
	 * Sets the european card expiration date of this e s f partecipant info.
	 *
	 * @param europeanCardExpirationDate the european card expiration date of this e s f partecipant info
	 */
	public void setEuropeanCardExpirationDate(Date europeanCardExpirationDate);

	/**
	 * Returns the gun licence number of this e s f partecipant info.
	 *
	 * @return the gun licence number of this e s f partecipant info
	 */
	@AutoEscape
	public String getGunLicenceNumber();

	/**
	 * Sets the gun licence number of this e s f partecipant info.
	 *
	 * @param gunLicenceNumber the gun licence number of this e s f partecipant info
	 */
	public void setGunLicenceNumber(String gunLicenceNumber);

	/**
	 * Returns the gun licence release date of this e s f partecipant info.
	 *
	 * @return the gun licence release date of this e s f partecipant info
	 */
	public Date getGunLicenceReleaseDate();

	/**
	 * Sets the gun licence release date of this e s f partecipant info.
	 *
	 * @param gunLicenceReleaseDate the gun licence release date of this e s f partecipant info
	 */
	public void setGunLicenceReleaseDate(Date gunLicenceReleaseDate);

	/**
	 * Returns the gun licence expiration date of this e s f partecipant info.
	 *
	 * @return the gun licence expiration date of this e s f partecipant info
	 */
	public Date getGunLicenceExpirationDate();

	/**
	 * Sets the gun licence expiration date of this e s f partecipant info.
	 *
	 * @param gunLicenceExpirationDate the gun licence expiration date of this e s f partecipant info
	 */
	public void setGunLicenceExpirationDate(Date gunLicenceExpirationDate);

	/**
	 * Returns the first gun type of this e s f partecipant info.
	 *
	 * @return the first gun type of this e s f partecipant info
	 */
	@AutoEscape
	public String getFirstGunType();

	/**
	 * Sets the first gun type of this e s f partecipant info.
	 *
	 * @param firstGunType the first gun type of this e s f partecipant info
	 */
	public void setFirstGunType(String firstGunType);

	/**
	 * Returns the first gun kind of this e s f partecipant info.
	 *
	 * @return the first gun kind of this e s f partecipant info
	 */
	@AutoEscape
	public String getFirstGunKind();

	/**
	 * Sets the first gun kind of this e s f partecipant info.
	 *
	 * @param firstGunKind the first gun kind of this e s f partecipant info
	 */
	public void setFirstGunKind(String firstGunKind);

	/**
	 * Returns the first gun caliber of this e s f partecipant info.
	 *
	 * @return the first gun caliber of this e s f partecipant info
	 */
	public double getFirstGunCaliber();

	/**
	 * Sets the first gun caliber of this e s f partecipant info.
	 *
	 * @param firstGunCaliber the first gun caliber of this e s f partecipant info
	 */
	public void setFirstGunCaliber(double firstGunCaliber);

	/**
	 * Returns the first gun code of this e s f partecipant info.
	 *
	 * @return the first gun code of this e s f partecipant info
	 */
	@AutoEscape
	public String getFirstGunCode();

	/**
	 * Sets the first gun code of this e s f partecipant info.
	 *
	 * @param firstGunCode the first gun code of this e s f partecipant info
	 */
	public void setFirstGunCode(String firstGunCode);

	/**
	 * Returns the first gun extra canes of this e s f partecipant info.
	 *
	 * @return the first gun extra canes of this e s f partecipant info
	 */
	@AutoEscape
	public String getFirstGunExtraCanes();

	/**
	 * Sets the first gun extra canes of this e s f partecipant info.
	 *
	 * @param firstGunExtraCanes the first gun extra canes of this e s f partecipant info
	 */
	public void setFirstGunExtraCanes(String firstGunExtraCanes);

	/**
	 * Returns the second gun type of this e s f partecipant info.
	 *
	 * @return the second gun type of this e s f partecipant info
	 */
	@AutoEscape
	public String getSecondGunType();

	/**
	 * Sets the second gun type of this e s f partecipant info.
	 *
	 * @param secondGunType the second gun type of this e s f partecipant info
	 */
	public void setSecondGunType(String secondGunType);

	/**
	 * Returns the second gun kind of this e s f partecipant info.
	 *
	 * @return the second gun kind of this e s f partecipant info
	 */
	@AutoEscape
	public String getSecondGunKind();

	/**
	 * Sets the second gun kind of this e s f partecipant info.
	 *
	 * @param secondGunKind the second gun kind of this e s f partecipant info
	 */
	public void setSecondGunKind(String secondGunKind);

	/**
	 * Returns the second gun caliber of this e s f partecipant info.
	 *
	 * @return the second gun caliber of this e s f partecipant info
	 */
	public double getSecondGunCaliber();

	/**
	 * Sets the second gun caliber of this e s f partecipant info.
	 *
	 * @param secondGunCaliber the second gun caliber of this e s f partecipant info
	 */
	public void setSecondGunCaliber(double secondGunCaliber);

	/**
	 * Returns the second gun code of this e s f partecipant info.
	 *
	 * @return the second gun code of this e s f partecipant info
	 */
	@AutoEscape
	public String getSecondGunCode();

	/**
	 * Sets the second gun code of this e s f partecipant info.
	 *
	 * @param secondGunCode the second gun code of this e s f partecipant info
	 */
	public void setSecondGunCode(String secondGunCode);

	/**
	 * Returns the second gun extra canes of this e s f partecipant info.
	 *
	 * @return the second gun extra canes of this e s f partecipant info
	 */
	@AutoEscape
	public String getSecondGunExtraCanes();

	/**
	 * Sets the second gun extra canes of this e s f partecipant info.
	 *
	 * @param secondGunExtraCanes the second gun extra canes of this e s f partecipant info
	 */
	public void setSecondGunExtraCanes(String secondGunExtraCanes);

	/**
	 * Returns the gun cartridge type of this e s f partecipant info.
	 *
	 * @return the gun cartridge type of this e s f partecipant info
	 */
	@AutoEscape
	public String getGunCartridgeType();

	/**
	 * Sets the gun cartridge type of this e s f partecipant info.
	 *
	 * @param gunCartridgeType the gun cartridge type of this e s f partecipant info
	 */
	public void setGunCartridgeType(String gunCartridgeType);

	/**
	 * Returns the gun cartridge kind of this e s f partecipant info.
	 *
	 * @return the gun cartridge kind of this e s f partecipant info
	 */
	@AutoEscape
	public String getGunCartridgeKind();

	/**
	 * Sets the gun cartridge kind of this e s f partecipant info.
	 *
	 * @param gunCartridgeKind the gun cartridge kind of this e s f partecipant info
	 */
	public void setGunCartridgeKind(String gunCartridgeKind);

	/**
	 * Returns the cartridge caliber of this e s f partecipant info.
	 *
	 * @return the cartridge caliber of this e s f partecipant info
	 */
	@AutoEscape
	public String getCartridgeCaliber();

	/**
	 * Sets the cartridge caliber of this e s f partecipant info.
	 *
	 * @param cartridgeCaliber the cartridge caliber of this e s f partecipant info
	 */
	public void setCartridgeCaliber(String cartridgeCaliber);

	/**
	 * Returns the esf match ID of this e s f partecipant info.
	 *
	 * @return the esf match ID of this e s f partecipant info
	 */
	public long getEsfMatchId();

	/**
	 * Sets the esf match ID of this e s f partecipant info.
	 *
	 * @param esfMatchId the esf match ID of this e s f partecipant info
	 */
	public void setEsfMatchId(long esfMatchId);

	/**
	 * Returns the esf gun type ID one of this e s f partecipant info.
	 *
	 * @return the esf gun type ID one of this e s f partecipant info
	 */
	public long getEsfGunTypeIdOne();

	/**
	 * Sets the esf gun type ID one of this e s f partecipant info.
	 *
	 * @param esfGunTypeIdOne the esf gun type ID one of this e s f partecipant info
	 */
	public void setEsfGunTypeIdOne(long esfGunTypeIdOne);

	/**
	 * Returns the esf gun kind ID one of this e s f partecipant info.
	 *
	 * @return the esf gun kind ID one of this e s f partecipant info
	 */
	public long getEsfGunKindIdOne();

	/**
	 * Sets the esf gun kind ID one of this e s f partecipant info.
	 *
	 * @param esfGunKindIdOne the esf gun kind ID one of this e s f partecipant info
	 */
	public void setEsfGunKindIdOne(long esfGunKindIdOne);

	/**
	 * Returns the esf gun type ID two of this e s f partecipant info.
	 *
	 * @return the esf gun type ID two of this e s f partecipant info
	 */
	public long getEsfGunTypeIdTwo();

	/**
	 * Sets the esf gun type ID two of this e s f partecipant info.
	 *
	 * @param esfGunTypeIdTwo the esf gun type ID two of this e s f partecipant info
	 */
	public void setEsfGunTypeIdTwo(long esfGunTypeIdTwo);

	/**
	 * Returns the esf gun kind ID two of this e s f partecipant info.
	 *
	 * @return the esf gun kind ID two of this e s f partecipant info
	 */
	public long getEsfGunKindIdTwo();

	/**
	 * Sets the esf gun kind ID two of this e s f partecipant info.
	 *
	 * @param esfGunKindIdTwo the esf gun kind ID two of this e s f partecipant info
	 */
	public void setEsfGunKindIdTwo(long esfGunKindIdTwo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFPartecipantInfo esfPartecipantInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFPartecipantInfo> toCacheModel();

	@Override
	public ESFPartecipantInfo toEscapedModel();

	@Override
	public ESFPartecipantInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}