/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.ESFUserESFUserRolePK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFUserESFUserRole service. Represents a row in the &quot;ESFUserESFUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFUserESFUserRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFUserESFUserRoleImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFUserESFUserRole
 * @see it.ethica.esf.model.impl.ESFUserESFUserRoleImpl
 * @see it.ethica.esf.model.impl.ESFUserESFUserRoleModelImpl
 * @generated
 */
public interface ESFUserESFUserRoleModel extends BaseModel<ESFUserESFUserRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f user e s f user role model instance should use the {@link ESFUserESFUserRole} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f user e s f user role.
	 *
	 * @return the primary key of this e s f user e s f user role
	 */
	public ESFUserESFUserRolePK getPrimaryKey();

	/**
	 * Sets the primary key of this e s f user e s f user role.
	 *
	 * @param primaryKey the primary key of this e s f user e s f user role
	 */
	public void setPrimaryKey(ESFUserESFUserRolePK primaryKey);

	/**
	 * Returns the esf user role ID of this e s f user e s f user role.
	 *
	 * @return the esf user role ID of this e s f user e s f user role
	 */
	public long getEsfUserRoleId();

	/**
	 * Sets the esf user role ID of this e s f user e s f user role.
	 *
	 * @param esfUserRoleId the esf user role ID of this e s f user e s f user role
	 */
	public void setEsfUserRoleId(long esfUserRoleId);

	/**
	 * Returns the esf user ID of this e s f user e s f user role.
	 *
	 * @return the esf user ID of this e s f user e s f user role
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f user e s f user role.
	 *
	 * @param esfUserId the esf user ID of this e s f user e s f user role
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f user e s f user role.
	 *
	 * @return the esf user uuid of this e s f user e s f user role
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f user e s f user role.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f user e s f user role
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the esf organization ID of this e s f user e s f user role.
	 *
	 * @return the esf organization ID of this e s f user e s f user role
	 */
	public long getEsfOrganizationId();

	/**
	 * Sets the esf organization ID of this e s f user e s f user role.
	 *
	 * @param esfOrganizationId the esf organization ID of this e s f user e s f user role
	 */
	public void setEsfOrganizationId(long esfOrganizationId);

	/**
	 * Returns the start date of this e s f user e s f user role.
	 *
	 * @return the start date of this e s f user e s f user role
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this e s f user e s f user role.
	 *
	 * @param startDate the start date of this e s f user e s f user role
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this e s f user e s f user role.
	 *
	 * @return the end date of this e s f user e s f user role
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this e s f user e s f user role.
	 *
	 * @param endDate the end date of this e s f user e s f user role
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFUserESFUserRole esfUserESFUserRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFUserESFUserRole> toCacheModel();

	@Override
	public ESFUserESFUserRole toEscapedModel();

	@Override
	public ESFUserESFUserRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}