/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFDocument service. Represents a row in the &quot;ESFDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFDocumentImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFDocument
 * @see it.ethica.esf.model.impl.ESFDocumentImpl
 * @see it.ethica.esf.model.impl.ESFDocumentModelImpl
 * @generated
 */
public interface ESFDocumentModel extends BaseModel<ESFDocument>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f document model instance should use the {@link ESFDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f document.
	 *
	 * @return the primary key of this e s f document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f document.
	 *
	 * @param primaryKey the primary key of this e s f document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f document.
	 *
	 * @return the uuid of this e s f document
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this e s f document.
	 *
	 * @param uuid the uuid of this e s f document
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the esf document ID of this e s f document.
	 *
	 * @return the esf document ID of this e s f document
	 */
	public long getEsfDocumentId();

	/**
	 * Sets the esf document ID of this e s f document.
	 *
	 * @param esfDocumentId the esf document ID of this e s f document
	 */
	public void setEsfDocumentId(long esfDocumentId);

	/**
	 * Returns the group ID of this e s f document.
	 *
	 * @return the group ID of this e s f document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f document.
	 *
	 * @param groupId the group ID of this e s f document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f document.
	 *
	 * @return the company ID of this e s f document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f document.
	 *
	 * @param companyId the company ID of this e s f document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f document.
	 *
	 * @return the user ID of this e s f document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f document.
	 *
	 * @param userId the user ID of this e s f document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f document.
	 *
	 * @return the user uuid of this e s f document
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f document.
	 *
	 * @param userUuid the user uuid of this e s f document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f document.
	 *
	 * @return the user name of this e s f document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f document.
	 *
	 * @param userName the user name of this e s f document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f document.
	 *
	 * @return the create date of this e s f document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f document.
	 *
	 * @param createDate the create date of this e s f document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f document.
	 *
	 * @return the modified date of this e s f document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f document.
	 *
	 * @param modifiedDate the modified date of this e s f document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the owner ID of this e s f document.
	 *
	 * @return the owner ID of this e s f document
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this e s f document.
	 *
	 * @param ownerId the owner ID of this e s f document
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the owner type of this e s f document.
	 *
	 * @return the owner type of this e s f document
	 */
	@AutoEscape
	public String getOwnerType();

	/**
	 * Sets the owner type of this e s f document.
	 *
	 * @param ownerType the owner type of this e s f document
	 */
	public void setOwnerType(String ownerType);

	/**
	 * Returns the name of this e s f document.
	 *
	 * @return the name of this e s f document
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f document.
	 *
	 * @param name the name of this e s f document
	 */
	public void setName(String name);

	/**
	 * Returns the number of this e s f document.
	 *
	 * @return the number of this e s f document
	 */
	public long getNumber();

	/**
	 * Sets the number of this e s f document.
	 *
	 * @param number the number of this e s f document
	 */
	public void setNumber(long number);

	/**
	 * Returns the release date of this e s f document.
	 *
	 * @return the release date of this e s f document
	 */
	public Date getReleaseDate();

	/**
	 * Sets the release date of this e s f document.
	 *
	 * @param releaseDate the release date of this e s f document
	 */
	public void setReleaseDate(Date releaseDate);

	/**
	 * Returns the expire date of this e s f document.
	 *
	 * @return the expire date of this e s f document
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this e s f document.
	 *
	 * @param expireDate the expire date of this e s f document
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the issuer of this e s f document.
	 *
	 * @return the issuer of this e s f document
	 */
	@AutoEscape
	public String getIssuer();

	/**
	 * Sets the issuer of this e s f document.
	 *
	 * @param issuer the issuer of this e s f document
	 */
	public void setIssuer(String issuer);

	/**
	 * Returns the contents of this e s f document.
	 *
	 * @return the contents of this e s f document
	 */
	@AutoEscape
	public String getContents();

	/**
	 * Sets the contents of this e s f document.
	 *
	 * @param contents the contents of this e s f document
	 */
	public void setContents(String contents);

	/**
	 * Returns the location reference of this e s f document.
	 *
	 * @return the location reference of this e s f document
	 */
	@AutoEscape
	public String getLocationReference();

	/**
	 * Sets the location reference of this e s f document.
	 *
	 * @param locationReference the location reference of this e s f document
	 */
	public void setLocationReference(String locationReference);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFDocument esfDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFDocument> toCacheModel();

	@Override
	public ESFDocument toEscapedModel();

	@Override
	public ESFDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}