/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFAnnualConiReport service. Represents a row in the &quot;ESFAnnualConiReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFAnnualConiReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFAnnualConiReportImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFAnnualConiReport
 * @see it.ethica.esf.model.impl.ESFAnnualConiReportImpl
 * @see it.ethica.esf.model.impl.ESFAnnualConiReportModelImpl
 * @generated
 */
public interface ESFAnnualConiReportModel extends BaseModel<ESFAnnualConiReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f annual coni report model instance should use the {@link ESFAnnualConiReport} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f annual coni report.
	 *
	 * @return the primary key of this e s f annual coni report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f annual coni report.
	 *
	 * @param primaryKey the primary key of this e s f annual coni report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the annual coni report ID of this e s f annual coni report.
	 *
	 * @return the annual coni report ID of this e s f annual coni report
	 */
	public long getAnnualConiReportId();

	/**
	 * Sets the annual coni report ID of this e s f annual coni report.
	 *
	 * @param annualConiReportId the annual coni report ID of this e s f annual coni report
	 */
	public void setAnnualConiReportId(long annualConiReportId);

	/**
	 * Returns the ass ID of this e s f annual coni report.
	 *
	 * @return the ass ID of this e s f annual coni report
	 */
	public long getAssId();

	/**
	 * Sets the ass ID of this e s f annual coni report.
	 *
	 * @param assId the ass ID of this e s f annual coni report
	 */
	public void setAssId(long assId);

	/**
	 * Returns the year of this e s f annual coni report.
	 *
	 * @return the year of this e s f annual coni report
	 */
	public int getYear();

	/**
	 * Sets the year of this e s f annual coni report.
	 *
	 * @param year the year of this e s f annual coni report
	 */
	public void setYear(int year);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFAnnualConiReport esfAnnualConiReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFAnnualConiReport> toCacheModel();

	@Override
	public ESFAnnualConiReport toEscapedModel();

	@Override
	public ESFAnnualConiReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}