/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFCatridge service. Represents a row in the &quot;ESFCatridge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFCatridgeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFCatridgeImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFCatridge
 * @see it.ethica.esf.model.impl.ESFCatridgeImpl
 * @see it.ethica.esf.model.impl.ESFCatridgeModelImpl
 * @generated
 */
public interface ESFCatridgeModel extends BaseModel<ESFCatridge> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f catridge model instance should use the {@link ESFCatridge} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f catridge.
	 *
	 * @return the primary key of this e s f catridge
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f catridge.
	 *
	 * @param primaryKey the primary key of this e s f catridge
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f catridge.
	 *
	 * @return the uuid of this e s f catridge
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f catridge.
	 *
	 * @param uuid the uuid of this e s f catridge
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf catridge ID of this e s f catridge.
	 *
	 * @return the esf catridge ID of this e s f catridge
	 */
	public long getEsfCatridgeId();

	/**
	 * Sets the esf catridge ID of this e s f catridge.
	 *
	 * @param esfCatridgeId the esf catridge ID of this e s f catridge
	 */
	public void setEsfCatridgeId(long esfCatridgeId);

	/**
	 * Returns the esf user ID of this e s f catridge.
	 *
	 * @return the esf user ID of this e s f catridge
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f catridge.
	 *
	 * @param esfUserId the esf user ID of this e s f catridge
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f catridge.
	 *
	 * @return the esf user uuid of this e s f catridge
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f catridge.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f catridge
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the esf gun type ID of this e s f catridge.
	 *
	 * @return the esf gun type ID of this e s f catridge
	 */
	public long getEsfGunTypeId();

	/**
	 * Sets the esf gun type ID of this e s f catridge.
	 *
	 * @param esfGunTypeId the esf gun type ID of this e s f catridge
	 */
	public void setEsfGunTypeId(long esfGunTypeId);

	/**
	 * Returns the catridge model of this e s f catridge.
	 *
	 * @return the catridge model of this e s f catridge
	 */
	@AutoEscape
	public String getCatridgeModel();

	/**
	 * Sets the catridge model of this e s f catridge.
	 *
	 * @param catridgeModel the catridge model of this e s f catridge
	 */
	public void setCatridgeModel(String catridgeModel);

	/**
	 * Returns the catridge caliber of this e s f catridge.
	 *
	 * @return the catridge caliber of this e s f catridge
	 */
	public long getCatridgeCaliber();

	/**
	 * Sets the catridge caliber of this e s f catridge.
	 *
	 * @param catridgeCaliber the catridge caliber of this e s f catridge
	 */
	public void setCatridgeCaliber(long catridgeCaliber);

	/**
	 * Returns the note of this e s f catridge.
	 *
	 * @return the note of this e s f catridge
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this e s f catridge.
	 *
	 * @param note the note of this e s f catridge
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFCatridge esfCatridge);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFCatridge> toCacheModel();

	@Override
	public ESFCatridge toEscapedModel();

	@Override
	public ESFCatridge toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}