/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFFederalRole service. Represents a row in the &quot;ESFFederalRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFFederalRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFFederalRoleImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFFederalRole
 * @see it.ethica.esf.model.impl.ESFFederalRoleImpl
 * @see it.ethica.esf.model.impl.ESFFederalRoleModelImpl
 * @generated
 */
public interface ESFFederalRoleModel extends BaseModel<ESFFederalRole>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f federal role model instance should use the {@link ESFFederalRole} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f federal role.
	 *
	 * @return the primary key of this e s f federal role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f federal role.
	 *
	 * @param primaryKey the primary key of this e s f federal role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f federal role.
	 *
	 * @return the uuid of this e s f federal role
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this e s f federal role.
	 *
	 * @param uuid the uuid of this e s f federal role
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the esf federal role ID of this e s f federal role.
	 *
	 * @return the esf federal role ID of this e s f federal role
	 */
	public long getEsfFederalRoleId();

	/**
	 * Sets the esf federal role ID of this e s f federal role.
	 *
	 * @param esfFederalRoleId the esf federal role ID of this e s f federal role
	 */
	public void setEsfFederalRoleId(long esfFederalRoleId);

	/**
	 * Returns the group ID of this e s f federal role.
	 *
	 * @return the group ID of this e s f federal role
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f federal role.
	 *
	 * @param groupId the group ID of this e s f federal role
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f federal role.
	 *
	 * @return the company ID of this e s f federal role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f federal role.
	 *
	 * @param companyId the company ID of this e s f federal role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f federal role.
	 *
	 * @return the user ID of this e s f federal role
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f federal role.
	 *
	 * @param userId the user ID of this e s f federal role
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f federal role.
	 *
	 * @return the user uuid of this e s f federal role
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f federal role.
	 *
	 * @param userUuid the user uuid of this e s f federal role
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f federal role.
	 *
	 * @return the user name of this e s f federal role
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f federal role.
	 *
	 * @param userName the user name of this e s f federal role
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f federal role.
	 *
	 * @return the create date of this e s f federal role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f federal role.
	 *
	 * @param createDate the create date of this e s f federal role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f federal role.
	 *
	 * @return the modified date of this e s f federal role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f federal role.
	 *
	 * @param modifiedDate the modified date of this e s f federal role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this e s f federal role.
	 *
	 * @return the code of this e s f federal role
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f federal role.
	 *
	 * @param code the code of this e s f federal role
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this e s f federal role.
	 *
	 * @return the description of this e s f federal role
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f federal role.
	 *
	 * @param description the description of this e s f federal role
	 */
	public void setDescription(String description);

	/**
	 * Returns the regional of this e s f federal role.
	 *
	 * @return the regional of this e s f federal role
	 */
	public boolean getRegional();

	/**
	 * Returns <code>true</code> if this e s f federal role is regional.
	 *
	 * @return <code>true</code> if this e s f federal role is regional; <code>false</code> otherwise
	 */
	public boolean isRegional();

	/**
	 * Sets whether this e s f federal role is regional.
	 *
	 * @param regional the regional of this e s f federal role
	 */
	public void setRegional(boolean regional);

	/**
	 * Returns the provincial of this e s f federal role.
	 *
	 * @return the provincial of this e s f federal role
	 */
	public boolean getProvincial();

	/**
	 * Returns <code>true</code> if this e s f federal role is provincial.
	 *
	 * @return <code>true</code> if this e s f federal role is provincial; <code>false</code> otherwise
	 */
	public boolean isProvincial();

	/**
	 * Sets whether this e s f federal role is provincial.
	 *
	 * @param provincial the provincial of this e s f federal role
	 */
	public void setProvincial(boolean provincial);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFFederalRole esfFederalRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFFederalRole> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFFederalRole toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFFederalRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}