/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFFornitureUser service. Represents a row in the &quot;ESFFornitureUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFFornitureUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFFornitureUserImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFFornitureUser
 * @see it.ethica.esf.model.impl.ESFFornitureUserImpl
 * @see it.ethica.esf.model.impl.ESFFornitureUserModelImpl
 * @generated
 */
public interface ESFFornitureUserModel extends BaseModel<ESFFornitureUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f forniture user model instance should use the {@link ESFFornitureUser} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f forniture user.
	 *
	 * @return the primary key of this e s f forniture user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f forniture user.
	 *
	 * @param primaryKey the primary key of this e s f forniture user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf i d forniture of this e s f forniture user.
	 *
	 * @return the esf i d forniture of this e s f forniture user
	 */
	public long getEsfIDForniture();

	/**
	 * Sets the esf i d forniture of this e s f forniture user.
	 *
	 * @param esfIDForniture the esf i d forniture of this e s f forniture user
	 */
	public void setEsfIDForniture(long esfIDForniture);

	/**
	 * Returns the esf ID user of this e s f forniture user.
	 *
	 * @return the esf ID user of this e s f forniture user
	 */
	public long getEsfIdUser();

	/**
	 * Sets the esf ID user of this e s f forniture user.
	 *
	 * @param esfIdUser the esf ID user of this e s f forniture user
	 */
	public void setEsfIdUser(long esfIdUser);

	/**
	 * Returns the esf quantity of this e s f forniture user.
	 *
	 * @return the esf quantity of this e s f forniture user
	 */
	public long getEsfQuantity();

	/**
	 * Sets the esf quantity of this e s f forniture user.
	 *
	 * @param esfQuantity the esf quantity of this e s f forniture user
	 */
	public void setEsfQuantity(long esfQuantity);

	/**
	 * Returns the esf date assign of this e s f forniture user.
	 *
	 * @return the esf date assign of this e s f forniture user
	 */
	public Date getEsfDateAssign();

	/**
	 * Sets the esf date assign of this e s f forniture user.
	 *
	 * @param esfDateAssign the esf date assign of this e s f forniture user
	 */
	public void setEsfDateAssign(Date esfDateAssign);

	/**
	 * Returns the esf forniture user i d of this e s f forniture user.
	 *
	 * @return the esf forniture user i d of this e s f forniture user
	 */
	public long getEsfFornitureUserID();

	/**
	 * Sets the esf forniture user i d of this e s f forniture user.
	 *
	 * @param esfFornitureUserID the esf forniture user i d of this e s f forniture user
	 */
	public void setEsfFornitureUserID(long esfFornitureUserID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFFornitureUser esfFornitureUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFFornitureUser> toCacheModel();

	@Override
	public ESFFornitureUser toEscapedModel();

	@Override
	public ESFFornitureUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}