/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFFlight service. Represents a row in the &quot;ESFFlight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFFlightModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFFlightImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFFlight
 * @see it.ethica.esf.model.impl.ESFFlightImpl
 * @see it.ethica.esf.model.impl.ESFFlightModelImpl
 * @generated
 */
public interface ESFFlightModel extends BaseModel<ESFFlight>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f flight model instance should use the {@link ESFFlight} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f flight.
	 *
	 * @return the primary key of this e s f flight
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f flight.
	 *
	 * @param primaryKey the primary key of this e s f flight
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf flight ID of this e s f flight.
	 *
	 * @return the esf flight ID of this e s f flight
	 */
	public long getEsfFlightId();

	/**
	 * Sets the esf flight ID of this e s f flight.
	 *
	 * @param esfFlightId the esf flight ID of this e s f flight
	 */
	public void setEsfFlightId(long esfFlightId);

	/**
	 * Returns the group ID of this e s f flight.
	 *
	 * @return the group ID of this e s f flight
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f flight.
	 *
	 * @param groupId the group ID of this e s f flight
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f flight.
	 *
	 * @return the company ID of this e s f flight
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f flight.
	 *
	 * @param companyId the company ID of this e s f flight
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f flight.
	 *
	 * @return the user ID of this e s f flight
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f flight.
	 *
	 * @param userId the user ID of this e s f flight
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f flight.
	 *
	 * @return the user uuid of this e s f flight
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f flight.
	 *
	 * @param userUuid the user uuid of this e s f flight
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f flight.
	 *
	 * @return the user name of this e s f flight
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f flight.
	 *
	 * @param userName the user name of this e s f flight
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f flight.
	 *
	 * @return the create date of this e s f flight
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f flight.
	 *
	 * @param createDate the create date of this e s f flight
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f flight.
	 *
	 * @return the modified date of this e s f flight
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f flight.
	 *
	 * @param modifiedDate the modified date of this e s f flight
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave date of this e s f flight.
	 *
	 * @return the leave date of this e s f flight
	 */
	public Date getLeaveDate();

	/**
	 * Sets the leave date of this e s f flight.
	 *
	 * @param leaveDate the leave date of this e s f flight
	 */
	public void setLeaveDate(Date leaveDate);

	/**
	 * Returns the leave hour of this e s f flight.
	 *
	 * @return the leave hour of this e s f flight
	 */
	@AutoEscape
	public String getLeaveHour();

	/**
	 * Sets the leave hour of this e s f flight.
	 *
	 * @param leaveHour the leave hour of this e s f flight
	 */
	public void setLeaveHour(String leaveHour);

	/**
	 * Returns the arrive date of this e s f flight.
	 *
	 * @return the arrive date of this e s f flight
	 */
	public Date getArriveDate();

	/**
	 * Sets the arrive date of this e s f flight.
	 *
	 * @param arriveDate the arrive date of this e s f flight
	 */
	public void setArriveDate(Date arriveDate);

	/**
	 * Returns the arrive hour of this e s f flight.
	 *
	 * @return the arrive hour of this e s f flight
	 */
	@AutoEscape
	public String getArriveHour();

	/**
	 * Sets the arrive hour of this e s f flight.
	 *
	 * @param arriveHour the arrive hour of this e s f flight
	 */
	public void setArriveHour(String arriveHour);

	/**
	 * Returns the flight code of this e s f flight.
	 *
	 * @return the flight code of this e s f flight
	 */
	@AutoEscape
	public String getFlightCode();

	/**
	 * Sets the flight code of this e s f flight.
	 *
	 * @param flightCode the flight code of this e s f flight
	 */
	public void setFlightCode(String flightCode);

	/**
	 * Returns the company name of this e s f flight.
	 *
	 * @return the company name of this e s f flight
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this e s f flight.
	 *
	 * @param companyName the company name of this e s f flight
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the departure airport of this e s f flight.
	 *
	 * @return the departure airport of this e s f flight
	 */
	@AutoEscape
	public String getDepartureAirport();

	/**
	 * Sets the departure airport of this e s f flight.
	 *
	 * @param departureAirport the departure airport of this e s f flight
	 */
	public void setDepartureAirport(String departureAirport);

	/**
	 * Returns the arrival airport of this e s f flight.
	 *
	 * @return the arrival airport of this e s f flight
	 */
	@AutoEscape
	public String getArrivalAirport();

	/**
	 * Sets the arrival airport of this e s f flight.
	 *
	 * @param arrivalAirport the arrival airport of this e s f flight
	 */
	public void setArrivalAirport(String arrivalAirport);

	/**
	 * Returns the esf match ID of this e s f flight.
	 *
	 * @return the esf match ID of this e s f flight
	 */
	public long getEsfMatchId();

	/**
	 * Sets the esf match ID of this e s f flight.
	 *
	 * @param esfMatchId the esf match ID of this e s f flight
	 */
	public void setEsfMatchId(long esfMatchId);

	/**
	 * Returns the esf user ID of this e s f flight.
	 *
	 * @return the esf user ID of this e s f flight
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f flight.
	 *
	 * @param esfUserId the esf user ID of this e s f flight
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f flight.
	 *
	 * @return the esf user uuid of this e s f flight
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f flight.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f flight
	 */
	public void setEsfUserUuid(String esfUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFFlight esfFlight);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFFlight> toCacheModel();

	@Override
	public ESFFlight toEscapedModel();

	@Override
	public ESFFlight toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}