/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFgunUser service. Represents a row in the &quot;ESFgunUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFgunUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFgunUserImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFgunUser
 * @see it.ethica.esf.model.impl.ESFgunUserImpl
 * @see it.ethica.esf.model.impl.ESFgunUserModelImpl
 * @generated
 */
public interface ESFgunUserModel extends BaseModel<ESFgunUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s fgun user model instance should use the {@link ESFgunUser} interface instead.
	 */

	/**
	 * Returns the primary key of this e s fgun user.
	 *
	 * @return the primary key of this e s fgun user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s fgun user.
	 *
	 * @param primaryKey the primary key of this e s fgun user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf gun user ID of this e s fgun user.
	 *
	 * @return the esf gun user ID of this e s fgun user
	 */
	public long getEsfGunUserId();

	/**
	 * Sets the esf gun user ID of this e s fgun user.
	 *
	 * @param esfGunUserId the esf gun user ID of this e s fgun user
	 */
	public void setEsfGunUserId(long esfGunUserId);

	/**
	 * Returns the esf gun user uuid of this e s fgun user.
	 *
	 * @return the esf gun user uuid of this e s fgun user
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfGunUserUuid() throws SystemException;

	/**
	 * Sets the esf gun user uuid of this e s fgun user.
	 *
	 * @param esfGunUserUuid the esf gun user uuid of this e s fgun user
	 */
	public void setEsfGunUserUuid(String esfGunUserUuid);

	/**
	 * Returns the esf gun ID of this e s fgun user.
	 *
	 * @return the esf gun ID of this e s fgun user
	 */
	public long getEsfGunId();

	/**
	 * Sets the esf gun ID of this e s fgun user.
	 *
	 * @param esfGunId the esf gun ID of this e s fgun user
	 */
	public void setEsfGunId(long esfGunId);

	/**
	 * Returns the esf user ID of this e s fgun user.
	 *
	 * @return the esf user ID of this e s fgun user
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s fgun user.
	 *
	 * @param esfUserId the esf user ID of this e s fgun user
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s fgun user.
	 *
	 * @return the esf user uuid of this e s fgun user
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s fgun user.
	 *
	 * @param esfUserUuid the esf user uuid of this e s fgun user
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the code of this e s fgun user.
	 *
	 * @return the code of this e s fgun user
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s fgun user.
	 *
	 * @param code the code of this e s fgun user
	 */
	public void setCode(String code);

	/**
	 * Returns the is favorite of this e s fgun user.
	 *
	 * @return the is favorite of this e s fgun user
	 */
	public boolean getIsFavorite();

	/**
	 * Returns <code>true</code> if this e s fgun user is is favorite.
	 *
	 * @return <code>true</code> if this e s fgun user is is favorite; <code>false</code> otherwise
	 */
	public boolean isIsFavorite();

	/**
	 * Sets whether this e s fgun user is is favorite.
	 *
	 * @param isFavorite the is favorite of this e s fgun user
	 */
	public void setIsFavorite(boolean isFavorite);

	/**
	 * Returns the type of this e s fgun user.
	 *
	 * @return the type of this e s fgun user
	 */
	public int getType();

	/**
	 * Sets the type of this e s fgun user.
	 *
	 * @param type the type of this e s fgun user
	 */
	public void setType(int type);

	/**
	 * Returns the note of this e s fgun user.
	 *
	 * @return the note of this e s fgun user
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this e s fgun user.
	 *
	 * @param note the note of this e s fgun user
	 */
	public void setNote(String note);

	/**
	 * Returns the esf gunn type ID of this e s fgun user.
	 *
	 * @return the esf gunn type ID of this e s fgun user
	 */
	public long getEsfGunnTypeId();

	/**
	 * Sets the esf gunn type ID of this e s fgun user.
	 *
	 * @param esfGunnTypeId the esf gunn type ID of this e s fgun user
	 */
	public void setEsfGunnTypeId(long esfGunnTypeId);

	/**
	 * Returns the esf gun kind ID of this e s fgun user.
	 *
	 * @return the esf gun kind ID of this e s fgun user
	 */
	public long getEsfGunKindId();

	/**
	 * Sets the esf gun kind ID of this e s fgun user.
	 *
	 * @param esfGunKindId the esf gun kind ID of this e s fgun user
	 */
	public void setEsfGunKindId(long esfGunKindId);

	/**
	 * Returns the type ID of this e s fgun user.
	 *
	 * @return the type ID of this e s fgun user
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this e s fgun user.
	 *
	 * @param typeId the type ID of this e s fgun user
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the esf measures of this e s fgun user.
	 *
	 * @return the esf measures of this e s fgun user
	 */
	@AutoEscape
	public String getEsfMeasures();

	/**
	 * Sets the esf measures of this e s fgun user.
	 *
	 * @param esfMeasures the esf measures of this e s fgun user
	 */
	public void setEsfMeasures(String esfMeasures);

	/**
	 * Returns the esf caliber of this e s fgun user.
	 *
	 * @return the esf caliber of this e s fgun user
	 */
	@AutoEscape
	public String getEsfCaliber();

	/**
	 * Sets the esf caliber of this e s fgun user.
	 *
	 * @param esfCaliber the esf caliber of this e s fgun user
	 */
	public void setEsfCaliber(String esfCaliber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFgunUser esFgunUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFgunUser> toCacheModel();

	@Override
	public ESFgunUser toEscapedModel();

	@Override
	public ESFgunUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}