/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFHistoricalAssociation service. Represents a row in the &quot;ESFHistoricalAssociation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFHistoricalAssociationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFHistoricalAssociationImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFHistoricalAssociation
 * @see it.ethica.esf.model.impl.ESFHistoricalAssociationImpl
 * @see it.ethica.esf.model.impl.ESFHistoricalAssociationModelImpl
 * @generated
 */
public interface ESFHistoricalAssociationModel extends BaseModel<ESFHistoricalAssociation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f historical association model instance should use the {@link ESFHistoricalAssociation} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f historical association.
	 *
	 * @return the primary key of this e s f historical association
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f historical association.
	 *
	 * @param primaryKey the primary key of this e s f historical association
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id historical association of this e s f historical association.
	 *
	 * @return the id historical association of this e s f historical association
	 */
	public long getIdHistoricalAssociation();

	/**
	 * Sets the id historical association of this e s f historical association.
	 *
	 * @param idHistoricalAssociation the id historical association of this e s f historical association
	 */
	public void setIdHistoricalAssociation(long idHistoricalAssociation);

	/**
	 * Returns the name of this e s f historical association.
	 *
	 * @return the name of this e s f historical association
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f historical association.
	 *
	 * @param name the name of this e s f historical association
	 */
	public void setName(String name);

	/**
	 * Returns the code of this e s f historical association.
	 *
	 * @return the code of this e s f historical association
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f historical association.
	 *
	 * @param code the code of this e s f historical association
	 */
	public void setCode(String code);

	/**
	 * Returns the date change of this e s f historical association.
	 *
	 * @return the date change of this e s f historical association
	 */
	public Date getDateChange();

	/**
	 * Sets the date change of this e s f historical association.
	 *
	 * @param dateChange the date change of this e s f historical association
	 */
	public void setDateChange(Date dateChange);

	/**
	 * Returns the end date of this e s f historical association.
	 *
	 * @return the end date of this e s f historical association
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this e s f historical association.
	 *
	 * @param endDate the end date of this e s f historical association
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the organization ID of this e s f historical association.
	 *
	 * @return the organization ID of this e s f historical association
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this e s f historical association.
	 *
	 * @param organizationId the organization ID of this e s f historical association
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the state ID of this e s f historical association.
	 *
	 * @return the state ID of this e s f historical association
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this e s f historical association.
	 *
	 * @param stateId the state ID of this e s f historical association
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the variation ID of this e s f historical association.
	 *
	 * @return the variation ID of this e s f historical association
	 */
	public long getVariationId();

	/**
	 * Sets the variation ID of this e s f historical association.
	 *
	 * @param variationId the variation ID of this e s f historical association
	 */
	public void setVariationId(long variationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFHistoricalAssociation esfHistoricalAssociation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFHistoricalAssociation> toCacheModel();

	@Override
	public ESFHistoricalAssociation toEscapedModel();

	@Override
	public ESFHistoricalAssociation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}