/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFInstructsShootingDirector service. Represents a row in the &quot;ESFInstructsShootingDirector&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFInstructsShootingDirectorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFInstructsShootingDirectorImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFInstructsShootingDirector
 * @see it.ethica.esf.model.impl.ESFInstructsShootingDirectorImpl
 * @see it.ethica.esf.model.impl.ESFInstructsShootingDirectorModelImpl
 * @generated
 */
public interface ESFInstructsShootingDirectorModel extends BaseModel<ESFInstructsShootingDirector> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f instructs shooting director model instance should use the {@link ESFInstructsShootingDirector} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f instructs shooting director.
	 *
	 * @return the primary key of this e s f instructs shooting director
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f instructs shooting director.
	 *
	 * @param primaryKey the primary key of this e s f instructs shooting director
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf instructs shooting director ID of this e s f instructs shooting director.
	 *
	 * @return the esf instructs shooting director ID of this e s f instructs shooting director
	 */
	public long getEsfInstructsShootingDirectorId();

	/**
	 * Sets the esf instructs shooting director ID of this e s f instructs shooting director.
	 *
	 * @param esfInstructsShootingDirectorId the esf instructs shooting director ID of this e s f instructs shooting director
	 */
	public void setEsfInstructsShootingDirectorId(
		long esfInstructsShootingDirectorId);

	/**
	 * Returns the esf instructs shooting director code of this e s f instructs shooting director.
	 *
	 * @return the esf instructs shooting director code of this e s f instructs shooting director
	 */
	@AutoEscape
	public String getEsfInstructsShootingDirectorCode();

	/**
	 * Sets the esf instructs shooting director code of this e s f instructs shooting director.
	 *
	 * @param esfInstructsShootingDirectorCode the esf instructs shooting director code of this e s f instructs shooting director
	 */
	public void setEsfInstructsShootingDirectorCode(
		String esfInstructsShootingDirectorCode);

	/**
	 * Returns the esf instructs shooting director desc of this e s f instructs shooting director.
	 *
	 * @return the esf instructs shooting director desc of this e s f instructs shooting director
	 */
	@AutoEscape
	public String getEsfInstructsShootingDirectorDesc();

	/**
	 * Sets the esf instructs shooting director desc of this e s f instructs shooting director.
	 *
	 * @param esfInstructsShootingDirectorDesc the esf instructs shooting director desc of this e s f instructs shooting director
	 */
	public void setEsfInstructsShootingDirectorDesc(
		String esfInstructsShootingDirectorDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ESFInstructsShootingDirector esfInstructsShootingDirector);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFInstructsShootingDirector> toCacheModel();

	@Override
	public ESFInstructsShootingDirector toEscapedModel();

	@Override
	public ESFInstructsShootingDirector toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}