/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFLentField service. Represents a row in the &quot;ESFLentField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFLentFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFLentFieldImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFLentField
 * @see it.ethica.esf.model.impl.ESFLentFieldImpl
 * @see it.ethica.esf.model.impl.ESFLentFieldModelImpl
 * @generated
 */
public interface ESFLentFieldModel extends BaseModel<ESFLentField> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f lent field model instance should use the {@link ESFLentField} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f lent field.
	 *
	 * @return the primary key of this e s f lent field
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f lent field.
	 *
	 * @param primaryKey the primary key of this e s f lent field
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lent field ID of this e s f lent field.
	 *
	 * @return the lent field ID of this e s f lent field
	 */
	public long getLentFieldId();

	/**
	 * Sets the lent field ID of this e s f lent field.
	 *
	 * @param lentFieldId the lent field ID of this e s f lent field
	 */
	public void setLentFieldId(long lentFieldId);

	/**
	 * Returns the esf entity state ID of this e s f lent field.
	 *
	 * @return the esf entity state ID of this e s f lent field
	 */
	public long getEsfEntityStateId();

	/**
	 * Sets the esf entity state ID of this e s f lent field.
	 *
	 * @param esfEntityStateId the esf entity state ID of this e s f lent field
	 */
	public void setEsfEntityStateId(long esfEntityStateId);

	/**
	 * Returns the esf field ID of this e s f lent field.
	 *
	 * @return the esf field ID of this e s f lent field
	 */
	public long getEsfFieldId();

	/**
	 * Sets the esf field ID of this e s f lent field.
	 *
	 * @param esfFieldId the esf field ID of this e s f lent field
	 */
	public void setEsfFieldId(long esfFieldId);

	/**
	 * Returns the real owner ID of this e s f lent field.
	 *
	 * @return the real owner ID of this e s f lent field
	 */
	public long getRealOwnerId();

	/**
	 * Sets the real owner ID of this e s f lent field.
	 *
	 * @param realOwnerId the real owner ID of this e s f lent field
	 */
	public void setRealOwnerId(long realOwnerId);

	/**
	 * Returns the actual owner ID of this e s f lent field.
	 *
	 * @return the actual owner ID of this e s f lent field
	 */
	public long getActualOwnerId();

	/**
	 * Sets the actual owner ID of this e s f lent field.
	 *
	 * @param actualOwnerId the actual owner ID of this e s f lent field
	 */
	public void setActualOwnerId(long actualOwnerId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFLentField esfLentField);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFLentField> toCacheModel();

	@Override
	public ESFLentField toEscapedModel();

	@Override
	public ESFLentField toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}