/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFRadunoFiles service. Represents a row in the &quot;ESFRadunoFiles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFRadunoFilesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFRadunoFilesImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFRadunoFiles
 * @see it.ethica.esf.model.impl.ESFRadunoFilesImpl
 * @see it.ethica.esf.model.impl.ESFRadunoFilesModelImpl
 * @generated
 */
public interface ESFRadunoFilesModel extends BaseModel<ESFRadunoFiles> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f raduno files model instance should use the {@link ESFRadunoFiles} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f raduno files.
	 *
	 * @return the primary key of this e s f raduno files
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f raduno files.
	 *
	 * @param primaryKey the primary key of this e s f raduno files
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_esf_raduno_files of this e s f raduno files.
	 *
	 * @return the id_esf_raduno_files of this e s f raduno files
	 */
	public long getId_esf_raduno_files();

	/**
	 * Sets the id_esf_raduno_files of this e s f raduno files.
	 *
	 * @param id_esf_raduno_files the id_esf_raduno_files of this e s f raduno files
	 */
	public void setId_esf_raduno_files(long id_esf_raduno_files);

	/**
	 * Returns the id_esf_raduno of this e s f raduno files.
	 *
	 * @return the id_esf_raduno of this e s f raduno files
	 */
	public long getId_esf_raduno();

	/**
	 * Sets the id_esf_raduno of this e s f raduno files.
	 *
	 * @param id_esf_raduno the id_esf_raduno of this e s f raduno files
	 */
	public void setId_esf_raduno(long id_esf_raduno);

	/**
	 * Returns the nome of this e s f raduno files.
	 *
	 * @return the nome of this e s f raduno files
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this e s f raduno files.
	 *
	 * @param nome the nome of this e s f raduno files
	 */
	public void setNome(String nome);

	/**
	 * Returns the path of this e s f raduno files.
	 *
	 * @return the path of this e s f raduno files
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this e s f raduno files.
	 *
	 * @param path the path of this e s f raduno files
	 */
	public void setPath(String path);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFRadunoFiles esfRadunoFiles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFRadunoFiles> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFRadunoFiles toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFRadunoFiles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}