/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.EsfRadunoShootersPK;

import java.io.Serializable;

/**
 * The base model interface for the EsfRadunoShooters service. Represents a row in the &quot;EsfRadunoShooters&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.EsfRadunoShootersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.EsfRadunoShootersImpl}.
 * </p>
 *
 * @author Ethica
 * @see EsfRadunoShooters
 * @see it.ethica.esf.model.impl.EsfRadunoShootersImpl
 * @see it.ethica.esf.model.impl.EsfRadunoShootersModelImpl
 * @generated
 */
public interface EsfRadunoShootersModel extends BaseModel<EsfRadunoShooters> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a esf raduno shooters model instance should use the {@link EsfRadunoShooters} interface instead.
	 */

	/**
	 * Returns the primary key of this esf raduno shooters.
	 *
	 * @return the primary key of this esf raduno shooters
	 */
	public EsfRadunoShootersPK getPrimaryKey();

	/**
	 * Sets the primary key of this esf raduno shooters.
	 *
	 * @param primaryKey the primary key of this esf raduno shooters
	 */
	public void setPrimaryKey(EsfRadunoShootersPK primaryKey);

	/**
	 * Returns the id_esf_raduno_shooters of this esf raduno shooters.
	 *
	 * @return the id_esf_raduno_shooters of this esf raduno shooters
	 */
	public long getId_esf_raduno_shooters();

	/**
	 * Sets the id_esf_raduno_shooters of this esf raduno shooters.
	 *
	 * @param id_esf_raduno_shooters the id_esf_raduno_shooters of this esf raduno shooters
	 */
	public void setId_esf_raduno_shooters(long id_esf_raduno_shooters);

	/**
	 * Returns the id_esf_raduno of this esf raduno shooters.
	 *
	 * @return the id_esf_raduno of this esf raduno shooters
	 */
	public long getId_esf_raduno();

	/**
	 * Sets the id_esf_raduno of this esf raduno shooters.
	 *
	 * @param id_esf_raduno the id_esf_raduno of this esf raduno shooters
	 */
	public void setId_esf_raduno(long id_esf_raduno);

	/**
	 * Returns the user ID of this esf raduno shooters.
	 *
	 * @return the user ID of this esf raduno shooters
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this esf raduno shooters.
	 *
	 * @param userId the user ID of this esf raduno shooters
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this esf raduno shooters.
	 *
	 * @return the user uuid of this esf raduno shooters
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this esf raduno shooters.
	 *
	 * @param userUuid the user uuid of this esf raduno shooters
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.ethica.esf.model.EsfRadunoShooters esfRadunoShooters);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.EsfRadunoShooters> toCacheModel();

	@Override
	public it.ethica.esf.model.EsfRadunoShooters toEscapedModel();

	@Override
	public it.ethica.esf.model.EsfRadunoShooters toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}