/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.ESFStateAssEntityPK;

import java.io.Serializable;

/**
 * The base model interface for the ESFStateAssEntity service. Represents a row in the &quot;ESFStateAssEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFStateAssEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFStateAssEntityImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFStateAssEntity
 * @see it.ethica.esf.model.impl.ESFStateAssEntityImpl
 * @see it.ethica.esf.model.impl.ESFStateAssEntityModelImpl
 * @generated
 */
public interface ESFStateAssEntityModel extends BaseModel<ESFStateAssEntity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f state ass entity model instance should use the {@link ESFStateAssEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f state ass entity.
	 *
	 * @return the primary key of this e s f state ass entity
	 */
	public ESFStateAssEntityPK getPrimaryKey();

	/**
	 * Sets the primary key of this e s f state ass entity.
	 *
	 * @param primaryKey the primary key of this e s f state ass entity
	 */
	public void setPrimaryKey(ESFStateAssEntityPK primaryKey);

	/**
	 * Returns the uuid of this e s f state ass entity.
	 *
	 * @return the uuid of this e s f state ass entity
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f state ass entity.
	 *
	 * @param uuid the uuid of this e s f state ass entity
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf state ID of this e s f state ass entity.
	 *
	 * @return the esf state ID of this e s f state ass entity
	 */
	public long getEsfStateId();

	/**
	 * Sets the esf state ID of this e s f state ass entity.
	 *
	 * @param esfStateId the esf state ID of this e s f state ass entity
	 */
	public void setEsfStateId(long esfStateId);

	/**
	 * Returns the class name of this e s f state ass entity.
	 *
	 * @return the class name of this e s f state ass entity
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this e s f state ass entity.
	 *
	 * @param className the class name of this e s f state ass entity
	 */
	public void setClassName(String className);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFStateAssEntity esfStateAssEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFStateAssEntity> toCacheModel();

	@Override
	public ESFStateAssEntity toEscapedModel();

	@Override
	public ESFStateAssEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}