/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.ESFShooterCategoryESFTournamentPK;

import java.io.Serializable;

/**
 * The base model interface for the ESFShooterCategoryESFTournament service. Represents a row in the &quot;ESFShooterCategoryESFTournament&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFShooterCategoryESFTournamentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFShooterCategoryESFTournamentImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFShooterCategoryESFTournament
 * @see it.ethica.esf.model.impl.ESFShooterCategoryESFTournamentImpl
 * @see it.ethica.esf.model.impl.ESFShooterCategoryESFTournamentModelImpl
 * @generated
 */
public interface ESFShooterCategoryESFTournamentModel extends BaseModel<ESFShooterCategoryESFTournament> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f shooter category e s f tournament model instance should use the {@link ESFShooterCategoryESFTournament} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f shooter category e s f tournament.
	 *
	 * @return the primary key of this e s f shooter category e s f tournament
	 */
	public ESFShooterCategoryESFTournamentPK getPrimaryKey();

	/**
	 * Sets the primary key of this e s f shooter category e s f tournament.
	 *
	 * @param primaryKey the primary key of this e s f shooter category e s f tournament
	 */
	public void setPrimaryKey(ESFShooterCategoryESFTournamentPK primaryKey);

	/**
	 * Returns the uuid of this e s f shooter category e s f tournament.
	 *
	 * @return the uuid of this e s f shooter category e s f tournament
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f shooter category e s f tournament.
	 *
	 * @param uuid the uuid of this e s f shooter category e s f tournament
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf shooter category ID of this e s f shooter category e s f tournament.
	 *
	 * @return the esf shooter category ID of this e s f shooter category e s f tournament
	 */
	public long getEsfShooterCategoryId();

	/**
	 * Sets the esf shooter category ID of this e s f shooter category e s f tournament.
	 *
	 * @param esfShooterCategoryId the esf shooter category ID of this e s f shooter category e s f tournament
	 */
	public void setEsfShooterCategoryId(long esfShooterCategoryId);

	/**
	 * Returns the esf tournament ID of this e s f shooter category e s f tournament.
	 *
	 * @return the esf tournament ID of this e s f shooter category e s f tournament
	 */
	public long getEsfTournamentId();

	/**
	 * Sets the esf tournament ID of this e s f shooter category e s f tournament.
	 *
	 * @param esfTournamentId the esf tournament ID of this e s f shooter category e s f tournament
	 */
	public void setEsfTournamentId(long esfTournamentId);

	/**
	 * Returns the group ID of this e s f shooter category e s f tournament.
	 *
	 * @return the group ID of this e s f shooter category e s f tournament
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f shooter category e s f tournament.
	 *
	 * @param groupId the group ID of this e s f shooter category e s f tournament
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ESFShooterCategoryESFTournament esfShooterCategoryESFTournament);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFShooterCategoryESFTournament> toCacheModel();

	@Override
	public ESFShooterCategoryESFTournament toEscapedModel();

	@Override
	public ESFShooterCategoryESFTournament toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}