/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFShooterAffiliationChrono service. Represents a row in the &quot;ESFShooterAffiliationChrono&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFShooterAffiliationChronoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFShooterAffiliationChronoImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFShooterAffiliationChrono
 * @see it.ethica.esf.model.impl.ESFShooterAffiliationChronoImpl
 * @see it.ethica.esf.model.impl.ESFShooterAffiliationChronoModelImpl
 * @generated
 */
public interface ESFShooterAffiliationChronoModel extends BaseModel<ESFShooterAffiliationChrono> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f shooter affiliation chrono model instance should use the {@link ESFShooterAffiliationChrono} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f shooter affiliation chrono.
	 *
	 * @return the primary key of this e s f shooter affiliation chrono
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f shooter affiliation chrono.
	 *
	 * @param primaryKey the primary key of this e s f shooter affiliation chrono
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf shooter affiliation chrono ID of this e s f shooter affiliation chrono.
	 *
	 * @return the esf shooter affiliation chrono ID of this e s f shooter affiliation chrono
	 */
	public long getEsfShooterAffiliationChronoId();

	/**
	 * Sets the esf shooter affiliation chrono ID of this e s f shooter affiliation chrono.
	 *
	 * @param esfShooterAffiliationChronoId the esf shooter affiliation chrono ID of this e s f shooter affiliation chrono
	 */
	public void setEsfShooterAffiliationChronoId(
		long esfShooterAffiliationChronoId);

	/**
	 * Returns the esfuser ID of this e s f shooter affiliation chrono.
	 *
	 * @return the esfuser ID of this e s f shooter affiliation chrono
	 */
	public long getEsfuserId();

	/**
	 * Sets the esfuser ID of this e s f shooter affiliation chrono.
	 *
	 * @param esfuserId the esfuser ID of this e s f shooter affiliation chrono
	 */
	public void setEsfuserId(long esfuserId);

	/**
	 * Returns the affiliation date of this e s f shooter affiliation chrono.
	 *
	 * @return the affiliation date of this e s f shooter affiliation chrono
	 */
	public Date getAffiliationDate();

	/**
	 * Sets the affiliation date of this e s f shooter affiliation chrono.
	 *
	 * @param affiliationDate the affiliation date of this e s f shooter affiliation chrono
	 */
	public void setAffiliationDate(Date affiliationDate);

	/**
	 * Returns the year of this e s f shooter affiliation chrono.
	 *
	 * @return the year of this e s f shooter affiliation chrono
	 */
	public int getYear();

	/**
	 * Sets the year of this e s f shooter affiliation chrono.
	 *
	 * @param year the year of this e s f shooter affiliation chrono
	 */
	public void setYear(int year);

	/**
	 * Returns the vcampo of this e s f shooter affiliation chrono.
	 *
	 * @return the vcampo of this e s f shooter affiliation chrono
	 */
	@AutoEscape
	public String getVcampo();

	/**
	 * Sets the vcampo of this e s f shooter affiliation chrono.
	 *
	 * @param Vcampo the vcampo of this e s f shooter affiliation chrono
	 */
	public void setVcampo(String Vcampo);

	/**
	 * Returns the payment date of this e s f shooter affiliation chrono.
	 *
	 * @return the payment date of this e s f shooter affiliation chrono
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this e s f shooter affiliation chrono.
	 *
	 * @param paymentDate the payment date of this e s f shooter affiliation chrono
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the payment of this e s f shooter affiliation chrono.
	 *
	 * @return the payment of this e s f shooter affiliation chrono
	 */
	@AutoEscape
	public String getPayment();

	/**
	 * Sets the payment of this e s f shooter affiliation chrono.
	 *
	 * @param payment the payment of this e s f shooter affiliation chrono
	 */
	public void setPayment(String payment);

	/**
	 * Returns the card of this e s f shooter affiliation chrono.
	 *
	 * @return the card of this e s f shooter affiliation chrono
	 */
	@AutoEscape
	public String getCard();

	/**
	 * Sets the card of this e s f shooter affiliation chrono.
	 *
	 * @param card the card of this e s f shooter affiliation chrono
	 */
	public void setCard(String card);

	/**
	 * Returns the esf organization of this e s f shooter affiliation chrono.
	 *
	 * @return the esf organization of this e s f shooter affiliation chrono
	 */
	@AutoEscape
	public String getEsfOrganization();

	/**
	 * Sets the esf organization of this e s f shooter affiliation chrono.
	 *
	 * @param esfOrganization the esf organization of this e s f shooter affiliation chrono
	 */
	public void setEsfOrganization(String esfOrganization);

	/**
	 * Returns the note of this e s f shooter affiliation chrono.
	 *
	 * @return the note of this e s f shooter affiliation chrono
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this e s f shooter affiliation chrono.
	 *
	 * @param note the note of this e s f shooter affiliation chrono
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.ethica.esf.model.ESFShooterAffiliationChrono esfShooterAffiliationChrono);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFShooterAffiliationChrono> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFShooterAffiliationChrono toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFShooterAffiliationChrono toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}