/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFSuspensiveShootingDirector service. Represents a row in the &quot;ESFSuspensiveShootingDirector&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFSuspensiveShootingDirectorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFSuspensiveShootingDirectorImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFSuspensiveShootingDirector
 * @see it.ethica.esf.model.impl.ESFSuspensiveShootingDirectorImpl
 * @see it.ethica.esf.model.impl.ESFSuspensiveShootingDirectorModelImpl
 * @generated
 */
public interface ESFSuspensiveShootingDirectorModel extends BaseModel<ESFSuspensiveShootingDirector> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f suspensive shooting director model instance should use the {@link ESFSuspensiveShootingDirector} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f suspensive shooting director.
	 *
	 * @return the primary key of this e s f suspensive shooting director
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f suspensive shooting director.
	 *
	 * @param primaryKey the primary key of this e s f suspensive shooting director
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf suspensive shooing director ID of this e s f suspensive shooting director.
	 *
	 * @return the esf suspensive shooing director ID of this e s f suspensive shooting director
	 */
	public long getEsfSuspensiveShooingDirectorId();

	/**
	 * Sets the esf suspensive shooing director ID of this e s f suspensive shooting director.
	 *
	 * @param esfSuspensiveShooingDirectorId the esf suspensive shooing director ID of this e s f suspensive shooting director
	 */
	public void setEsfSuspensiveShooingDirectorId(
		long esfSuspensiveShooingDirectorId);

	/**
	 * Returns the esf data of this e s f suspensive shooting director.
	 *
	 * @return the esf data of this e s f suspensive shooting director
	 */
	public Date getEsfData();

	/**
	 * Sets the esf data of this e s f suspensive shooting director.
	 *
	 * @param esfData the esf data of this e s f suspensive shooting director
	 */
	public void setEsfData(Date esfData);

	/**
	 * Returns the esf code data of this e s f suspensive shooting director.
	 *
	 * @return the esf code data of this e s f suspensive shooting director
	 */
	@AutoEscape
	public String getEsfCodeData();

	/**
	 * Sets the esf code data of this e s f suspensive shooting director.
	 *
	 * @param esfCodeData the esf code data of this e s f suspensive shooting director
	 */
	public void setEsfCodeData(String esfCodeData);

	/**
	 * Returns the esf start data of this e s f suspensive shooting director.
	 *
	 * @return the esf start data of this e s f suspensive shooting director
	 */
	public Date getEsfStartData();

	/**
	 * Sets the esf start data of this e s f suspensive shooting director.
	 *
	 * @param esfStartData the esf start data of this e s f suspensive shooting director
	 */
	public void setEsfStartData(Date esfStartData);

	/**
	 * Returns the esf end data of this e s f suspensive shooting director.
	 *
	 * @return the esf end data of this e s f suspensive shooting director
	 */
	public Date getEsfEndData();

	/**
	 * Sets the esf end data of this e s f suspensive shooting director.
	 *
	 * @param esfEndData the esf end data of this e s f suspensive shooting director
	 */
	public void setEsfEndData(Date esfEndData);

	/**
	 * Returns the esf user ID of this e s f suspensive shooting director.
	 *
	 * @return the esf user ID of this e s f suspensive shooting director
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f suspensive shooting director.
	 *
	 * @param esfUserId the esf user ID of this e s f suspensive shooting director
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f suspensive shooting director.
	 *
	 * @return the esf user uuid of this e s f suspensive shooting director
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f suspensive shooting director.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f suspensive shooting director
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the code user of this e s f suspensive shooting director.
	 *
	 * @return the code user of this e s f suspensive shooting director
	 */
	public long getCodeUser();

	/**
	 * Sets the code user of this e s f suspensive shooting director.
	 *
	 * @param codeUser the code user of this e s f suspensive shooting director
	 */
	public void setCodeUser(long codeUser);

	/**
	 * Returns the codice_ sosp of this e s f suspensive shooting director.
	 *
	 * @return the codice_ sosp of this e s f suspensive shooting director
	 */
	public long getCodice_Sosp();

	/**
	 * Sets the codice_ sosp of this e s f suspensive shooting director.
	 *
	 * @param Codice_Sosp the codice_ sosp of this e s f suspensive shooting director
	 */
	public void setCodice_Sosp(long Codice_Sosp);

	/**
	 * Returns the note of this e s f suspensive shooting director.
	 *
	 * @return the note of this e s f suspensive shooting director
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this e s f suspensive shooting director.
	 *
	 * @param note the note of this e s f suspensive shooting director
	 */
	public void setNote(String note);

	/**
	 * Returns the qualif1_ utiliz of this e s f suspensive shooting director.
	 *
	 * @return the qualif1_ utiliz of this e s f suspensive shooting director
	 */
	public long getQualif1_Utiliz();

	/**
	 * Sets the qualif1_ utiliz of this e s f suspensive shooting director.
	 *
	 * @param Qualif1_Utiliz the qualif1_ utiliz of this e s f suspensive shooting director
	 */
	public void setQualif1_Utiliz(long Qualif1_Utiliz);

	/**
	 * Returns the qualif2_ utiliz of this e s f suspensive shooting director.
	 *
	 * @return the qualif2_ utiliz of this e s f suspensive shooting director
	 */
	public long getQualif2_Utiliz();

	/**
	 * Sets the qualif2_ utiliz of this e s f suspensive shooting director.
	 *
	 * @param Qualif2_Utiliz the qualif2_ utiliz of this e s f suspensive shooting director
	 */
	public void setQualif2_Utiliz(long Qualif2_Utiliz);

	/**
	 * Returns the qualif3_ utiliz of this e s f suspensive shooting director.
	 *
	 * @return the qualif3_ utiliz of this e s f suspensive shooting director
	 */
	public long getQualif3_Utiliz();

	/**
	 * Sets the qualif3_ utiliz of this e s f suspensive shooting director.
	 *
	 * @param Qualif3_Utiliz the qualif3_ utiliz of this e s f suspensive shooting director
	 */
	public void setQualif3_Utiliz(long Qualif3_Utiliz);

	/**
	 * Returns the tipo_ gara1_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara1_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara1_noUtil();

	/**
	 * Sets the tipo_ gara1_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara1_noUtil the tipo_ gara1_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara1_noUtil(long Tipo_Gara1_noUtil);

	/**
	 * Returns the tipo_ gara2_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara2_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara2_noUtil();

	/**
	 * Sets the tipo_ gara2_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara2_noUtil the tipo_ gara2_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara2_noUtil(long Tipo_Gara2_noUtil);

	/**
	 * Returns the tipo_ gara3_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara3_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara3_noUtil();

	/**
	 * Sets the tipo_ gara3_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara3_noUtil the tipo_ gara3_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara3_noUtil(long Tipo_Gara3_noUtil);

	/**
	 * Returns the tipo_ gara4_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara4_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara4_noUtil();

	/**
	 * Sets the tipo_ gara4_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara4_noUtil the tipo_ gara4_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara4_noUtil(long Tipo_Gara4_noUtil);

	/**
	 * Returns the tipo_ gara5_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara5_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara5_noUtil();

	/**
	 * Sets the tipo_ gara5_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara5_noUtil the tipo_ gara5_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara5_noUtil(long Tipo_Gara5_noUtil);

	/**
	 * Returns the tipo_ gara6_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara6_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara6_noUtil();

	/**
	 * Sets the tipo_ gara6_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara6_noUtil the tipo_ gara6_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara6_noUtil(long Tipo_Gara6_noUtil);

	/**
	 * Returns the tipo_ gara7_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara7_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara7_noUtil();

	/**
	 * Sets the tipo_ gara7_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara7_noUtil the tipo_ gara7_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara7_noUtil(long Tipo_Gara7_noUtil);

	/**
	 * Returns the tipo_ gara8_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara8_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara8_noUtil();

	/**
	 * Sets the tipo_ gara8_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara8_noUtil the tipo_ gara8_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara8_noUtil(long Tipo_Gara8_noUtil);

	/**
	 * Returns the tipo_ gara9_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara9_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara9_noUtil();

	/**
	 * Sets the tipo_ gara9_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara9_noUtil the tipo_ gara9_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara9_noUtil(long Tipo_Gara9_noUtil);

	/**
	 * Returns the tipo_ gara10_no util of this e s f suspensive shooting director.
	 *
	 * @return the tipo_ gara10_no util of this e s f suspensive shooting director
	 */
	public long getTipo_Gara10_noUtil();

	/**
	 * Sets the tipo_ gara10_no util of this e s f suspensive shooting director.
	 *
	 * @param Tipo_Gara10_noUtil the tipo_ gara10_no util of this e s f suspensive shooting director
	 */
	public void setTipo_Gara10_noUtil(long Tipo_Gara10_noUtil);

	/**
	 * Returns the esf variation data of this e s f suspensive shooting director.
	 *
	 * @return the esf variation data of this e s f suspensive shooting director
	 */
	public Date getEsfVariationData();

	/**
	 * Sets the esf variation data of this e s f suspensive shooting director.
	 *
	 * @param esfVariationData the esf variation data of this e s f suspensive shooting director
	 */
	public void setEsfVariationData(Date esfVariationData);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ESFSuspensiveShootingDirector esfSuspensiveShootingDirector);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFSuspensiveShootingDirector> toCacheModel();

	@Override
	public ESFSuspensiveShootingDirector toEscapedModel();

	@Override
	public ESFSuspensiveShootingDirector toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}