/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFTeam service. Represents a row in the &quot;ESFTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFTeamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFTeamImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFTeam
 * @see it.ethica.esf.model.impl.ESFTeamImpl
 * @see it.ethica.esf.model.impl.ESFTeamModelImpl
 * @generated
 */
public interface ESFTeamModel extends BaseModel<ESFTeam> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f team model instance should use the {@link ESFTeam} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f team.
	 *
	 * @return the primary key of this e s f team
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f team.
	 *
	 * @param primaryKey the primary key of this e s f team
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf team ID of this e s f team.
	 *
	 * @return the esf team ID of this e s f team
	 */
	public long getEsfTeamId();

	/**
	 * Sets the esf team ID of this e s f team.
	 *
	 * @param esfTeamId the esf team ID of this e s f team
	 */
	public void setEsfTeamId(long esfTeamId);

	/**
	 * Returns the esf tournament ID of this e s f team.
	 *
	 * @return the esf tournament ID of this e s f team
	 */
	public long getEsfTournamentId();

	/**
	 * Sets the esf tournament ID of this e s f team.
	 *
	 * @param esfTournamentId the esf tournament ID of this e s f team
	 */
	public void setEsfTournamentId(long esfTournamentId);

	/**
	 * Returns the name of this e s f team.
	 *
	 * @return the name of this e s f team
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f team.
	 *
	 * @param name the name of this e s f team
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFTeam esfTeam);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFTeam> toCacheModel();

	@Override
	public ESFTeam toEscapedModel();

	@Override
	public ESFTeam toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}