/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFUserCategory service. Represents a row in the &quot;ESFUserCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFUserCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFUserCategoryImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFUserCategory
 * @see it.ethica.esf.model.impl.ESFUserCategoryImpl
 * @see it.ethica.esf.model.impl.ESFUserCategoryModelImpl
 * @generated
 */
public interface ESFUserCategoryModel extends BaseModel<ESFUserCategory>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f user category model instance should use the {@link ESFUserCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f user category.
	 *
	 * @return the primary key of this e s f user category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f user category.
	 *
	 * @param primaryKey the primary key of this e s f user category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf user category ID of this e s f user category.
	 *
	 * @return the esf user category ID of this e s f user category
	 */
	public long getEsfUserCategoryId();

	/**
	 * Sets the esf user category ID of this e s f user category.
	 *
	 * @param esfUserCategoryId the esf user category ID of this e s f user category
	 */
	public void setEsfUserCategoryId(long esfUserCategoryId);

	/**
	 * Returns the group ID of this e s f user category.
	 *
	 * @return the group ID of this e s f user category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f user category.
	 *
	 * @param groupId the group ID of this e s f user category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f user category.
	 *
	 * @return the company ID of this e s f user category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f user category.
	 *
	 * @param companyId the company ID of this e s f user category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f user category.
	 *
	 * @return the user ID of this e s f user category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f user category.
	 *
	 * @param userId the user ID of this e s f user category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f user category.
	 *
	 * @return the user uuid of this e s f user category
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f user category.
	 *
	 * @param userUuid the user uuid of this e s f user category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f user category.
	 *
	 * @return the user name of this e s f user category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f user category.
	 *
	 * @param userName the user name of this e s f user category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f user category.
	 *
	 * @return the create date of this e s f user category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f user category.
	 *
	 * @param createDate the create date of this e s f user category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f user category.
	 *
	 * @return the modified date of this e s f user category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f user category.
	 *
	 * @param modifiedDate the modified date of this e s f user category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the esf user ID of this e s f user category.
	 *
	 * @return the esf user ID of this e s f user category
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f user category.
	 *
	 * @param esfUserId the esf user ID of this e s f user category
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f user category.
	 *
	 * @return the esf user uuid of this e s f user category
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f user category.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f user category
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the start date of this e s f user category.
	 *
	 * @return the start date of this e s f user category
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this e s f user category.
	 *
	 * @param startDate the start date of this e s f user category
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this e s f user category.
	 *
	 * @return the end date of this e s f user category
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this e s f user category.
	 *
	 * @param endDate the end date of this e s f user category
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the esf category ID of this e s f user category.
	 *
	 * @return the esf category ID of this e s f user category
	 */
	public long getEsfCategoryId();

	/**
	 * Sets the esf category ID of this e s f user category.
	 *
	 * @param esfCategoryId the esf category ID of this e s f user category
	 */
	public void setEsfCategoryId(long esfCategoryId);

	/**
	 * Returns the esf sport type ID of this e s f user category.
	 *
	 * @return the esf sport type ID of this e s f user category
	 */
	public long getEsfSportTypeId();

	/**
	 * Sets the esf sport type ID of this e s f user category.
	 *
	 * @param esfSportTypeId the esf sport type ID of this e s f user category
	 */
	public void setEsfSportTypeId(long esfSportTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFUserCategory esfUserCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFUserCategory> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFUserCategory toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFUserCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}