/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.VW_AzzurriPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VW_Azzurri service. Represents a row in the &quot;vw_azzurri&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.VW_AzzurriModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.VW_AzzurriImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_Azzurri
 * @see it.ethica.esf.model.impl.VW_AzzurriImpl
 * @see it.ethica.esf.model.impl.VW_AzzurriModelImpl
 * @generated
 */
public interface VW_AzzurriModel extends BaseModel<VW_Azzurri> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v w_ azzurri model instance should use the {@link VW_Azzurri} interface instead.
	 */

	/**
	 * Returns the primary key of this v w_ azzurri.
	 *
	 * @return the primary key of this v w_ azzurri
	 */
	public VW_AzzurriPK getPrimaryKey();

	/**
	 * Sets the primary key of this v w_ azzurri.
	 *
	 * @param primaryKey the primary key of this v w_ azzurri
	 */
	public void setPrimaryKey(VW_AzzurriPK primaryKey);

	/**
	 * Returns the esf national ID of this v w_ azzurri.
	 *
	 * @return the esf national ID of this v w_ azzurri
	 */
	public long getEsfNationalId();

	/**
	 * Sets the esf national ID of this v w_ azzurri.
	 *
	 * @param esfNationalId the esf national ID of this v w_ azzurri
	 */
	public void setEsfNationalId(long esfNationalId);

	/**
	 * Returns the user ID of this v w_ azzurri.
	 *
	 * @return the user ID of this v w_ azzurri
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v w_ azzurri.
	 *
	 * @param userId the user ID of this v w_ azzurri
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v w_ azzurri.
	 *
	 * @return the user uuid of this v w_ azzurri
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v w_ azzurri.
	 *
	 * @param userUuid the user uuid of this v w_ azzurri
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v w_ azzurri.
	 *
	 * @return the user name of this v w_ azzurri
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this v w_ azzurri.
	 *
	 * @param userName the user name of this v w_ azzurri
	 */
	public void setUserName(String userName);

	/**
	 * Returns the esf user ID of this v w_ azzurri.
	 *
	 * @return the esf user ID of this v w_ azzurri
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this v w_ azzurri.
	 *
	 * @param esfUserId the esf user ID of this v w_ azzurri
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this v w_ azzurri.
	 *
	 * @return the esf user uuid of this v w_ azzurri
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this v w_ azzurri.
	 *
	 * @param esfUserUuid the esf user uuid of this v w_ azzurri
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the esf sport type ID of this v w_ azzurri.
	 *
	 * @return the esf sport type ID of this v w_ azzurri
	 */
	public long getEsfSportTypeId();

	/**
	 * Sets the esf sport type ID of this v w_ azzurri.
	 *
	 * @param esfSportTypeId the esf sport type ID of this v w_ azzurri
	 */
	public void setEsfSportTypeId(long esfSportTypeId);

	/**
	 * Returns the start date of this v w_ azzurri.
	 *
	 * @return the start date of this v w_ azzurri
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this v w_ azzurri.
	 *
	 * @param startDate the start date of this v w_ azzurri
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this v w_ azzurri.
	 *
	 * @return the end date of this v w_ azzurri
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this v w_ azzurri.
	 *
	 * @param endDate the end date of this v w_ azzurri
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the name of this v w_ azzurri.
	 *
	 * @return the name of this v w_ azzurri
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this v w_ azzurri.
	 *
	 * @param name the name of this v w_ azzurri
	 */
	public void setName(String name);

	/**
	 * Returns the description of this v w_ azzurri.
	 *
	 * @return the description of this v w_ azzurri
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v w_ azzurri.
	 *
	 * @param description the description of this v w_ azzurri
	 */
	public void setDescription(String description);

	/**
	 * Returns the invitato of this v w_ azzurri.
	 *
	 * @return the invitato of this v w_ azzurri
	 */
	public int getInvitato();

	/**
	 * Sets the invitato of this v w_ azzurri.
	 *
	 * @param invitato the invitato of this v w_ azzurri
	 */
	public void setInvitato(int invitato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VW_Azzurri vw_Azzurri);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VW_Azzurri> toCacheModel();

	@Override
	public VW_Azzurri toEscapedModel();

	@Override
	public VW_Azzurri toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}