/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.vw_datidirettoretiroPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the vw_datidirettoretiro service. Represents a row in the &quot;vw_datidirettoretiro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.vw_datidirettoretiroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.vw_datidirettoretiroImpl}.
 * </p>
 *
 * @author Ethica
 * @see vw_datidirettoretiro
 * @see it.ethica.esf.model.impl.vw_datidirettoretiroImpl
 * @see it.ethica.esf.model.impl.vw_datidirettoretiroModelImpl
 * @generated
 */
public interface vw_datidirettoretiroModel extends BaseModel<vw_datidirettoretiro> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vw_datidirettoretiro model instance should use the {@link vw_datidirettoretiro} interface instead.
	 */

	/**
	 * Returns the primary key of this vw_datidirettoretiro.
	 *
	 * @return the primary key of this vw_datidirettoretiro
	 */
	public vw_datidirettoretiroPK getPrimaryKey();

	/**
	 * Sets the primary key of this vw_datidirettoretiro.
	 *
	 * @param primaryKey the primary key of this vw_datidirettoretiro
	 */
	public void setPrimaryKey(vw_datidirettoretiroPK primaryKey);

	/**
	 * Returns the esfshootingdirectorid of this vw_datidirettoretiro.
	 *
	 * @return the esfshootingdirectorid of this vw_datidirettoretiro
	 */
	public long getEsfshootingdirectorid();

	/**
	 * Sets the esfshootingdirectorid of this vw_datidirettoretiro.
	 *
	 * @param esfshootingdirectorid the esfshootingdirectorid of this vw_datidirettoretiro
	 */
	public void setEsfshootingdirectorid(long esfshootingdirectorid);

	/**
	 * Returns the nome of this vw_datidirettoretiro.
	 *
	 * @return the nome of this vw_datidirettoretiro
	 */
	public long getNome();

	/**
	 * Sets the nome of this vw_datidirettoretiro.
	 *
	 * @param nome the nome of this vw_datidirettoretiro
	 */
	public void setNome(long nome);

	/**
	 * Returns the cognome of this vw_datidirettoretiro.
	 *
	 * @return the cognome of this vw_datidirettoretiro
	 */
	public long getCognome();

	/**
	 * Sets the cognome of this vw_datidirettoretiro.
	 *
	 * @param cognome the cognome of this vw_datidirettoretiro
	 */
	public void setCognome(long cognome);

	/**
	 * Returns the esfstartdata of this vw_datidirettoretiro.
	 *
	 * @return the esfstartdata of this vw_datidirettoretiro
	 */
	public Date getEsfstartdata();

	/**
	 * Sets the esfstartdata of this vw_datidirettoretiro.
	 *
	 * @param esfstartdata the esfstartdata of this vw_datidirettoretiro
	 */
	public void setEsfstartdata(Date esfstartdata);

	/**
	 * Returns the categoryid of this vw_datidirettoretiro.
	 *
	 * @return the categoryid of this vw_datidirettoretiro
	 */
	public long getCategoryid();

	/**
	 * Sets the categoryid of this vw_datidirettoretiro.
	 *
	 * @param categoryid the categoryid of this vw_datidirettoretiro
	 */
	public void setCategoryid(long categoryid);

	/**
	 * Returns the numerotessera of this vw_datidirettoretiro.
	 *
	 * @return the numerotessera of this vw_datidirettoretiro
	 */
	public long getNumerotessera();

	/**
	 * Sets the numerotessera of this vw_datidirettoretiro.
	 *
	 * @param numerotessera the numerotessera of this vw_datidirettoretiro
	 */
	public void setNumerotessera(long numerotessera);

	/**
	 * Returns the codiceregione of this vw_datidirettoretiro.
	 *
	 * @return the codiceregione of this vw_datidirettoretiro
	 */
	public long getCodiceregione();

	/**
	 * Sets the codiceregione of this vw_datidirettoretiro.
	 *
	 * @param codiceregione the codiceregione of this vw_datidirettoretiro
	 */
	public void setCodiceregione(long codiceregione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vw_datidirettoretiro vw_datidirettoretiro);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vw_datidirettoretiro> toCacheModel();

	@Override
	public vw_datidirettoretiro toEscapedModel();

	@Override
	public vw_datidirettoretiro toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}