/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.VW_ESFListaIncarichiPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VW_ESFListaIncarichi service. Represents a row in the &quot;VW_ESFListaIncarichi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.VW_ESFListaIncarichiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.VW_ESFListaIncarichiImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_ESFListaIncarichi
 * @see it.ethica.esf.model.impl.VW_ESFListaIncarichiImpl
 * @see it.ethica.esf.model.impl.VW_ESFListaIncarichiModelImpl
 * @generated
 */
public interface VW_ESFListaIncarichiModel extends BaseModel<VW_ESFListaIncarichi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v w_ e s f lista incarichi model instance should use the {@link VW_ESFListaIncarichi} interface instead.
	 */

	/**
	 * Returns the primary key of this v w_ e s f lista incarichi.
	 *
	 * @return the primary key of this v w_ e s f lista incarichi
	 */
	public VW_ESFListaIncarichiPK getPrimaryKey();

	/**
	 * Sets the primary key of this v w_ e s f lista incarichi.
	 *
	 * @param primaryKey the primary key of this v w_ e s f lista incarichi
	 */
	public void setPrimaryKey(VW_ESFListaIncarichiPK primaryKey);

	/**
	 * Returns the anni precedenti of this v w_ e s f lista incarichi.
	 *
	 * @return the anni precedenti of this v w_ e s f lista incarichi
	 */
	public int getAnniPrecedenti();

	/**
	 * Sets the anni precedenti of this v w_ e s f lista incarichi.
	 *
	 * @param AnniPrecedenti the anni precedenti of this v w_ e s f lista incarichi
	 */
	public void setAnniPrecedenti(int AnniPrecedenti);

	/**
	 * Returns the anno fine incarico of this v w_ e s f lista incarichi.
	 *
	 * @return the anno fine incarico of this v w_ e s f lista incarichi
	 */
	public int getAnnoFineIncarico();

	/**
	 * Sets the anno fine incarico of this v w_ e s f lista incarichi.
	 *
	 * @param AnnoFineIncarico the anno fine incarico of this v w_ e s f lista incarichi
	 */
	public void setAnnoFineIncarico(int AnnoFineIncarico);

	/**
	 * Returns the anno inizio incarico of this v w_ e s f lista incarichi.
	 *
	 * @return the anno inizio incarico of this v w_ e s f lista incarichi
	 */
	public int getAnnoInizioIncarico();

	/**
	 * Sets the anno inizio incarico of this v w_ e s f lista incarichi.
	 *
	 * @param AnnoInizioIncarico the anno inizio incarico of this v w_ e s f lista incarichi
	 */
	public void setAnnoInizioIncarico(int AnnoInizioIncarico);

	/**
	 * Returns the anno corrente of this v w_ e s f lista incarichi.
	 *
	 * @return the anno corrente of this v w_ e s f lista incarichi
	 */
	public int getAnnoCorrente();

	/**
	 * Sets the anno corrente of this v w_ e s f lista incarichi.
	 *
	 * @param AnnoCorrente the anno corrente of this v w_ e s f lista incarichi
	 */
	public void setAnnoCorrente(int AnnoCorrente);

	/**
	 * Returns the nome ruolo of this v w_ e s f lista incarichi.
	 *
	 * @return the nome ruolo of this v w_ e s f lista incarichi
	 */
	@AutoEscape
	public String getNomeRuolo();

	/**
	 * Sets the nome ruolo of this v w_ e s f lista incarichi.
	 *
	 * @param NomeRuolo the nome ruolo of this v w_ e s f lista incarichi
	 */
	public void setNomeRuolo(String NomeRuolo);

	/**
	 * Returns the end date of this v w_ e s f lista incarichi.
	 *
	 * @return the end date of this v w_ e s f lista incarichi
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this v w_ e s f lista incarichi.
	 *
	 * @param endDate the end date of this v w_ e s f lista incarichi
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the start date of this v w_ e s f lista incarichi.
	 *
	 * @return the start date of this v w_ e s f lista incarichi
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this v w_ e s f lista incarichi.
	 *
	 * @param startDate the start date of this v w_ e s f lista incarichi
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the esf user ID of this v w_ e s f lista incarichi.
	 *
	 * @return the esf user ID of this v w_ e s f lista incarichi
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this v w_ e s f lista incarichi.
	 *
	 * @param esfUserId the esf user ID of this v w_ e s f lista incarichi
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this v w_ e s f lista incarichi.
	 *
	 * @return the esf user uuid of this v w_ e s f lista incarichi
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this v w_ e s f lista incarichi.
	 *
	 * @param esfUserUuid the esf user uuid of this v w_ e s f lista incarichi
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the esf organization ID of this v w_ e s f lista incarichi.
	 *
	 * @return the esf organization ID of this v w_ e s f lista incarichi
	 */
	public long getEsfOrganizationId();

	/**
	 * Sets the esf organization ID of this v w_ e s f lista incarichi.
	 *
	 * @param esfOrganizationId the esf organization ID of this v w_ e s f lista incarichi
	 */
	public void setEsfOrganizationId(long esfOrganizationId);

	/**
	 * Returns the last name of this v w_ e s f lista incarichi.
	 *
	 * @return the last name of this v w_ e s f lista incarichi
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this v w_ e s f lista incarichi.
	 *
	 * @param lastName the last name of this v w_ e s f lista incarichi
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the first name of this v w_ e s f lista incarichi.
	 *
	 * @return the first name of this v w_ e s f lista incarichi
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this v w_ e s f lista incarichi.
	 *
	 * @param firstName the first name of this v w_ e s f lista incarichi
	 */
	public void setFirstName(String firstName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VW_ESFListaIncarichi vw_esfListaIncarichi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VW_ESFListaIncarichi> toCacheModel();

	@Override
	public VW_ESFListaIncarichi toEscapedModel();

	@Override
	public VW_ESFListaIncarichi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}