/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.ethica.esf.service.persistence.VW_StaffPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VW_Staff service. Represents a row in the &quot;vw_staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.VW_StaffModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.VW_StaffImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_Staff
 * @see it.ethica.esf.model.impl.VW_StaffImpl
 * @see it.ethica.esf.model.impl.VW_StaffModelImpl
 * @generated
 */
public interface VW_StaffModel extends BaseModel<VW_Staff> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v w_ staff model instance should use the {@link VW_Staff} interface instead.
	 */

	/**
	 * Returns the primary key of this v w_ staff.
	 *
	 * @return the primary key of this v w_ staff
	 */
	public VW_StaffPK getPrimaryKey();

	/**
	 * Sets the primary key of this v w_ staff.
	 *
	 * @param primaryKey the primary key of this v w_ staff
	 */
	public void setPrimaryKey(VW_StaffPK primaryKey);

	/**
	 * Returns the user ID of this v w_ staff.
	 *
	 * @return the user ID of this v w_ staff
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v w_ staff.
	 *
	 * @param userId the user ID of this v w_ staff
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v w_ staff.
	 *
	 * @return the user uuid of this v w_ staff
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v w_ staff.
	 *
	 * @param userUuid the user uuid of this v w_ staff
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the email address of this v w_ staff.
	 *
	 * @return the email address of this v w_ staff
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this v w_ staff.
	 *
	 * @param emailAddress the email address of this v w_ staff
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the first name of this v w_ staff.
	 *
	 * @return the first name of this v w_ staff
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this v w_ staff.
	 *
	 * @param firstName the first name of this v w_ staff
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this v w_ staff.
	 *
	 * @return the last name of this v w_ staff
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this v w_ staff.
	 *
	 * @param lastName the last name of this v w_ staff
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the create date of this v w_ staff.
	 *
	 * @return the create date of this v w_ staff
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this v w_ staff.
	 *
	 * @param createDate the create date of this v w_ staff
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the esf start data of this v w_ staff.
	 *
	 * @return the esf start data of this v w_ staff
	 */
	public Date getEsfStartData();

	/**
	 * Sets the esf start data of this v w_ staff.
	 *
	 * @param esfStartData the esf start data of this v w_ staff
	 */
	public void setEsfStartData(Date esfStartData);

	/**
	 * Returns the esf end data of this v w_ staff.
	 *
	 * @return the esf end data of this v w_ staff
	 */
	public Date getEsfEndData();

	/**
	 * Sets the esf end data of this v w_ staff.
	 *
	 * @param esfEndData the esf end data of this v w_ staff
	 */
	public void setEsfEndData(Date esfEndData);

	/**
	 * Returns the region ID of this v w_ staff.
	 *
	 * @return the region ID of this v w_ staff
	 */
	@AutoEscape
	public String getRegionId();

	/**
	 * Sets the region ID of this v w_ staff.
	 *
	 * @param regionId the region ID of this v w_ staff
	 */
	public void setRegionId(String regionId);

	/**
	 * Returns the province ID of this v w_ staff.
	 *
	 * @return the province ID of this v w_ staff
	 */
	@AutoEscape
	public String getProvinceId();

	/**
	 * Sets the province ID of this v w_ staff.
	 *
	 * @param provinceId the province ID of this v w_ staff
	 */
	public void setProvinceId(String provinceId);

	/**
	 * Returns the esf shooting director qualification desc of this v w_ staff.
	 *
	 * @return the esf shooting director qualification desc of this v w_ staff
	 */
	@AutoEscape
	public String getEsfShootingDirectorQualificationDesc();

	/**
	 * Sets the esf shooting director qualification desc of this v w_ staff.
	 *
	 * @param esfShootingDirectorQualificationDesc the esf shooting director qualification desc of this v w_ staff
	 */
	public void setEsfShootingDirectorQualificationDesc(
		String esfShootingDirectorQualificationDesc);

	/**
	 * Returns the esf sport type ID of this v w_ staff.
	 *
	 * @return the esf sport type ID of this v w_ staff
	 */
	public long getEsfSportTypeId();

	/**
	 * Sets the esf sport type ID of this v w_ staff.
	 *
	 * @param esfSportTypeId the esf sport type ID of this v w_ staff
	 */
	public void setEsfSportTypeId(long esfSportTypeId);

	/**
	 * Returns the name of this v w_ staff.
	 *
	 * @return the name of this v w_ staff
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this v w_ staff.
	 *
	 * @param name the name of this v w_ staff
	 */
	public void setName(String name);

	/**
	 * Returns the invitato of this v w_ staff.
	 *
	 * @return the invitato of this v w_ staff
	 */
	public long getInvitato();

	/**
	 * Sets the invitato of this v w_ staff.
	 *
	 * @param invitato the invitato of this v w_ staff
	 */
	public void setInvitato(long invitato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.VW_Staff vw_Staff);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.VW_Staff> toCacheModel();

	@Override
	public it.ethica.esf.model.VW_Staff toEscapedModel();

	@Override
	public it.ethica.esf.model.VW_Staff toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}