/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFUser;
import it.ethica.esf.model.ESFUserModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFUser service. Represents a row in the &quot;ESFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFUserImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFUserImpl
 * @see it.ethica.esf.model.ESFUser
 * @see it.ethica.esf.model.ESFUserModel
 * @generated
 */
public class ESFUserModelImpl extends BaseModelImpl<ESFUser>
	implements ESFUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f user model instance should use the {@link it.ethica.esf.model.ESFUser} interface instead.
	 */
	public static final String TABLE_NAME = "ESFUser";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfUserId", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "typearmy", Types.BIGINT },
			{ "fiscalCode", Types.VARCHAR },
			{ "birthcity", Types.VARCHAR },
			{ "nationality", Types.VARCHAR },
			{ "isSportsGroups", Types.BOOLEAN },
			{ "job", Types.VARCHAR },
			{ "issfIdNumber", Types.VARCHAR },
			{ "categoryId", Types.BIGINT },
			{ "pin", Types.BIGINT },
			{ "codeUser", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFUser (uuid_ VARCHAR(75) null,esfUserId LONG not null primary key,code_ VARCHAR(75) null,typearmy LONG,fiscalCode VARCHAR(75) null,birthcity VARCHAR(75) null,nationality VARCHAR(75) null,isSportsGroups BOOLEAN,job VARCHAR(75) null,issfIdNumber VARCHAR(75) null,categoryId LONG,pin LONG,codeUser LONG)";
	public static final String TABLE_SQL_DROP = "drop table ESFUser";
	public static final String ORDER_BY_JPQL = " ORDER BY esfUser.esfUserId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFUser.esfUserId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFUser"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFUser"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFUser"),
			true);
	public static long CODE_COLUMN_BITMASK = 1L;
	public static long CODEUSER_COLUMN_BITMASK = 2L;
	public static long ESFUSERID_COLUMN_BITMASK = 4L;
	public static long FISCALCODE_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFUser"));

	public ESFUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFUser.class;
	}

	@Override
	public String getModelClassName() {
		return ESFUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfUserId", getEsfUserId());
		attributes.put("code", getCode());
		attributes.put("typearmy", getTypearmy());
		attributes.put("fiscalCode", getFiscalCode());
		attributes.put("birthcity", getBirthcity());
		attributes.put("nationality", getNationality());
		attributes.put("isSportsGroups", getIsSportsGroups());
		attributes.put("job", getJob());
		attributes.put("issfIdNumber", getIssfIdNumber());
		attributes.put("categoryId", getCategoryId());
		attributes.put("pin", getPin());
		attributes.put("codeUser", getCodeUser());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		Long typearmy = (Long)attributes.get("typearmy");

		if (typearmy != null) {
			setTypearmy(typearmy);
		}

		String fiscalCode = (String)attributes.get("fiscalCode");

		if (fiscalCode != null) {
			setFiscalCode(fiscalCode);
		}

		String birthcity = (String)attributes.get("birthcity");

		if (birthcity != null) {
			setBirthcity(birthcity);
		}

		String nationality = (String)attributes.get("nationality");

		if (nationality != null) {
			setNationality(nationality);
		}

		Boolean isSportsGroups = (Boolean)attributes.get("isSportsGroups");

		if (isSportsGroups != null) {
			setIsSportsGroups(isSportsGroups);
		}

		String job = (String)attributes.get("job");

		if (job != null) {
			setJob(job);
		}

		String issfIdNumber = (String)attributes.get("issfIdNumber");

		if (issfIdNumber != null) {
			setIssfIdNumber(issfIdNumber);
		}

		Long categoryId = (Long)attributes.get("categoryId");

		if (categoryId != null) {
			setCategoryId(categoryId);
		}

		Long pin = (Long)attributes.get("pin");

		if (pin != null) {
			setPin(pin);
		}

		Long codeUser = (Long)attributes.get("codeUser");

		if (codeUser != null) {
			setCodeUser(codeUser);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalEsfUserId) {
			_setOriginalEsfUserId = true;

			_originalEsfUserId = _esfUserId;
		}

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	public long getOriginalEsfUserId() {
		return _originalEsfUserId;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@Override
	public long getTypearmy() {
		return _typearmy;
	}

	@Override
	public void setTypearmy(long typearmy) {
		_typearmy = typearmy;
	}

	@Override
	public String getFiscalCode() {
		if (_fiscalCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _fiscalCode;
		}
	}

	@Override
	public void setFiscalCode(String fiscalCode) {
		_columnBitmask |= FISCALCODE_COLUMN_BITMASK;

		if (_originalFiscalCode == null) {
			_originalFiscalCode = _fiscalCode;
		}

		_fiscalCode = fiscalCode;
	}

	public String getOriginalFiscalCode() {
		return GetterUtil.getString(_originalFiscalCode);
	}

	@Override
	public String getBirthcity() {
		if (_birthcity == null) {
			return StringPool.BLANK;
		}
		else {
			return _birthcity;
		}
	}

	@Override
	public void setBirthcity(String birthcity) {
		_birthcity = birthcity;
	}

	@Override
	public String getNationality() {
		if (_nationality == null) {
			return StringPool.BLANK;
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		_nationality = nationality;
	}

	@Override
	public boolean getIsSportsGroups() {
		return _isSportsGroups;
	}

	@Override
	public boolean isIsSportsGroups() {
		return _isSportsGroups;
	}

	@Override
	public void setIsSportsGroups(boolean isSportsGroups) {
		_isSportsGroups = isSportsGroups;
	}

	@Override
	public String getJob() {
		if (_job == null) {
			return StringPool.BLANK;
		}
		else {
			return _job;
		}
	}

	@Override
	public void setJob(String job) {
		_job = job;
	}

	@Override
	public String getIssfIdNumber() {
		if (_issfIdNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _issfIdNumber;
		}
	}

	@Override
	public void setIssfIdNumber(String issfIdNumber) {
		_issfIdNumber = issfIdNumber;
	}

	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_categoryId = categoryId;
	}

	@Override
	public long getPin() {
		return _pin;
	}

	@Override
	public void setPin(long pin) {
		_pin = pin;
	}

	@Override
	public long getCodeUser() {
		return _codeUser;
	}

	@Override
	public void setCodeUser(long codeUser) {
		_columnBitmask |= CODEUSER_COLUMN_BITMASK;

		if (!_setOriginalCodeUser) {
			_setOriginalCodeUser = true;

			_originalCodeUser = _codeUser;
		}

		_codeUser = codeUser;
	}

	public long getOriginalCodeUser() {
		return _originalCodeUser;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ESFUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFUser toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFUserImpl esfUserImpl = new ESFUserImpl();

		esfUserImpl.setUuid(getUuid());
		esfUserImpl.setEsfUserId(getEsfUserId());
		esfUserImpl.setCode(getCode());
		esfUserImpl.setTypearmy(getTypearmy());
		esfUserImpl.setFiscalCode(getFiscalCode());
		esfUserImpl.setBirthcity(getBirthcity());
		esfUserImpl.setNationality(getNationality());
		esfUserImpl.setIsSportsGroups(getIsSportsGroups());
		esfUserImpl.setJob(getJob());
		esfUserImpl.setIssfIdNumber(getIssfIdNumber());
		esfUserImpl.setCategoryId(getCategoryId());
		esfUserImpl.setPin(getPin());
		esfUserImpl.setCodeUser(getCodeUser());

		esfUserImpl.resetOriginalValues();

		return esfUserImpl;
	}

	@Override
	public int compareTo(ESFUser esfUser) {
		int value = 0;

		if (getEsfUserId() < esfUser.getEsfUserId()) {
			value = -1;
		}
		else if (getEsfUserId() > esfUser.getEsfUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFUser)) {
			return false;
		}

		ESFUser esfUser = (ESFUser)obj;

		long primaryKey = esfUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFUserModelImpl esfUserModelImpl = this;

		esfUserModelImpl._originalUuid = esfUserModelImpl._uuid;

		esfUserModelImpl._originalEsfUserId = esfUserModelImpl._esfUserId;

		esfUserModelImpl._setOriginalEsfUserId = false;

		esfUserModelImpl._originalCode = esfUserModelImpl._code;

		esfUserModelImpl._originalFiscalCode = esfUserModelImpl._fiscalCode;

		esfUserModelImpl._originalCodeUser = esfUserModelImpl._codeUser;

		esfUserModelImpl._setOriginalCodeUser = false;

		esfUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFUser> toCacheModel() {
		ESFUserCacheModel esfUserCacheModel = new ESFUserCacheModel();

		esfUserCacheModel.uuid = getUuid();

		String uuid = esfUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfUserCacheModel.uuid = null;
		}

		esfUserCacheModel.esfUserId = getEsfUserId();

		esfUserCacheModel.code = getCode();

		String code = esfUserCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			esfUserCacheModel.code = null;
		}

		esfUserCacheModel.typearmy = getTypearmy();

		esfUserCacheModel.fiscalCode = getFiscalCode();

		String fiscalCode = esfUserCacheModel.fiscalCode;

		if ((fiscalCode != null) && (fiscalCode.length() == 0)) {
			esfUserCacheModel.fiscalCode = null;
		}

		esfUserCacheModel.birthcity = getBirthcity();

		String birthcity = esfUserCacheModel.birthcity;

		if ((birthcity != null) && (birthcity.length() == 0)) {
			esfUserCacheModel.birthcity = null;
		}

		esfUserCacheModel.nationality = getNationality();

		String nationality = esfUserCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			esfUserCacheModel.nationality = null;
		}

		esfUserCacheModel.isSportsGroups = getIsSportsGroups();

		esfUserCacheModel.job = getJob();

		String job = esfUserCacheModel.job;

		if ((job != null) && (job.length() == 0)) {
			esfUserCacheModel.job = null;
		}

		esfUserCacheModel.issfIdNumber = getIssfIdNumber();

		String issfIdNumber = esfUserCacheModel.issfIdNumber;

		if ((issfIdNumber != null) && (issfIdNumber.length() == 0)) {
			esfUserCacheModel.issfIdNumber = null;
		}

		esfUserCacheModel.categoryId = getCategoryId();

		esfUserCacheModel.pin = getPin();

		esfUserCacheModel.codeUser = getCodeUser();

		return esfUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", typearmy=");
		sb.append(getTypearmy());
		sb.append(", fiscalCode=");
		sb.append(getFiscalCode());
		sb.append(", birthcity=");
		sb.append(getBirthcity());
		sb.append(", nationality=");
		sb.append(getNationality());
		sb.append(", isSportsGroups=");
		sb.append(getIsSportsGroups());
		sb.append(", job=");
		sb.append(getJob());
		sb.append(", issfIdNumber=");
		sb.append(getIssfIdNumber());
		sb.append(", categoryId=");
		sb.append(getCategoryId());
		sb.append(", pin=");
		sb.append(getPin());
		sb.append(", codeUser=");
		sb.append(getCodeUser());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typearmy</column-name><column-value><![CDATA[");
		sb.append(getTypearmy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fiscalCode</column-name><column-value><![CDATA[");
		sb.append(getFiscalCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthcity</column-name><column-value><![CDATA[");
		sb.append(getBirthcity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nationality</column-name><column-value><![CDATA[");
		sb.append(getNationality());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isSportsGroups</column-name><column-value><![CDATA[");
		sb.append(getIsSportsGroups());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>job</column-name><column-value><![CDATA[");
		sb.append(getJob());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>issfIdNumber</column-name><column-value><![CDATA[");
		sb.append(getIssfIdNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pin</column-name><column-value><![CDATA[");
		sb.append(getPin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codeUser</column-name><column-value><![CDATA[");
		sb.append(getCodeUser());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFUser.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFUser.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfUserId;
	private String _esfUserUuid;
	private long _originalEsfUserId;
	private boolean _setOriginalEsfUserId;
	private String _code;
	private String _originalCode;
	private long _typearmy;
	private String _fiscalCode;
	private String _originalFiscalCode;
	private String _birthcity;
	private String _nationality;
	private boolean _isSportsGroups;
	private String _job;
	private String _issfIdNumber;
	private long _categoryId;
	private long _pin;
	private long _codeUser;
	private long _originalCodeUser;
	private boolean _setOriginalCodeUser;
	private long _columnBitmask;
	private ESFUser _escapedModel;
}