/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFCard;
import it.ethica.esf.model.ESFCardModel;
import it.ethica.esf.model.ESFCardSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ESFCard service. Represents a row in the &quot;ESFCard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFCardModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFCardImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFCardImpl
 * @see it.ethica.esf.model.ESFCard
 * @see it.ethica.esf.model.ESFCardModel
 * @generated
 */
@JSON(strict = true)
public class ESFCardModelImpl extends BaseModelImpl<ESFCard>
	implements ESFCardModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f card model instance should use the {@link it.ethica.esf.model.ESFCard} interface instead.
	 */
	public static final String TABLE_NAME = "ESFCard";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfCardId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "codeAlfa", Types.VARCHAR },
			{ "codeNum", Types.BIGINT },
			{ "esfUserId", Types.BIGINT },
			{ "esfOrganizationId", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "oldCode", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFCard (uuid_ VARCHAR(75) null,esfCardId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,codeAlfa VARCHAR(75) null,codeNum LONG,esfUserId LONG,esfOrganizationId LONG,code_ VARCHAR(75) null,oldCode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ESFCard";
	public static final String ORDER_BY_JPQL = " ORDER BY esfCard.codeNum ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFCard.codeNum ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFCard"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFCard"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFCard"),
			true);
	public static long CODE_COLUMN_BITMASK = 1L;
	public static long CODEALFA_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 8L;
	public static long ESFUSERID_COLUMN_BITMASK = 16L;
	public static long GROUPID_COLUMN_BITMASK = 32L;
	public static long OLDCODE_COLUMN_BITMASK = 64L;
	public static long UUID_COLUMN_BITMASK = 128L;
	public static long CODENUM_COLUMN_BITMASK = 256L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ESFCard toModel(ESFCardSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ESFCard model = new ESFCardImpl();

		model.setUuid(soapModel.getUuid());
		model.setEsfCardId(soapModel.getEsfCardId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCodeAlfa(soapModel.getCodeAlfa());
		model.setCodeNum(soapModel.getCodeNum());
		model.setEsfUserId(soapModel.getEsfUserId());
		model.setEsfOrganizationId(soapModel.getEsfOrganizationId());
		model.setCode(soapModel.getCode());
		model.setOldCode(soapModel.getOldCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ESFCard> toModels(ESFCardSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ESFCard> models = new ArrayList<ESFCard>(soapModels.length);

		for (ESFCardSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFCard"));

	public ESFCardModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfCardId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfCardId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfCardId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFCard.class;
	}

	@Override
	public String getModelClassName() {
		return ESFCard.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfCardId", getEsfCardId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("codeAlfa", getCodeAlfa());
		attributes.put("codeNum", getCodeNum());
		attributes.put("esfUserId", getEsfUserId());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("code", getCode());
		attributes.put("oldCode", getOldCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfCardId = (Long)attributes.get("esfCardId");

		if (esfCardId != null) {
			setEsfCardId(esfCardId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String codeAlfa = (String)attributes.get("codeAlfa");

		if (codeAlfa != null) {
			setCodeAlfa(codeAlfa);
		}

		Long codeNum = (Long)attributes.get("codeNum");

		if (codeNum != null) {
			setCodeNum(codeNum);
		}

		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		String oldCode = (String)attributes.get("oldCode");

		if (oldCode != null) {
			setOldCode(oldCode);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEsfCardId() {
		return _esfCardId;
	}

	@Override
	public void setEsfCardId(long esfCardId) {
		_esfCardId = esfCardId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCodeAlfa() {
		if (_codeAlfa == null) {
			return StringPool.BLANK;
		}
		else {
			return _codeAlfa;
		}
	}

	@Override
	public void setCodeAlfa(String codeAlfa) {
		_columnBitmask |= CODEALFA_COLUMN_BITMASK;

		if (_originalCodeAlfa == null) {
			_originalCodeAlfa = _codeAlfa;
		}

		_codeAlfa = codeAlfa;
	}

	public String getOriginalCodeAlfa() {
		return GetterUtil.getString(_originalCodeAlfa);
	}

	@JSON
	@Override
	public long getCodeNum() {
		return _codeNum;
	}

	@Override
	public void setCodeNum(long codeNum) {
		_columnBitmask = -1L;

		_codeNum = codeNum;
	}

	@JSON
	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask |= ESFUSERID_COLUMN_BITMASK;

		if (!_setOriginalEsfUserId) {
			_setOriginalEsfUserId = true;

			_originalEsfUserId = _esfUserId;
		}

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	public long getOriginalEsfUserId() {
		return _originalEsfUserId;
	}

	@JSON
	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_columnBitmask |= ESFORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalEsfOrganizationId) {
			_setOriginalEsfOrganizationId = true;

			_originalEsfOrganizationId = _esfOrganizationId;
		}

		_esfOrganizationId = esfOrganizationId;
	}

	public long getOriginalEsfOrganizationId() {
		return _originalEsfOrganizationId;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public String getOldCode() {
		if (_oldCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _oldCode;
		}
	}

	@Override
	public void setOldCode(String oldCode) {
		_columnBitmask |= OLDCODE_COLUMN_BITMASK;

		if (_originalOldCode == null) {
			_originalOldCode = _oldCode;
		}

		_oldCode = oldCode;
	}

	public String getOriginalOldCode() {
		return GetterUtil.getString(_originalOldCode);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ESFCard.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ESFCard.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFCard toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFCard)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFCardImpl esfCardImpl = new ESFCardImpl();

		esfCardImpl.setUuid(getUuid());
		esfCardImpl.setEsfCardId(getEsfCardId());
		esfCardImpl.setGroupId(getGroupId());
		esfCardImpl.setCompanyId(getCompanyId());
		esfCardImpl.setUserId(getUserId());
		esfCardImpl.setUserName(getUserName());
		esfCardImpl.setCreateDate(getCreateDate());
		esfCardImpl.setModifiedDate(getModifiedDate());
		esfCardImpl.setCodeAlfa(getCodeAlfa());
		esfCardImpl.setCodeNum(getCodeNum());
		esfCardImpl.setEsfUserId(getEsfUserId());
		esfCardImpl.setEsfOrganizationId(getEsfOrganizationId());
		esfCardImpl.setCode(getCode());
		esfCardImpl.setOldCode(getOldCode());

		esfCardImpl.resetOriginalValues();

		return esfCardImpl;
	}

	@Override
	public int compareTo(ESFCard esfCard) {
		int value = 0;

		if (getCodeNum() < esfCard.getCodeNum()) {
			value = -1;
		}
		else if (getCodeNum() > esfCard.getCodeNum()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFCard)) {
			return false;
		}

		ESFCard esfCard = (ESFCard)obj;

		long primaryKey = esfCard.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFCardModelImpl esfCardModelImpl = this;

		esfCardModelImpl._originalUuid = esfCardModelImpl._uuid;

		esfCardModelImpl._originalGroupId = esfCardModelImpl._groupId;

		esfCardModelImpl._setOriginalGroupId = false;

		esfCardModelImpl._originalCompanyId = esfCardModelImpl._companyId;

		esfCardModelImpl._setOriginalCompanyId = false;

		esfCardModelImpl._originalCodeAlfa = esfCardModelImpl._codeAlfa;

		esfCardModelImpl._originalEsfUserId = esfCardModelImpl._esfUserId;

		esfCardModelImpl._setOriginalEsfUserId = false;

		esfCardModelImpl._originalEsfOrganizationId = esfCardModelImpl._esfOrganizationId;

		esfCardModelImpl._setOriginalEsfOrganizationId = false;

		esfCardModelImpl._originalCode = esfCardModelImpl._code;

		esfCardModelImpl._originalOldCode = esfCardModelImpl._oldCode;

		esfCardModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFCard> toCacheModel() {
		ESFCardCacheModel esfCardCacheModel = new ESFCardCacheModel();

		esfCardCacheModel.uuid = getUuid();

		String uuid = esfCardCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfCardCacheModel.uuid = null;
		}

		esfCardCacheModel.esfCardId = getEsfCardId();

		esfCardCacheModel.groupId = getGroupId();

		esfCardCacheModel.companyId = getCompanyId();

		esfCardCacheModel.userId = getUserId();

		esfCardCacheModel.userName = getUserName();

		String userName = esfCardCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfCardCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfCardCacheModel.createDate = createDate.getTime();
		}
		else {
			esfCardCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfCardCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfCardCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		esfCardCacheModel.codeAlfa = getCodeAlfa();

		String codeAlfa = esfCardCacheModel.codeAlfa;

		if ((codeAlfa != null) && (codeAlfa.length() == 0)) {
			esfCardCacheModel.codeAlfa = null;
		}

		esfCardCacheModel.codeNum = getCodeNum();

		esfCardCacheModel.esfUserId = getEsfUserId();

		esfCardCacheModel.esfOrganizationId = getEsfOrganizationId();

		esfCardCacheModel.code = getCode();

		String code = esfCardCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			esfCardCacheModel.code = null;
		}

		esfCardCacheModel.oldCode = getOldCode();

		String oldCode = esfCardCacheModel.oldCode;

		if ((oldCode != null) && (oldCode.length() == 0)) {
			esfCardCacheModel.oldCode = null;
		}

		return esfCardCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfCardId=");
		sb.append(getEsfCardId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", codeAlfa=");
		sb.append(getCodeAlfa());
		sb.append(", codeNum=");
		sb.append(getCodeNum());
		sb.append(", esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", oldCode=");
		sb.append(getOldCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFCard");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfCardId</column-name><column-value><![CDATA[");
		sb.append(getEsfCardId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codeAlfa</column-name><column-value><![CDATA[");
		sb.append(getCodeAlfa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codeNum</column-name><column-value><![CDATA[");
		sb.append(getCodeNum());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oldCode</column-name><column-value><![CDATA[");
		sb.append(getOldCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFCard.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFCard.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfCardId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _codeAlfa;
	private String _originalCodeAlfa;
	private long _codeNum;
	private long _esfUserId;
	private String _esfUserUuid;
	private long _originalEsfUserId;
	private boolean _setOriginalEsfUserId;
	private long _esfOrganizationId;
	private long _originalEsfOrganizationId;
	private boolean _setOriginalEsfOrganizationId;
	private String _code;
	private String _originalCode;
	private String _oldCode;
	private String _originalOldCode;
	private long _columnBitmask;
	private ESFCard _escapedModel;
}