/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.ethica.esf.model.ESFCountry;
import it.ethica.esf.model.ESFCountryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFCountry service. Represents a row in the &quot;ESFCountry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFCountryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFCountryImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFCountryImpl
 * @see it.ethica.esf.model.ESFCountry
 * @see it.ethica.esf.model.ESFCountryModel
 * @generated
 */
public class ESFCountryModelImpl extends BaseModelImpl<ESFCountry>
	implements ESFCountryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f country model instance should use the {@link it.ethica.esf.model.ESFCountry} interface instead.
	 */
	public static final String TABLE_NAME = "ESFCountry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "idCountry", Types.VARCHAR },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFCountry (idCountry VARCHAR(75) not null primary key,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ESFCountry";
	public static final String ORDER_BY_JPQL = " ORDER BY esfCountry.idCountry ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFCountry.idCountry ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFCountry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFCountry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFCountry"));

	public ESFCountryModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _idCountry;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setIdCountry(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idCountry;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ESFCountry.class;
	}

	@Override
	public String getModelClassName() {
		return ESFCountry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idCountry", getIdCountry());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String idCountry = (String)attributes.get("idCountry");

		if (idCountry != null) {
			setIdCountry(idCountry);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public String getIdCountry() {
		if (_idCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _idCountry;
		}
	}

	@Override
	public void setIdCountry(String idCountry) {
		_idCountry = idCountry;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public ESFCountry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFCountry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFCountryImpl esfCountryImpl = new ESFCountryImpl();

		esfCountryImpl.setIdCountry(getIdCountry());
		esfCountryImpl.setName(getName());

		esfCountryImpl.resetOriginalValues();

		return esfCountryImpl;
	}

	@Override
	public int compareTo(ESFCountry esfCountry) {
		String primaryKey = esfCountry.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFCountry)) {
			return false;
		}

		ESFCountry esfCountry = (ESFCountry)obj;

		String primaryKey = esfCountry.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ESFCountry> toCacheModel() {
		ESFCountryCacheModel esfCountryCacheModel = new ESFCountryCacheModel();

		esfCountryCacheModel.idCountry = getIdCountry();

		String idCountry = esfCountryCacheModel.idCountry;

		if ((idCountry != null) && (idCountry.length() == 0)) {
			esfCountryCacheModel.idCountry = null;
		}

		esfCountryCacheModel.name = getName();

		String name = esfCountryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			esfCountryCacheModel.name = null;
		}

		return esfCountryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{idCountry=");
		sb.append(getIdCountry());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFCountry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idCountry</column-name><column-value><![CDATA[");
		sb.append(getIdCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFCountry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFCountry.class
		};
	private String _idCountry;
	private String _name;
	private ESFCountry _escapedModel;
}