/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFOrganizationUnitservice;
import it.ethica.esf.model.ESFOrganizationUnitserviceModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFOrganizationUnitservice service. Represents a row in the &quot;ESFOrganizationUnitservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFOrganizationUnitserviceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFOrganizationUnitserviceImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrganizationUnitserviceImpl
 * @see it.ethica.esf.model.ESFOrganizationUnitservice
 * @see it.ethica.esf.model.ESFOrganizationUnitserviceModel
 * @generated
 */
public class ESFOrganizationUnitserviceModelImpl extends BaseModelImpl<ESFOrganizationUnitservice>
	implements ESFOrganizationUnitserviceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f organization unitservice model instance should use the {@link it.ethica.esf.model.ESFOrganizationUnitservice} interface instead.
	 */
	public static final String TABLE_NAME = "ESFOrganizationUnitservice";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfOrganizationUnitserviceId", Types.BIGINT },
			{ "esfOrganizationId", Types.BIGINT },
			{ "esfUnitserviceId", Types.BIGINT },
			{ "numberUnitservices", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFOrganizationUnitservice (uuid_ VARCHAR(75) null,esfOrganizationUnitserviceId LONG not null primary key,esfOrganizationId LONG,esfUnitserviceId LONG,numberUnitservices LONG,description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ESFOrganizationUnitservice";
	public static final String ORDER_BY_JPQL = " ORDER BY esfOrganizationUnitservice.description ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFOrganizationUnitservice.description ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFOrganizationUnitservice"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFOrganizationUnitservice"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFOrganizationUnitservice"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 2L;
	public static long ESFUNITSERVICEID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static long DESCRIPTION_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFOrganizationUnitservice"));

	public ESFOrganizationUnitserviceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfOrganizationUnitserviceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfOrganizationUnitserviceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfOrganizationUnitserviceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFOrganizationUnitservice.class;
	}

	@Override
	public String getModelClassName() {
		return ESFOrganizationUnitservice.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfOrganizationUnitserviceId",
			getEsfOrganizationUnitserviceId());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("esfUnitserviceId", getEsfUnitserviceId());
		attributes.put("numberUnitservices", getNumberUnitservices());
		attributes.put("description", getDescription());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfOrganizationUnitserviceId = (Long)attributes.get(
				"esfOrganizationUnitserviceId");

		if (esfOrganizationUnitserviceId != null) {
			setEsfOrganizationUnitserviceId(esfOrganizationUnitserviceId);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		Long esfUnitserviceId = (Long)attributes.get("esfUnitserviceId");

		if (esfUnitserviceId != null) {
			setEsfUnitserviceId(esfUnitserviceId);
		}

		Long numberUnitservices = (Long)attributes.get("numberUnitservices");

		if (numberUnitservices != null) {
			setNumberUnitservices(numberUnitservices);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEsfOrganizationUnitserviceId() {
		return _esfOrganizationUnitserviceId;
	}

	@Override
	public void setEsfOrganizationUnitserviceId(
		long esfOrganizationUnitserviceId) {
		_esfOrganizationUnitserviceId = esfOrganizationUnitserviceId;
	}

	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_columnBitmask |= ESFORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalEsfOrganizationId) {
			_setOriginalEsfOrganizationId = true;

			_originalEsfOrganizationId = _esfOrganizationId;
		}

		_esfOrganizationId = esfOrganizationId;
	}

	public long getOriginalEsfOrganizationId() {
		return _originalEsfOrganizationId;
	}

	@Override
	public long getEsfUnitserviceId() {
		return _esfUnitserviceId;
	}

	@Override
	public void setEsfUnitserviceId(long esfUnitserviceId) {
		_columnBitmask |= ESFUNITSERVICEID_COLUMN_BITMASK;

		if (!_setOriginalEsfUnitserviceId) {
			_setOriginalEsfUnitserviceId = true;

			_originalEsfUnitserviceId = _esfUnitserviceId;
		}

		_esfUnitserviceId = esfUnitserviceId;
	}

	public long getOriginalEsfUnitserviceId() {
		return _originalEsfUnitserviceId;
	}

	@Override
	public long getNumberUnitservices() {
		return _numberUnitservices;
	}

	@Override
	public void setNumberUnitservices(long numberUnitservices) {
		_numberUnitservices = numberUnitservices;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_columnBitmask = -1L;

		_description = description;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ESFOrganizationUnitservice.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ESFOrganizationUnitservice.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFOrganizationUnitservice toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFOrganizationUnitservice)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFOrganizationUnitserviceImpl esfOrganizationUnitserviceImpl = new ESFOrganizationUnitserviceImpl();

		esfOrganizationUnitserviceImpl.setUuid(getUuid());
		esfOrganizationUnitserviceImpl.setEsfOrganizationUnitserviceId(getEsfOrganizationUnitserviceId());
		esfOrganizationUnitserviceImpl.setEsfOrganizationId(getEsfOrganizationId());
		esfOrganizationUnitserviceImpl.setEsfUnitserviceId(getEsfUnitserviceId());
		esfOrganizationUnitserviceImpl.setNumberUnitservices(getNumberUnitservices());
		esfOrganizationUnitserviceImpl.setDescription(getDescription());
		esfOrganizationUnitserviceImpl.setGroupId(getGroupId());
		esfOrganizationUnitserviceImpl.setCompanyId(getCompanyId());
		esfOrganizationUnitserviceImpl.setUserId(getUserId());
		esfOrganizationUnitserviceImpl.setUserName(getUserName());
		esfOrganizationUnitserviceImpl.setCreateDate(getCreateDate());
		esfOrganizationUnitserviceImpl.setModifiedDate(getModifiedDate());

		esfOrganizationUnitserviceImpl.resetOriginalValues();

		return esfOrganizationUnitserviceImpl;
	}

	@Override
	public int compareTo(ESFOrganizationUnitservice esfOrganizationUnitservice) {
		int value = 0;

		value = getDescription()
					.compareTo(esfOrganizationUnitservice.getDescription());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFOrganizationUnitservice)) {
			return false;
		}

		ESFOrganizationUnitservice esfOrganizationUnitservice = (ESFOrganizationUnitservice)obj;

		long primaryKey = esfOrganizationUnitservice.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFOrganizationUnitserviceModelImpl esfOrganizationUnitserviceModelImpl = this;

		esfOrganizationUnitserviceModelImpl._originalUuid = esfOrganizationUnitserviceModelImpl._uuid;

		esfOrganizationUnitserviceModelImpl._originalEsfOrganizationId = esfOrganizationUnitserviceModelImpl._esfOrganizationId;

		esfOrganizationUnitserviceModelImpl._setOriginalEsfOrganizationId = false;

		esfOrganizationUnitserviceModelImpl._originalEsfUnitserviceId = esfOrganizationUnitserviceModelImpl._esfUnitserviceId;

		esfOrganizationUnitserviceModelImpl._setOriginalEsfUnitserviceId = false;

		esfOrganizationUnitserviceModelImpl._originalGroupId = esfOrganizationUnitserviceModelImpl._groupId;

		esfOrganizationUnitserviceModelImpl._setOriginalGroupId = false;

		esfOrganizationUnitserviceModelImpl._originalCompanyId = esfOrganizationUnitserviceModelImpl._companyId;

		esfOrganizationUnitserviceModelImpl._setOriginalCompanyId = false;

		esfOrganizationUnitserviceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFOrganizationUnitservice> toCacheModel() {
		ESFOrganizationUnitserviceCacheModel esfOrganizationUnitserviceCacheModel =
			new ESFOrganizationUnitserviceCacheModel();

		esfOrganizationUnitserviceCacheModel.uuid = getUuid();

		String uuid = esfOrganizationUnitserviceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfOrganizationUnitserviceCacheModel.uuid = null;
		}

		esfOrganizationUnitserviceCacheModel.esfOrganizationUnitserviceId = getEsfOrganizationUnitserviceId();

		esfOrganizationUnitserviceCacheModel.esfOrganizationId = getEsfOrganizationId();

		esfOrganizationUnitserviceCacheModel.esfUnitserviceId = getEsfUnitserviceId();

		esfOrganizationUnitserviceCacheModel.numberUnitservices = getNumberUnitservices();

		esfOrganizationUnitserviceCacheModel.description = getDescription();

		String description = esfOrganizationUnitserviceCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			esfOrganizationUnitserviceCacheModel.description = null;
		}

		esfOrganizationUnitserviceCacheModel.groupId = getGroupId();

		esfOrganizationUnitserviceCacheModel.companyId = getCompanyId();

		esfOrganizationUnitserviceCacheModel.userId = getUserId();

		esfOrganizationUnitserviceCacheModel.userName = getUserName();

		String userName = esfOrganizationUnitserviceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfOrganizationUnitserviceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfOrganizationUnitserviceCacheModel.createDate = createDate.getTime();
		}
		else {
			esfOrganizationUnitserviceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfOrganizationUnitserviceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfOrganizationUnitserviceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return esfOrganizationUnitserviceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfOrganizationUnitserviceId=");
		sb.append(getEsfOrganizationUnitserviceId());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", esfUnitserviceId=");
		sb.append(getEsfUnitserviceId());
		sb.append(", numberUnitservices=");
		sb.append(getNumberUnitservices());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFOrganizationUnitservice");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationUnitserviceId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationUnitserviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUnitserviceId</column-name><column-value><![CDATA[");
		sb.append(getEsfUnitserviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberUnitservices</column-name><column-value><![CDATA[");
		sb.append(getNumberUnitservices());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFOrganizationUnitservice.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFOrganizationUnitservice.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfOrganizationUnitserviceId;
	private long _esfOrganizationId;
	private long _originalEsfOrganizationId;
	private boolean _setOriginalEsfOrganizationId;
	private long _esfUnitserviceId;
	private long _originalEsfUnitserviceId;
	private boolean _setOriginalEsfUnitserviceId;
	private long _numberUnitservices;
	private String _description;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private ESFOrganizationUnitservice _escapedModel;
}