/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFRadunoTipo;
import it.ethica.esf.model.ESFRadunoTipoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFRadunoTipo service. Represents a row in the &quot;ESFRadunoTipo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFRadunoTipoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFRadunoTipoImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFRadunoTipoImpl
 * @see it.ethica.esf.model.ESFRadunoTipo
 * @see it.ethica.esf.model.ESFRadunoTipoModel
 * @generated
 */
public class ESFRadunoTipoModelImpl extends BaseModelImpl<ESFRadunoTipo>
	implements ESFRadunoTipoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f raduno tipo model instance should use the {@link it.ethica.esf.model.ESFRadunoTipo} interface instead.
	 */
	public static final String TABLE_NAME = "ESFRadunoTipo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_esf_raduno_tipo", Types.BIGINT },
			{ "descrizione", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFRadunoTipo (id_esf_raduno_tipo LONG not null primary key IDENTITY,descrizione VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ESFRadunoTipo";
	public static final String ORDER_BY_JPQL = " ORDER BY esfRadunoTipo.id_esf_raduno_tipo ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFRadunoTipo.id_esf_raduno_tipo ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFRadunoTipo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFRadunoTipo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFRadunoTipo"));

	public ESFRadunoTipoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_esf_raduno_tipo;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_esf_raduno_tipo(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_esf_raduno_tipo;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFRadunoTipo.class;
	}

	@Override
	public String getModelClassName() {
		return ESFRadunoTipo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_esf_raduno_tipo", getId_esf_raduno_tipo());
		attributes.put("descrizione", getDescrizione());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_esf_raduno_tipo = (Long)attributes.get("id_esf_raduno_tipo");

		if (id_esf_raduno_tipo != null) {
			setId_esf_raduno_tipo(id_esf_raduno_tipo);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}
	}

	@Override
	public long getId_esf_raduno_tipo() {
		return _id_esf_raduno_tipo;
	}

	@Override
	public void setId_esf_raduno_tipo(long id_esf_raduno_tipo) {
		_id_esf_raduno_tipo = id_esf_raduno_tipo;
	}

	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ESFRadunoTipo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFRadunoTipo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFRadunoTipo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFRadunoTipoImpl esfRadunoTipoImpl = new ESFRadunoTipoImpl();

		esfRadunoTipoImpl.setId_esf_raduno_tipo(getId_esf_raduno_tipo());
		esfRadunoTipoImpl.setDescrizione(getDescrizione());

		esfRadunoTipoImpl.resetOriginalValues();

		return esfRadunoTipoImpl;
	}

	@Override
	public int compareTo(ESFRadunoTipo esfRadunoTipo) {
		long primaryKey = esfRadunoTipo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFRadunoTipo)) {
			return false;
		}

		ESFRadunoTipo esfRadunoTipo = (ESFRadunoTipo)obj;

		long primaryKey = esfRadunoTipo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ESFRadunoTipo> toCacheModel() {
		ESFRadunoTipoCacheModel esfRadunoTipoCacheModel = new ESFRadunoTipoCacheModel();

		esfRadunoTipoCacheModel.id_esf_raduno_tipo = getId_esf_raduno_tipo();

		esfRadunoTipoCacheModel.descrizione = getDescrizione();

		String descrizione = esfRadunoTipoCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			esfRadunoTipoCacheModel.descrizione = null;
		}

		return esfRadunoTipoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_esf_raduno_tipo=");
		sb.append(getId_esf_raduno_tipo());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFRadunoTipo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_esf_raduno_tipo</column-name><column-value><![CDATA[");
		sb.append(getId_esf_raduno_tipo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFRadunoTipo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFRadunoTipo.class
		};
	private long _id_esf_raduno_tipo;
	private String _descrizione;
	private ESFRadunoTipo _escapedModel;
}