/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFSuspensiveShootingDirector;
import it.ethica.esf.model.ESFSuspensiveShootingDirectorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFSuspensiveShootingDirector service. Represents a row in the &quot;ESFSuspensiveShootingDirector&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFSuspensiveShootingDirectorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFSuspensiveShootingDirectorImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFSuspensiveShootingDirectorImpl
 * @see it.ethica.esf.model.ESFSuspensiveShootingDirector
 * @see it.ethica.esf.model.ESFSuspensiveShootingDirectorModel
 * @generated
 */
public class ESFSuspensiveShootingDirectorModelImpl extends BaseModelImpl<ESFSuspensiveShootingDirector>
	implements ESFSuspensiveShootingDirectorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f suspensive shooting director model instance should use the {@link it.ethica.esf.model.ESFSuspensiveShootingDirector} interface instead.
	 */
	public static final String TABLE_NAME = "ESFSuspensiveShootingDirector";
	public static final Object[][] TABLE_COLUMNS = {
			{ "esfSuspensiveShooingDirectorId", Types.BIGINT },
			{ "esfData", Types.TIMESTAMP },
			{ "esfCodeData", Types.VARCHAR },
			{ "esfStartData", Types.TIMESTAMP },
			{ "esfEndData", Types.TIMESTAMP },
			{ "esfUserId", Types.BIGINT },
			{ "codeUser", Types.BIGINT },
			{ "Codice_Sosp", Types.BIGINT },
			{ "note", Types.VARCHAR },
			{ "Qualif1_Utiliz", Types.BIGINT },
			{ "Qualif2_Utiliz", Types.BIGINT },
			{ "Qualif3_Utiliz", Types.BIGINT },
			{ "Tipo_Gara1_noUtil", Types.BIGINT },
			{ "Tipo_Gara2_noUtil", Types.BIGINT },
			{ "Tipo_Gara3_noUtil", Types.BIGINT },
			{ "Tipo_Gara4_noUtil", Types.BIGINT },
			{ "Tipo_Gara5_noUtil", Types.BIGINT },
			{ "Tipo_Gara6_noUtil", Types.BIGINT },
			{ "Tipo_Gara7_noUtil", Types.BIGINT },
			{ "Tipo_Gara8_noUtil", Types.BIGINT },
			{ "Tipo_Gara9_noUtil", Types.BIGINT },
			{ "Tipo_Gara10_noUtil", Types.BIGINT },
			{ "esfVariationData", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFSuspensiveShootingDirector (esfSuspensiveShooingDirectorId LONG not null primary key,esfData DATE null,esfCodeData VARCHAR(75) null,esfStartData DATE null,esfEndData DATE null,esfUserId LONG,codeUser LONG,Codice_Sosp LONG,note VARCHAR(75) null,Qualif1_Utiliz LONG,Qualif2_Utiliz LONG,Qualif3_Utiliz LONG,Tipo_Gara1_noUtil LONG,Tipo_Gara2_noUtil LONG,Tipo_Gara3_noUtil LONG,Tipo_Gara4_noUtil LONG,Tipo_Gara5_noUtil LONG,Tipo_Gara6_noUtil LONG,Tipo_Gara7_noUtil LONG,Tipo_Gara8_noUtil LONG,Tipo_Gara9_noUtil LONG,Tipo_Gara10_noUtil LONG,esfVariationData DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ESFSuspensiveShootingDirector";
	public static final String ORDER_BY_JPQL = " ORDER BY esfSuspensiveShootingDirector.esfSuspensiveShooingDirectorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFSuspensiveShootingDirector.esfSuspensiveShooingDirectorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFSuspensiveShootingDirector"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFSuspensiveShootingDirector"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFSuspensiveShootingDirector"),
			true);
	public static long ESFENDDATA_COLUMN_BITMASK = 1L;
	public static long ESFUSERID_COLUMN_BITMASK = 2L;
	public static long ESFSUSPENSIVESHOOINGDIRECTORID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFSuspensiveShootingDirector"));

	public ESFSuspensiveShootingDirectorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfSuspensiveShooingDirectorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfSuspensiveShooingDirectorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfSuspensiveShooingDirectorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFSuspensiveShootingDirector.class;
	}

	@Override
	public String getModelClassName() {
		return ESFSuspensiveShootingDirector.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("esfSuspensiveShooingDirectorId",
			getEsfSuspensiveShooingDirectorId());
		attributes.put("esfData", getEsfData());
		attributes.put("esfCodeData", getEsfCodeData());
		attributes.put("esfStartData", getEsfStartData());
		attributes.put("esfEndData", getEsfEndData());
		attributes.put("esfUserId", getEsfUserId());
		attributes.put("codeUser", getCodeUser());
		attributes.put("Codice_Sosp", getCodice_Sosp());
		attributes.put("note", getNote());
		attributes.put("Qualif1_Utiliz", getQualif1_Utiliz());
		attributes.put("Qualif2_Utiliz", getQualif2_Utiliz());
		attributes.put("Qualif3_Utiliz", getQualif3_Utiliz());
		attributes.put("Tipo_Gara1_noUtil", getTipo_Gara1_noUtil());
		attributes.put("Tipo_Gara2_noUtil", getTipo_Gara2_noUtil());
		attributes.put("Tipo_Gara3_noUtil", getTipo_Gara3_noUtil());
		attributes.put("Tipo_Gara4_noUtil", getTipo_Gara4_noUtil());
		attributes.put("Tipo_Gara5_noUtil", getTipo_Gara5_noUtil());
		attributes.put("Tipo_Gara6_noUtil", getTipo_Gara6_noUtil());
		attributes.put("Tipo_Gara7_noUtil", getTipo_Gara7_noUtil());
		attributes.put("Tipo_Gara8_noUtil", getTipo_Gara8_noUtil());
		attributes.put("Tipo_Gara9_noUtil", getTipo_Gara9_noUtil());
		attributes.put("Tipo_Gara10_noUtil", getTipo_Gara10_noUtil());
		attributes.put("esfVariationData", getEsfVariationData());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long esfSuspensiveShooingDirectorId = (Long)attributes.get(
				"esfSuspensiveShooingDirectorId");

		if (esfSuspensiveShooingDirectorId != null) {
			setEsfSuspensiveShooingDirectorId(esfSuspensiveShooingDirectorId);
		}

		Date esfData = (Date)attributes.get("esfData");

		if (esfData != null) {
			setEsfData(esfData);
		}

		String esfCodeData = (String)attributes.get("esfCodeData");

		if (esfCodeData != null) {
			setEsfCodeData(esfCodeData);
		}

		Date esfStartData = (Date)attributes.get("esfStartData");

		if (esfStartData != null) {
			setEsfStartData(esfStartData);
		}

		Date esfEndData = (Date)attributes.get("esfEndData");

		if (esfEndData != null) {
			setEsfEndData(esfEndData);
		}

		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		Long codeUser = (Long)attributes.get("codeUser");

		if (codeUser != null) {
			setCodeUser(codeUser);
		}

		Long Codice_Sosp = (Long)attributes.get("Codice_Sosp");

		if (Codice_Sosp != null) {
			setCodice_Sosp(Codice_Sosp);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}

		Long Qualif1_Utiliz = (Long)attributes.get("Qualif1_Utiliz");

		if (Qualif1_Utiliz != null) {
			setQualif1_Utiliz(Qualif1_Utiliz);
		}

		Long Qualif2_Utiliz = (Long)attributes.get("Qualif2_Utiliz");

		if (Qualif2_Utiliz != null) {
			setQualif2_Utiliz(Qualif2_Utiliz);
		}

		Long Qualif3_Utiliz = (Long)attributes.get("Qualif3_Utiliz");

		if (Qualif3_Utiliz != null) {
			setQualif3_Utiliz(Qualif3_Utiliz);
		}

		Long Tipo_Gara1_noUtil = (Long)attributes.get("Tipo_Gara1_noUtil");

		if (Tipo_Gara1_noUtil != null) {
			setTipo_Gara1_noUtil(Tipo_Gara1_noUtil);
		}

		Long Tipo_Gara2_noUtil = (Long)attributes.get("Tipo_Gara2_noUtil");

		if (Tipo_Gara2_noUtil != null) {
			setTipo_Gara2_noUtil(Tipo_Gara2_noUtil);
		}

		Long Tipo_Gara3_noUtil = (Long)attributes.get("Tipo_Gara3_noUtil");

		if (Tipo_Gara3_noUtil != null) {
			setTipo_Gara3_noUtil(Tipo_Gara3_noUtil);
		}

		Long Tipo_Gara4_noUtil = (Long)attributes.get("Tipo_Gara4_noUtil");

		if (Tipo_Gara4_noUtil != null) {
			setTipo_Gara4_noUtil(Tipo_Gara4_noUtil);
		}

		Long Tipo_Gara5_noUtil = (Long)attributes.get("Tipo_Gara5_noUtil");

		if (Tipo_Gara5_noUtil != null) {
			setTipo_Gara5_noUtil(Tipo_Gara5_noUtil);
		}

		Long Tipo_Gara6_noUtil = (Long)attributes.get("Tipo_Gara6_noUtil");

		if (Tipo_Gara6_noUtil != null) {
			setTipo_Gara6_noUtil(Tipo_Gara6_noUtil);
		}

		Long Tipo_Gara7_noUtil = (Long)attributes.get("Tipo_Gara7_noUtil");

		if (Tipo_Gara7_noUtil != null) {
			setTipo_Gara7_noUtil(Tipo_Gara7_noUtil);
		}

		Long Tipo_Gara8_noUtil = (Long)attributes.get("Tipo_Gara8_noUtil");

		if (Tipo_Gara8_noUtil != null) {
			setTipo_Gara8_noUtil(Tipo_Gara8_noUtil);
		}

		Long Tipo_Gara9_noUtil = (Long)attributes.get("Tipo_Gara9_noUtil");

		if (Tipo_Gara9_noUtil != null) {
			setTipo_Gara9_noUtil(Tipo_Gara9_noUtil);
		}

		Long Tipo_Gara10_noUtil = (Long)attributes.get("Tipo_Gara10_noUtil");

		if (Tipo_Gara10_noUtil != null) {
			setTipo_Gara10_noUtil(Tipo_Gara10_noUtil);
		}

		Date esfVariationData = (Date)attributes.get("esfVariationData");

		if (esfVariationData != null) {
			setEsfVariationData(esfVariationData);
		}
	}

	@Override
	public long getEsfSuspensiveShooingDirectorId() {
		return _esfSuspensiveShooingDirectorId;
	}

	@Override
	public void setEsfSuspensiveShooingDirectorId(
		long esfSuspensiveShooingDirectorId) {
		_columnBitmask = -1L;

		_esfSuspensiveShooingDirectorId = esfSuspensiveShooingDirectorId;
	}

	@Override
	public Date getEsfData() {
		return _esfData;
	}

	@Override
	public void setEsfData(Date esfData) {
		_esfData = esfData;
	}

	@Override
	public String getEsfCodeData() {
		if (_esfCodeData == null) {
			return StringPool.BLANK;
		}
		else {
			return _esfCodeData;
		}
	}

	@Override
	public void setEsfCodeData(String esfCodeData) {
		_esfCodeData = esfCodeData;
	}

	@Override
	public Date getEsfStartData() {
		return _esfStartData;
	}

	@Override
	public void setEsfStartData(Date esfStartData) {
		_esfStartData = esfStartData;
	}

	@Override
	public Date getEsfEndData() {
		return _esfEndData;
	}

	@Override
	public void setEsfEndData(Date esfEndData) {
		_columnBitmask |= ESFENDDATA_COLUMN_BITMASK;

		if (_originalEsfEndData == null) {
			_originalEsfEndData = _esfEndData;
		}

		_esfEndData = esfEndData;
	}

	public Date getOriginalEsfEndData() {
		return _originalEsfEndData;
	}

	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask |= ESFUSERID_COLUMN_BITMASK;

		if (!_setOriginalEsfUserId) {
			_setOriginalEsfUserId = true;

			_originalEsfUserId = _esfUserId;
		}

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	public long getOriginalEsfUserId() {
		return _originalEsfUserId;
	}

	@Override
	public long getCodeUser() {
		return _codeUser;
	}

	@Override
	public void setCodeUser(long codeUser) {
		_codeUser = codeUser;
	}

	@Override
	public long getCodice_Sosp() {
		return _Codice_Sosp;
	}

	@Override
	public void setCodice_Sosp(long Codice_Sosp) {
		_Codice_Sosp = Codice_Sosp;
	}

	@Override
	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	@Override
	public long getQualif1_Utiliz() {
		return _Qualif1_Utiliz;
	}

	@Override
	public void setQualif1_Utiliz(long Qualif1_Utiliz) {
		_Qualif1_Utiliz = Qualif1_Utiliz;
	}

	@Override
	public long getQualif2_Utiliz() {
		return _Qualif2_Utiliz;
	}

	@Override
	public void setQualif2_Utiliz(long Qualif2_Utiliz) {
		_Qualif2_Utiliz = Qualif2_Utiliz;
	}

	@Override
	public long getQualif3_Utiliz() {
		return _Qualif3_Utiliz;
	}

	@Override
	public void setQualif3_Utiliz(long Qualif3_Utiliz) {
		_Qualif3_Utiliz = Qualif3_Utiliz;
	}

	@Override
	public long getTipo_Gara1_noUtil() {
		return _Tipo_Gara1_noUtil;
	}

	@Override
	public void setTipo_Gara1_noUtil(long Tipo_Gara1_noUtil) {
		_Tipo_Gara1_noUtil = Tipo_Gara1_noUtil;
	}

	@Override
	public long getTipo_Gara2_noUtil() {
		return _Tipo_Gara2_noUtil;
	}

	@Override
	public void setTipo_Gara2_noUtil(long Tipo_Gara2_noUtil) {
		_Tipo_Gara2_noUtil = Tipo_Gara2_noUtil;
	}

	@Override
	public long getTipo_Gara3_noUtil() {
		return _Tipo_Gara3_noUtil;
	}

	@Override
	public void setTipo_Gara3_noUtil(long Tipo_Gara3_noUtil) {
		_Tipo_Gara3_noUtil = Tipo_Gara3_noUtil;
	}

	@Override
	public long getTipo_Gara4_noUtil() {
		return _Tipo_Gara4_noUtil;
	}

	@Override
	public void setTipo_Gara4_noUtil(long Tipo_Gara4_noUtil) {
		_Tipo_Gara4_noUtil = Tipo_Gara4_noUtil;
	}

	@Override
	public long getTipo_Gara5_noUtil() {
		return _Tipo_Gara5_noUtil;
	}

	@Override
	public void setTipo_Gara5_noUtil(long Tipo_Gara5_noUtil) {
		_Tipo_Gara5_noUtil = Tipo_Gara5_noUtil;
	}

	@Override
	public long getTipo_Gara6_noUtil() {
		return _Tipo_Gara6_noUtil;
	}

	@Override
	public void setTipo_Gara6_noUtil(long Tipo_Gara6_noUtil) {
		_Tipo_Gara6_noUtil = Tipo_Gara6_noUtil;
	}

	@Override
	public long getTipo_Gara7_noUtil() {
		return _Tipo_Gara7_noUtil;
	}

	@Override
	public void setTipo_Gara7_noUtil(long Tipo_Gara7_noUtil) {
		_Tipo_Gara7_noUtil = Tipo_Gara7_noUtil;
	}

	@Override
	public long getTipo_Gara8_noUtil() {
		return _Tipo_Gara8_noUtil;
	}

	@Override
	public void setTipo_Gara8_noUtil(long Tipo_Gara8_noUtil) {
		_Tipo_Gara8_noUtil = Tipo_Gara8_noUtil;
	}

	@Override
	public long getTipo_Gara9_noUtil() {
		return _Tipo_Gara9_noUtil;
	}

	@Override
	public void setTipo_Gara9_noUtil(long Tipo_Gara9_noUtil) {
		_Tipo_Gara9_noUtil = Tipo_Gara9_noUtil;
	}

	@Override
	public long getTipo_Gara10_noUtil() {
		return _Tipo_Gara10_noUtil;
	}

	@Override
	public void setTipo_Gara10_noUtil(long Tipo_Gara10_noUtil) {
		_Tipo_Gara10_noUtil = Tipo_Gara10_noUtil;
	}

	@Override
	public Date getEsfVariationData() {
		return _esfVariationData;
	}

	@Override
	public void setEsfVariationData(Date esfVariationData) {
		_esfVariationData = esfVariationData;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ESFSuspensiveShootingDirector.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFSuspensiveShootingDirector toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFSuspensiveShootingDirector)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFSuspensiveShootingDirectorImpl esfSuspensiveShootingDirectorImpl = new ESFSuspensiveShootingDirectorImpl();

		esfSuspensiveShootingDirectorImpl.setEsfSuspensiveShooingDirectorId(getEsfSuspensiveShooingDirectorId());
		esfSuspensiveShootingDirectorImpl.setEsfData(getEsfData());
		esfSuspensiveShootingDirectorImpl.setEsfCodeData(getEsfCodeData());
		esfSuspensiveShootingDirectorImpl.setEsfStartData(getEsfStartData());
		esfSuspensiveShootingDirectorImpl.setEsfEndData(getEsfEndData());
		esfSuspensiveShootingDirectorImpl.setEsfUserId(getEsfUserId());
		esfSuspensiveShootingDirectorImpl.setCodeUser(getCodeUser());
		esfSuspensiveShootingDirectorImpl.setCodice_Sosp(getCodice_Sosp());
		esfSuspensiveShootingDirectorImpl.setNote(getNote());
		esfSuspensiveShootingDirectorImpl.setQualif1_Utiliz(getQualif1_Utiliz());
		esfSuspensiveShootingDirectorImpl.setQualif2_Utiliz(getQualif2_Utiliz());
		esfSuspensiveShootingDirectorImpl.setQualif3_Utiliz(getQualif3_Utiliz());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara1_noUtil(getTipo_Gara1_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara2_noUtil(getTipo_Gara2_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara3_noUtil(getTipo_Gara3_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara4_noUtil(getTipo_Gara4_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara5_noUtil(getTipo_Gara5_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara6_noUtil(getTipo_Gara6_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara7_noUtil(getTipo_Gara7_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara8_noUtil(getTipo_Gara8_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara9_noUtil(getTipo_Gara9_noUtil());
		esfSuspensiveShootingDirectorImpl.setTipo_Gara10_noUtil(getTipo_Gara10_noUtil());
		esfSuspensiveShootingDirectorImpl.setEsfVariationData(getEsfVariationData());

		esfSuspensiveShootingDirectorImpl.resetOriginalValues();

		return esfSuspensiveShootingDirectorImpl;
	}

	@Override
	public int compareTo(
		ESFSuspensiveShootingDirector esfSuspensiveShootingDirector) {
		int value = 0;

		if (getEsfSuspensiveShooingDirectorId() < esfSuspensiveShootingDirector.getEsfSuspensiveShooingDirectorId()) {
			value = -1;
		}
		else if (getEsfSuspensiveShooingDirectorId() > esfSuspensiveShootingDirector.getEsfSuspensiveShooingDirectorId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFSuspensiveShootingDirector)) {
			return false;
		}

		ESFSuspensiveShootingDirector esfSuspensiveShootingDirector = (ESFSuspensiveShootingDirector)obj;

		long primaryKey = esfSuspensiveShootingDirector.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFSuspensiveShootingDirectorModelImpl esfSuspensiveShootingDirectorModelImpl =
			this;

		esfSuspensiveShootingDirectorModelImpl._originalEsfEndData = esfSuspensiveShootingDirectorModelImpl._esfEndData;

		esfSuspensiveShootingDirectorModelImpl._originalEsfUserId = esfSuspensiveShootingDirectorModelImpl._esfUserId;

		esfSuspensiveShootingDirectorModelImpl._setOriginalEsfUserId = false;

		esfSuspensiveShootingDirectorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFSuspensiveShootingDirector> toCacheModel() {
		ESFSuspensiveShootingDirectorCacheModel esfSuspensiveShootingDirectorCacheModel =
			new ESFSuspensiveShootingDirectorCacheModel();

		esfSuspensiveShootingDirectorCacheModel.esfSuspensiveShooingDirectorId = getEsfSuspensiveShooingDirectorId();

		Date esfData = getEsfData();

		if (esfData != null) {
			esfSuspensiveShootingDirectorCacheModel.esfData = esfData.getTime();
		}
		else {
			esfSuspensiveShootingDirectorCacheModel.esfData = Long.MIN_VALUE;
		}

		esfSuspensiveShootingDirectorCacheModel.esfCodeData = getEsfCodeData();

		String esfCodeData = esfSuspensiveShootingDirectorCacheModel.esfCodeData;

		if ((esfCodeData != null) && (esfCodeData.length() == 0)) {
			esfSuspensiveShootingDirectorCacheModel.esfCodeData = null;
		}

		Date esfStartData = getEsfStartData();

		if (esfStartData != null) {
			esfSuspensiveShootingDirectorCacheModel.esfStartData = esfStartData.getTime();
		}
		else {
			esfSuspensiveShootingDirectorCacheModel.esfStartData = Long.MIN_VALUE;
		}

		Date esfEndData = getEsfEndData();

		if (esfEndData != null) {
			esfSuspensiveShootingDirectorCacheModel.esfEndData = esfEndData.getTime();
		}
		else {
			esfSuspensiveShootingDirectorCacheModel.esfEndData = Long.MIN_VALUE;
		}

		esfSuspensiveShootingDirectorCacheModel.esfUserId = getEsfUserId();

		esfSuspensiveShootingDirectorCacheModel.codeUser = getCodeUser();

		esfSuspensiveShootingDirectorCacheModel.Codice_Sosp = getCodice_Sosp();

		esfSuspensiveShootingDirectorCacheModel.note = getNote();

		String note = esfSuspensiveShootingDirectorCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			esfSuspensiveShootingDirectorCacheModel.note = null;
		}

		esfSuspensiveShootingDirectorCacheModel.Qualif1_Utiliz = getQualif1_Utiliz();

		esfSuspensiveShootingDirectorCacheModel.Qualif2_Utiliz = getQualif2_Utiliz();

		esfSuspensiveShootingDirectorCacheModel.Qualif3_Utiliz = getQualif3_Utiliz();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara1_noUtil = getTipo_Gara1_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara2_noUtil = getTipo_Gara2_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara3_noUtil = getTipo_Gara3_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara4_noUtil = getTipo_Gara4_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara5_noUtil = getTipo_Gara5_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara6_noUtil = getTipo_Gara6_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara7_noUtil = getTipo_Gara7_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara8_noUtil = getTipo_Gara8_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara9_noUtil = getTipo_Gara9_noUtil();

		esfSuspensiveShootingDirectorCacheModel.Tipo_Gara10_noUtil = getTipo_Gara10_noUtil();

		Date esfVariationData = getEsfVariationData();

		if (esfVariationData != null) {
			esfSuspensiveShootingDirectorCacheModel.esfVariationData = esfVariationData.getTime();
		}
		else {
			esfSuspensiveShootingDirectorCacheModel.esfVariationData = Long.MIN_VALUE;
		}

		return esfSuspensiveShootingDirectorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(47);

		sb.append("{esfSuspensiveShooingDirectorId=");
		sb.append(getEsfSuspensiveShooingDirectorId());
		sb.append(", esfData=");
		sb.append(getEsfData());
		sb.append(", esfCodeData=");
		sb.append(getEsfCodeData());
		sb.append(", esfStartData=");
		sb.append(getEsfStartData());
		sb.append(", esfEndData=");
		sb.append(getEsfEndData());
		sb.append(", esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", codeUser=");
		sb.append(getCodeUser());
		sb.append(", Codice_Sosp=");
		sb.append(getCodice_Sosp());
		sb.append(", note=");
		sb.append(getNote());
		sb.append(", Qualif1_Utiliz=");
		sb.append(getQualif1_Utiliz());
		sb.append(", Qualif2_Utiliz=");
		sb.append(getQualif2_Utiliz());
		sb.append(", Qualif3_Utiliz=");
		sb.append(getQualif3_Utiliz());
		sb.append(", Tipo_Gara1_noUtil=");
		sb.append(getTipo_Gara1_noUtil());
		sb.append(", Tipo_Gara2_noUtil=");
		sb.append(getTipo_Gara2_noUtil());
		sb.append(", Tipo_Gara3_noUtil=");
		sb.append(getTipo_Gara3_noUtil());
		sb.append(", Tipo_Gara4_noUtil=");
		sb.append(getTipo_Gara4_noUtil());
		sb.append(", Tipo_Gara5_noUtil=");
		sb.append(getTipo_Gara5_noUtil());
		sb.append(", Tipo_Gara6_noUtil=");
		sb.append(getTipo_Gara6_noUtil());
		sb.append(", Tipo_Gara7_noUtil=");
		sb.append(getTipo_Gara7_noUtil());
		sb.append(", Tipo_Gara8_noUtil=");
		sb.append(getTipo_Gara8_noUtil());
		sb.append(", Tipo_Gara9_noUtil=");
		sb.append(getTipo_Gara9_noUtil());
		sb.append(", Tipo_Gara10_noUtil=");
		sb.append(getTipo_Gara10_noUtil());
		sb.append(", esfVariationData=");
		sb.append(getEsfVariationData());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(73);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFSuspensiveShootingDirector");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>esfSuspensiveShooingDirectorId</column-name><column-value><![CDATA[");
		sb.append(getEsfSuspensiveShooingDirectorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfData</column-name><column-value><![CDATA[");
		sb.append(getEsfData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfCodeData</column-name><column-value><![CDATA[");
		sb.append(getEsfCodeData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfStartData</column-name><column-value><![CDATA[");
		sb.append(getEsfStartData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfEndData</column-name><column-value><![CDATA[");
		sb.append(getEsfEndData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codeUser</column-name><column-value><![CDATA[");
		sb.append(getCodeUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Codice_Sosp</column-name><column-value><![CDATA[");
		sb.append(getCodice_Sosp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Qualif1_Utiliz</column-name><column-value><![CDATA[");
		sb.append(getQualif1_Utiliz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Qualif2_Utiliz</column-name><column-value><![CDATA[");
		sb.append(getQualif2_Utiliz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Qualif3_Utiliz</column-name><column-value><![CDATA[");
		sb.append(getQualif3_Utiliz());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara1_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara1_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara2_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara2_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara3_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara3_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara4_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara4_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara5_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara5_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara6_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara6_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara7_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara7_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara8_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara8_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara9_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara9_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Tipo_Gara10_noUtil</column-name><column-value><![CDATA[");
		sb.append(getTipo_Gara10_noUtil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfVariationData</column-name><column-value><![CDATA[");
		sb.append(getEsfVariationData());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFSuspensiveShootingDirector.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFSuspensiveShootingDirector.class
		};
	private long _esfSuspensiveShooingDirectorId;
	private Date _esfData;
	private String _esfCodeData;
	private Date _esfStartData;
	private Date _esfEndData;
	private Date _originalEsfEndData;
	private long _esfUserId;
	private String _esfUserUuid;
	private long _originalEsfUserId;
	private boolean _setOriginalEsfUserId;
	private long _codeUser;
	private long _Codice_Sosp;
	private String _note;
	private long _Qualif1_Utiliz;
	private long _Qualif2_Utiliz;
	private long _Qualif3_Utiliz;
	private long _Tipo_Gara1_noUtil;
	private long _Tipo_Gara2_noUtil;
	private long _Tipo_Gara3_noUtil;
	private long _Tipo_Gara4_noUtil;
	private long _Tipo_Gara5_noUtil;
	private long _Tipo_Gara6_noUtil;
	private long _Tipo_Gara7_noUtil;
	private long _Tipo_Gara8_noUtil;
	private long _Tipo_Gara9_noUtil;
	private long _Tipo_Gara10_noUtil;
	private Date _esfVariationData;
	private long _columnBitmask;
	private ESFSuspensiveShootingDirector _escapedModel;
}