/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFShooterQualification;
import it.ethica.esf.model.ESFShooterQualificationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFShooterQualification service. Represents a row in the &quot;ESFShooterQualification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFShooterQualificationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFShooterQualificationImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFShooterQualificationImpl
 * @see it.ethica.esf.model.ESFShooterQualification
 * @see it.ethica.esf.model.ESFShooterQualificationModel
 * @generated
 */
public class ESFShooterQualificationModelImpl extends BaseModelImpl<ESFShooterQualification>
	implements ESFShooterQualificationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f shooter qualification model instance should use the {@link it.ethica.esf.model.ESFShooterQualification} interface instead.
	 */
	public static final String TABLE_NAME = "ESFShooterQualification";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfShooterQualificationId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "isJunior", Types.BOOLEAN },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "description", Types.VARCHAR },
			{ "code_", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFShooterQualification (uuid_ VARCHAR(75) null,esfShooterQualificationId LONG not null primary key,name VARCHAR(75) null,isJunior BOOLEAN,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,description VARCHAR(75) null,code_ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ESFShooterQualification";
	public static final String ORDER_BY_JPQL = " ORDER BY esfShooterQualification.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFShooterQualification.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFShooterQualification"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFShooterQualification"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFShooterQualification"),
			true);
	public static long CODE_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long NAME_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFShooterQualification"));

	public ESFShooterQualificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfShooterQualificationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfShooterQualificationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfShooterQualificationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFShooterQualification.class;
	}

	@Override
	public String getModelClassName() {
		return ESFShooterQualification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfShooterQualificationId",
			getEsfShooterQualificationId());
		attributes.put("name", getName());
		attributes.put("isJunior", getIsJunior());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("description", getDescription());
		attributes.put("code", getCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfShooterQualificationId = (Long)attributes.get(
				"esfShooterQualificationId");

		if (esfShooterQualificationId != null) {
			setEsfShooterQualificationId(esfShooterQualificationId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Boolean isJunior = (Boolean)attributes.get("isJunior");

		if (isJunior != null) {
			setIsJunior(isJunior);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEsfShooterQualificationId() {
		return _esfShooterQualificationId;
	}

	@Override
	public void setEsfShooterQualificationId(long esfShooterQualificationId) {
		_esfShooterQualificationId = esfShooterQualificationId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public boolean getIsJunior() {
		return _isJunior;
	}

	@Override
	public boolean isIsJunior() {
		return _isJunior;
	}

	@Override
	public void setIsJunior(boolean isJunior) {
		_isJunior = isJunior;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ESFShooterQualification.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ESFShooterQualification.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFShooterQualification toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFShooterQualification)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFShooterQualificationImpl esfShooterQualificationImpl = new ESFShooterQualificationImpl();

		esfShooterQualificationImpl.setUuid(getUuid());
		esfShooterQualificationImpl.setEsfShooterQualificationId(getEsfShooterQualificationId());
		esfShooterQualificationImpl.setName(getName());
		esfShooterQualificationImpl.setIsJunior(getIsJunior());
		esfShooterQualificationImpl.setGroupId(getGroupId());
		esfShooterQualificationImpl.setCompanyId(getCompanyId());
		esfShooterQualificationImpl.setUserId(getUserId());
		esfShooterQualificationImpl.setUserName(getUserName());
		esfShooterQualificationImpl.setCreateDate(getCreateDate());
		esfShooterQualificationImpl.setModifiedDate(getModifiedDate());
		esfShooterQualificationImpl.setDescription(getDescription());
		esfShooterQualificationImpl.setCode(getCode());

		esfShooterQualificationImpl.resetOriginalValues();

		return esfShooterQualificationImpl;
	}

	@Override
	public int compareTo(ESFShooterQualification esfShooterQualification) {
		int value = 0;

		value = getName().compareTo(esfShooterQualification.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFShooterQualification)) {
			return false;
		}

		ESFShooterQualification esfShooterQualification = (ESFShooterQualification)obj;

		long primaryKey = esfShooterQualification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFShooterQualificationModelImpl esfShooterQualificationModelImpl = this;

		esfShooterQualificationModelImpl._originalUuid = esfShooterQualificationModelImpl._uuid;

		esfShooterQualificationModelImpl._originalGroupId = esfShooterQualificationModelImpl._groupId;

		esfShooterQualificationModelImpl._setOriginalGroupId = false;

		esfShooterQualificationModelImpl._originalCompanyId = esfShooterQualificationModelImpl._companyId;

		esfShooterQualificationModelImpl._setOriginalCompanyId = false;

		esfShooterQualificationModelImpl._originalCode = esfShooterQualificationModelImpl._code;

		esfShooterQualificationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFShooterQualification> toCacheModel() {
		ESFShooterQualificationCacheModel esfShooterQualificationCacheModel = new ESFShooterQualificationCacheModel();

		esfShooterQualificationCacheModel.uuid = getUuid();

		String uuid = esfShooterQualificationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfShooterQualificationCacheModel.uuid = null;
		}

		esfShooterQualificationCacheModel.esfShooterQualificationId = getEsfShooterQualificationId();

		esfShooterQualificationCacheModel.name = getName();

		String name = esfShooterQualificationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			esfShooterQualificationCacheModel.name = null;
		}

		esfShooterQualificationCacheModel.isJunior = getIsJunior();

		esfShooterQualificationCacheModel.groupId = getGroupId();

		esfShooterQualificationCacheModel.companyId = getCompanyId();

		esfShooterQualificationCacheModel.userId = getUserId();

		esfShooterQualificationCacheModel.userName = getUserName();

		String userName = esfShooterQualificationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfShooterQualificationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfShooterQualificationCacheModel.createDate = createDate.getTime();
		}
		else {
			esfShooterQualificationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfShooterQualificationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfShooterQualificationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		esfShooterQualificationCacheModel.description = getDescription();

		String description = esfShooterQualificationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			esfShooterQualificationCacheModel.description = null;
		}

		esfShooterQualificationCacheModel.code = getCode();

		String code = esfShooterQualificationCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			esfShooterQualificationCacheModel.code = null;
		}

		return esfShooterQualificationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfShooterQualificationId=");
		sb.append(getEsfShooterQualificationId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", isJunior=");
		sb.append(getIsJunior());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", code=");
		sb.append(getCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFShooterQualification");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfShooterQualificationId</column-name><column-value><![CDATA[");
		sb.append(getEsfShooterQualificationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isJunior</column-name><column-value><![CDATA[");
		sb.append(getIsJunior());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFShooterQualification.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFShooterQualification.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfShooterQualificationId;
	private String _name;
	private boolean _isJunior;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _description;
	private String _code;
	private String _originalCode;
	private long _columnBitmask;
	private ESFShooterQualification _escapedModel;
}