/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFUnitservice;
import it.ethica.esf.model.ESFUnitserviceModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFUnitservice service. Represents a row in the &quot;ESFUnitservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFUnitserviceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFUnitserviceImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFUnitserviceImpl
 * @see it.ethica.esf.model.ESFUnitservice
 * @see it.ethica.esf.model.ESFUnitserviceModel
 * @generated
 */
public class ESFUnitserviceModelImpl extends BaseModelImpl<ESFUnitservice>
	implements ESFUnitserviceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f unitservice model instance should use the {@link it.ethica.esf.model.ESFUnitservice} interface instead.
	 */
	public static final String TABLE_NAME = "ESFUnitservice";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfUnitserviceId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFUnitservice (uuid_ VARCHAR(75) null,esfUnitserviceId LONG not null primary key,description VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ESFUnitservice";
	public static final String ORDER_BY_JPQL = " ORDER BY esfUnitservice.description ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFUnitservice.description ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFUnitservice"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFUnitservice"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFUnitservice"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long DESCRIPTION_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFUnitservice"));

	public ESFUnitserviceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfUnitserviceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfUnitserviceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfUnitserviceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFUnitservice.class;
	}

	@Override
	public String getModelClassName() {
		return ESFUnitservice.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfUnitserviceId", getEsfUnitserviceId());
		attributes.put("description", getDescription());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfUnitserviceId = (Long)attributes.get("esfUnitserviceId");

		if (esfUnitserviceId != null) {
			setEsfUnitserviceId(esfUnitserviceId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEsfUnitserviceId() {
		return _esfUnitserviceId;
	}

	@Override
	public void setEsfUnitserviceId(long esfUnitserviceId) {
		_esfUnitserviceId = esfUnitserviceId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_columnBitmask = -1L;

		if (_originalDescription == null) {
			_originalDescription = _description;
		}

		_description = description;
	}

	public String getOriginalDescription() {
		return GetterUtil.getString(_originalDescription);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ESFUnitservice.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ESFUnitservice.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFUnitservice toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFUnitservice)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFUnitserviceImpl esfUnitserviceImpl = new ESFUnitserviceImpl();

		esfUnitserviceImpl.setUuid(getUuid());
		esfUnitserviceImpl.setEsfUnitserviceId(getEsfUnitserviceId());
		esfUnitserviceImpl.setDescription(getDescription());
		esfUnitserviceImpl.setGroupId(getGroupId());
		esfUnitserviceImpl.setCompanyId(getCompanyId());
		esfUnitserviceImpl.setUserId(getUserId());
		esfUnitserviceImpl.setUserName(getUserName());
		esfUnitserviceImpl.setCreateDate(getCreateDate());
		esfUnitserviceImpl.setModifiedDate(getModifiedDate());

		esfUnitserviceImpl.resetOriginalValues();

		return esfUnitserviceImpl;
	}

	@Override
	public int compareTo(ESFUnitservice esfUnitservice) {
		int value = 0;

		value = getDescription().compareTo(esfUnitservice.getDescription());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFUnitservice)) {
			return false;
		}

		ESFUnitservice esfUnitservice = (ESFUnitservice)obj;

		long primaryKey = esfUnitservice.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFUnitserviceModelImpl esfUnitserviceModelImpl = this;

		esfUnitserviceModelImpl._originalUuid = esfUnitserviceModelImpl._uuid;

		esfUnitserviceModelImpl._originalDescription = esfUnitserviceModelImpl._description;

		esfUnitserviceModelImpl._originalGroupId = esfUnitserviceModelImpl._groupId;

		esfUnitserviceModelImpl._setOriginalGroupId = false;

		esfUnitserviceModelImpl._originalCompanyId = esfUnitserviceModelImpl._companyId;

		esfUnitserviceModelImpl._setOriginalCompanyId = false;

		esfUnitserviceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFUnitservice> toCacheModel() {
		ESFUnitserviceCacheModel esfUnitserviceCacheModel = new ESFUnitserviceCacheModel();

		esfUnitserviceCacheModel.uuid = getUuid();

		String uuid = esfUnitserviceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfUnitserviceCacheModel.uuid = null;
		}

		esfUnitserviceCacheModel.esfUnitserviceId = getEsfUnitserviceId();

		esfUnitserviceCacheModel.description = getDescription();

		String description = esfUnitserviceCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			esfUnitserviceCacheModel.description = null;
		}

		esfUnitserviceCacheModel.groupId = getGroupId();

		esfUnitserviceCacheModel.companyId = getCompanyId();

		esfUnitserviceCacheModel.userId = getUserId();

		esfUnitserviceCacheModel.userName = getUserName();

		String userName = esfUnitserviceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfUnitserviceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfUnitserviceCacheModel.createDate = createDate.getTime();
		}
		else {
			esfUnitserviceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfUnitserviceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfUnitserviceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return esfUnitserviceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfUnitserviceId=");
		sb.append(getEsfUnitserviceId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFUnitservice");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUnitserviceId</column-name><column-value><![CDATA[");
		sb.append(getEsfUnitserviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFUnitservice.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFUnitservice.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfUnitserviceId;
	private String _description;
	private String _originalDescription;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private ESFUnitservice _escapedModel;
}