/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import it.ethica.esf.model.VW_ESFIncarichiFederali;
import it.ethica.esf.model.VW_ESFIncarichiFederaliModel;
import it.ethica.esf.service.persistence.VW_ESFIncarichiFederaliPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VW_ESFIncarichiFederali service. Represents a row in the &quot;VW_ESFIncarichiFederali&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.VW_ESFIncarichiFederaliModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VW_ESFIncarichiFederaliImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_ESFIncarichiFederaliImpl
 * @see it.ethica.esf.model.VW_ESFIncarichiFederali
 * @see it.ethica.esf.model.VW_ESFIncarichiFederaliModel
 * @generated
 */
public class VW_ESFIncarichiFederaliModelImpl extends BaseModelImpl<VW_ESFIncarichiFederali>
	implements VW_ESFIncarichiFederaliModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v w_ e s f incarichi federali model instance should use the {@link it.ethica.esf.model.VW_ESFIncarichiFederali} interface instead.
	 */
	public static final String TABLE_NAME = "VW_ESFIncarichiFederali";
	public static final Object[][] TABLE_COLUMNS = {
			{ "esfUserId", Types.BIGINT },
			{ "esfFederalRoleId", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "startDate", Types.BIGINT },
			{ "endDate", Types.TIMESTAMP },
			{ "active_", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table VW_ESFIncarichiFederali (esfUserId LONG not null,esfFederalRoleId LONG not null,code_ VARCHAR(75) null,description VARCHAR(75) null,startDate LONG not null,endDate DATE not null,active_ BOOLEAN not null,primary key (esfUserId, esfFederalRoleId, startDate, endDate, active_))";
	public static final String TABLE_SQL_DROP = "drop table VW_ESFIncarichiFederali";
	public static final String ORDER_BY_JPQL = " ORDER BY vw_esfIncarichiFederali.id.esfUserId ASC, vw_esfIncarichiFederali.id.endDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VW_ESFIncarichiFederali.esfUserId ASC, VW_ESFIncarichiFederali.endDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.VW_ESFIncarichiFederali"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.VW_ESFIncarichiFederali"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.VW_ESFIncarichiFederali"),
			true);
	public static long ACTIVE__COLUMN_BITMASK = 1L;
	public static long ESFUSERID_COLUMN_BITMASK = 2L;
	public static long ENDDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.VW_ESFIncarichiFederali"));

	public VW_ESFIncarichiFederaliModelImpl() {
	}

	@Override
	public VW_ESFIncarichiFederaliPK getPrimaryKey() {
		return new VW_ESFIncarichiFederaliPK(_esfUserId, _esfFederalRoleId,
			_startDate, _endDate, _active_);
	}

	@Override
	public void setPrimaryKey(VW_ESFIncarichiFederaliPK primaryKey) {
		setEsfUserId(primaryKey.esfUserId);
		setEsfFederalRoleId(primaryKey.esfFederalRoleId);
		setStartDate(primaryKey.startDate);
		setEndDate(primaryKey.endDate);
		setActive_(primaryKey.active_);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VW_ESFIncarichiFederaliPK(_esfUserId, _esfFederalRoleId,
			_startDate, _endDate, _active_);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VW_ESFIncarichiFederaliPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VW_ESFIncarichiFederali.class;
	}

	@Override
	public String getModelClassName() {
		return VW_ESFIncarichiFederali.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("esfUserId", getEsfUserId());
		attributes.put("esfFederalRoleId", getEsfFederalRoleId());
		attributes.put("code_", getCode_());
		attributes.put("description", getDescription());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("active_", getActive_());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		Long esfFederalRoleId = (Long)attributes.get("esfFederalRoleId");

		if (esfFederalRoleId != null) {
			setEsfFederalRoleId(esfFederalRoleId);
		}

		String code_ = (String)attributes.get("code_");

		if (code_ != null) {
			setCode_(code_);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long startDate = (Long)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Boolean active_ = (Boolean)attributes.get("active_");

		if (active_ != null) {
			setActive_(active_);
		}
	}

	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalEsfUserId) {
			_setOriginalEsfUserId = true;

			_originalEsfUserId = _esfUserId;
		}

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	public long getOriginalEsfUserId() {
		return _originalEsfUserId;
	}

	@Override
	public long getEsfFederalRoleId() {
		return _esfFederalRoleId;
	}

	@Override
	public void setEsfFederalRoleId(long esfFederalRoleId) {
		_esfFederalRoleId = esfFederalRoleId;
	}

	@Override
	public String getCode_() {
		if (_code_ == null) {
			return StringPool.BLANK;
		}
		else {
			return _code_;
		}
	}

	@Override
	public void setCode_(String code_) {
		_code_ = code_;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public long getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(long startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_columnBitmask = -1L;

		_endDate = endDate;
	}

	@Override
	public boolean getActive_() {
		return _active_;
	}

	@Override
	public boolean isActive_() {
		return _active_;
	}

	@Override
	public void setActive_(boolean active_) {
		_columnBitmask |= ACTIVE__COLUMN_BITMASK;

		if (!_setOriginalActive_) {
			_setOriginalActive_ = true;

			_originalActive_ = _active_;
		}

		_active_ = active_;
	}

	public boolean getOriginalActive_() {
		return _originalActive_;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VW_ESFIncarichiFederali toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VW_ESFIncarichiFederali)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VW_ESFIncarichiFederaliImpl vw_esfIncarichiFederaliImpl = new VW_ESFIncarichiFederaliImpl();

		vw_esfIncarichiFederaliImpl.setEsfUserId(getEsfUserId());
		vw_esfIncarichiFederaliImpl.setEsfFederalRoleId(getEsfFederalRoleId());
		vw_esfIncarichiFederaliImpl.setCode_(getCode_());
		vw_esfIncarichiFederaliImpl.setDescription(getDescription());
		vw_esfIncarichiFederaliImpl.setStartDate(getStartDate());
		vw_esfIncarichiFederaliImpl.setEndDate(getEndDate());
		vw_esfIncarichiFederaliImpl.setActive_(getActive_());

		vw_esfIncarichiFederaliImpl.resetOriginalValues();

		return vw_esfIncarichiFederaliImpl;
	}

	@Override
	public int compareTo(VW_ESFIncarichiFederali vw_esfIncarichiFederali) {
		int value = 0;

		if (getEsfUserId() < vw_esfIncarichiFederali.getEsfUserId()) {
			value = -1;
		}
		else if (getEsfUserId() > vw_esfIncarichiFederali.getEsfUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getEndDate(),
				vw_esfIncarichiFederali.getEndDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VW_ESFIncarichiFederali)) {
			return false;
		}

		VW_ESFIncarichiFederali vw_esfIncarichiFederali = (VW_ESFIncarichiFederali)obj;

		VW_ESFIncarichiFederaliPK primaryKey = vw_esfIncarichiFederali.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		VW_ESFIncarichiFederaliModelImpl vw_esfIncarichiFederaliModelImpl = this;

		vw_esfIncarichiFederaliModelImpl._originalEsfUserId = vw_esfIncarichiFederaliModelImpl._esfUserId;

		vw_esfIncarichiFederaliModelImpl._setOriginalEsfUserId = false;

		vw_esfIncarichiFederaliModelImpl._originalActive_ = vw_esfIncarichiFederaliModelImpl._active_;

		vw_esfIncarichiFederaliModelImpl._setOriginalActive_ = false;

		vw_esfIncarichiFederaliModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VW_ESFIncarichiFederali> toCacheModel() {
		VW_ESFIncarichiFederaliCacheModel vw_esfIncarichiFederaliCacheModel = new VW_ESFIncarichiFederaliCacheModel();

		vw_esfIncarichiFederaliCacheModel.esfUserId = getEsfUserId();

		vw_esfIncarichiFederaliCacheModel.esfFederalRoleId = getEsfFederalRoleId();

		vw_esfIncarichiFederaliCacheModel.code_ = getCode_();

		String code_ = vw_esfIncarichiFederaliCacheModel.code_;

		if ((code_ != null) && (code_.length() == 0)) {
			vw_esfIncarichiFederaliCacheModel.code_ = null;
		}

		vw_esfIncarichiFederaliCacheModel.description = getDescription();

		String description = vw_esfIncarichiFederaliCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			vw_esfIncarichiFederaliCacheModel.description = null;
		}

		vw_esfIncarichiFederaliCacheModel.startDate = getStartDate();

		Date endDate = getEndDate();

		if (endDate != null) {
			vw_esfIncarichiFederaliCacheModel.endDate = endDate.getTime();
		}
		else {
			vw_esfIncarichiFederaliCacheModel.endDate = Long.MIN_VALUE;
		}

		vw_esfIncarichiFederaliCacheModel.active_ = getActive_();

		return vw_esfIncarichiFederaliCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", esfFederalRoleId=");
		sb.append(getEsfFederalRoleId());
		sb.append(", code_=");
		sb.append(getCode_());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", active_=");
		sb.append(getActive_());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.VW_ESFIncarichiFederali");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfFederalRoleId</column-name><column-value><![CDATA[");
		sb.append(getEsfFederalRoleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code_</column-name><column-value><![CDATA[");
		sb.append(getCode_());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active_</column-name><column-value><![CDATA[");
		sb.append(getActive_());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VW_ESFIncarichiFederali.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VW_ESFIncarichiFederali.class
		};
	private long _esfUserId;
	private String _esfUserUuid;
	private long _originalEsfUserId;
	private boolean _setOriginalEsfUserId;
	private long _esfFederalRoleId;
	private String _code_;
	private String _description;
	private long _startDate;
	private Date _endDate;
	private boolean _active_;
	private boolean _originalActive_;
	private boolean _setOriginalActive_;
	private long _columnBitmask;
	private VW_ESFIncarichiFederali _escapedModel;
}