/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import it.ethica.esf.model.VW_ESFListaIncarichi;
import it.ethica.esf.model.VW_ESFListaIncarichiModel;
import it.ethica.esf.service.persistence.VW_ESFListaIncarichiPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VW_ESFListaIncarichi service. Represents a row in the &quot;VW_ESFListaIncarichi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.VW_ESFListaIncarichiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VW_ESFListaIncarichiImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_ESFListaIncarichiImpl
 * @see it.ethica.esf.model.VW_ESFListaIncarichi
 * @see it.ethica.esf.model.VW_ESFListaIncarichiModel
 * @generated
 */
public class VW_ESFListaIncarichiModelImpl extends BaseModelImpl<VW_ESFListaIncarichi>
	implements VW_ESFListaIncarichiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v w_ e s f lista incarichi model instance should use the {@link it.ethica.esf.model.VW_ESFListaIncarichi} interface instead.
	 */
	public static final String TABLE_NAME = "VW_ESFListaIncarichi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "AnniPrecedenti", Types.INTEGER },
			{ "AnnoFineIncarico", Types.INTEGER },
			{ "AnnoInizioIncarico", Types.INTEGER },
			{ "AnnoCorrente", Types.INTEGER },
			{ "NomeRuolo", Types.VARCHAR },
			{ "endDate", Types.TIMESTAMP },
			{ "startDate", Types.TIMESTAMP },
			{ "esfUserId", Types.BIGINT },
			{ "esfOrganizationId", Types.BIGINT },
			{ "lastName", Types.VARCHAR },
			{ "firstName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table VW_ESFListaIncarichi (AnniPrecedenti INTEGER not null,AnnoFineIncarico INTEGER not null,AnnoInizioIncarico INTEGER not null,AnnoCorrente INTEGER not null,NomeRuolo VARCHAR(75) not null,endDate DATE null,startDate DATE not null,esfUserId LONG not null,esfOrganizationId LONG not null,lastName VARCHAR(75) not null,firstName VARCHAR(75) not null,primary key (AnniPrecedenti, AnnoFineIncarico, AnnoInizioIncarico, AnnoCorrente, NomeRuolo, startDate, esfUserId, esfOrganizationId, lastName, firstName))";
	public static final String TABLE_SQL_DROP = "drop table VW_ESFListaIncarichi";
	public static final String ORDER_BY_JPQL = " ORDER BY vw_esfListaIncarichi.endDate ASC, vw_esfListaIncarichi.id.esfUserId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VW_ESFListaIncarichi.endDate ASC, VW_ESFListaIncarichi.esfUserId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.VW_ESFListaIncarichi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.VW_ESFListaIncarichi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.VW_ESFListaIncarichi"),
			true);
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 1L;
	public static long ENDDATE_COLUMN_BITMASK = 2L;
	public static long ESFUSERID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.VW_ESFListaIncarichi"));

	public VW_ESFListaIncarichiModelImpl() {
	}

	@Override
	public VW_ESFListaIncarichiPK getPrimaryKey() {
		return new VW_ESFListaIncarichiPK(_AnniPrecedenti, _AnnoFineIncarico,
			_AnnoInizioIncarico, _AnnoCorrente, _NomeRuolo, _startDate,
			_esfUserId, _esfOrganizationId, _lastName, _firstName);
	}

	@Override
	public void setPrimaryKey(VW_ESFListaIncarichiPK primaryKey) {
		setAnniPrecedenti(primaryKey.AnniPrecedenti);
		setAnnoFineIncarico(primaryKey.AnnoFineIncarico);
		setAnnoInizioIncarico(primaryKey.AnnoInizioIncarico);
		setAnnoCorrente(primaryKey.AnnoCorrente);
		setNomeRuolo(primaryKey.NomeRuolo);
		setStartDate(primaryKey.startDate);
		setEsfUserId(primaryKey.esfUserId);
		setEsfOrganizationId(primaryKey.esfOrganizationId);
		setLastName(primaryKey.lastName);
		setFirstName(primaryKey.firstName);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VW_ESFListaIncarichiPK(_AnniPrecedenti, _AnnoFineIncarico,
			_AnnoInizioIncarico, _AnnoCorrente, _NomeRuolo, _startDate,
			_esfUserId, _esfOrganizationId, _lastName, _firstName);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VW_ESFListaIncarichiPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VW_ESFListaIncarichi.class;
	}

	@Override
	public String getModelClassName() {
		return VW_ESFListaIncarichi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("AnniPrecedenti", getAnniPrecedenti());
		attributes.put("AnnoFineIncarico", getAnnoFineIncarico());
		attributes.put("AnnoInizioIncarico", getAnnoInizioIncarico());
		attributes.put("AnnoCorrente", getAnnoCorrente());
		attributes.put("NomeRuolo", getNomeRuolo());
		attributes.put("endDate", getEndDate());
		attributes.put("startDate", getStartDate());
		attributes.put("esfUserId", getEsfUserId());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("lastName", getLastName());
		attributes.put("firstName", getFirstName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer AnniPrecedenti = (Integer)attributes.get("AnniPrecedenti");

		if (AnniPrecedenti != null) {
			setAnniPrecedenti(AnniPrecedenti);
		}

		Integer AnnoFineIncarico = (Integer)attributes.get("AnnoFineIncarico");

		if (AnnoFineIncarico != null) {
			setAnnoFineIncarico(AnnoFineIncarico);
		}

		Integer AnnoInizioIncarico = (Integer)attributes.get(
				"AnnoInizioIncarico");

		if (AnnoInizioIncarico != null) {
			setAnnoInizioIncarico(AnnoInizioIncarico);
		}

		Integer AnnoCorrente = (Integer)attributes.get("AnnoCorrente");

		if (AnnoCorrente != null) {
			setAnnoCorrente(AnnoCorrente);
		}

		String NomeRuolo = (String)attributes.get("NomeRuolo");

		if (NomeRuolo != null) {
			setNomeRuolo(NomeRuolo);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		String lastName = (String)attributes.get("lastName");

		if (lastName != null) {
			setLastName(lastName);
		}

		String firstName = (String)attributes.get("firstName");

		if (firstName != null) {
			setFirstName(firstName);
		}
	}

	@Override
	public int getAnniPrecedenti() {
		return _AnniPrecedenti;
	}

	@Override
	public void setAnniPrecedenti(int AnniPrecedenti) {
		_AnniPrecedenti = AnniPrecedenti;
	}

	@Override
	public int getAnnoFineIncarico() {
		return _AnnoFineIncarico;
	}

	@Override
	public void setAnnoFineIncarico(int AnnoFineIncarico) {
		_AnnoFineIncarico = AnnoFineIncarico;
	}

	@Override
	public int getAnnoInizioIncarico() {
		return _AnnoInizioIncarico;
	}

	@Override
	public void setAnnoInizioIncarico(int AnnoInizioIncarico) {
		_AnnoInizioIncarico = AnnoInizioIncarico;
	}

	@Override
	public int getAnnoCorrente() {
		return _AnnoCorrente;
	}

	@Override
	public void setAnnoCorrente(int AnnoCorrente) {
		_AnnoCorrente = AnnoCorrente;
	}

	@Override
	public String getNomeRuolo() {
		if (_NomeRuolo == null) {
			return StringPool.BLANK;
		}
		else {
			return _NomeRuolo;
		}
	}

	@Override
	public void setNomeRuolo(String NomeRuolo) {
		_NomeRuolo = NomeRuolo;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_columnBitmask = -1L;

		_endDate = endDate;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask = -1L;

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_columnBitmask |= ESFORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalEsfOrganizationId) {
			_setOriginalEsfOrganizationId = true;

			_originalEsfOrganizationId = _esfOrganizationId;
		}

		_esfOrganizationId = esfOrganizationId;
	}

	public long getOriginalEsfOrganizationId() {
		return _originalEsfOrganizationId;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VW_ESFListaIncarichi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VW_ESFListaIncarichi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VW_ESFListaIncarichiImpl vw_esfListaIncarichiImpl = new VW_ESFListaIncarichiImpl();

		vw_esfListaIncarichiImpl.setAnniPrecedenti(getAnniPrecedenti());
		vw_esfListaIncarichiImpl.setAnnoFineIncarico(getAnnoFineIncarico());
		vw_esfListaIncarichiImpl.setAnnoInizioIncarico(getAnnoInizioIncarico());
		vw_esfListaIncarichiImpl.setAnnoCorrente(getAnnoCorrente());
		vw_esfListaIncarichiImpl.setNomeRuolo(getNomeRuolo());
		vw_esfListaIncarichiImpl.setEndDate(getEndDate());
		vw_esfListaIncarichiImpl.setStartDate(getStartDate());
		vw_esfListaIncarichiImpl.setEsfUserId(getEsfUserId());
		vw_esfListaIncarichiImpl.setEsfOrganizationId(getEsfOrganizationId());
		vw_esfListaIncarichiImpl.setLastName(getLastName());
		vw_esfListaIncarichiImpl.setFirstName(getFirstName());

		vw_esfListaIncarichiImpl.resetOriginalValues();

		return vw_esfListaIncarichiImpl;
	}

	@Override
	public int compareTo(VW_ESFListaIncarichi vw_esfListaIncarichi) {
		int value = 0;

		value = DateUtil.compareTo(getEndDate(),
				vw_esfListaIncarichi.getEndDate());

		if (value != 0) {
			return value;
		}

		if (getEsfUserId() < vw_esfListaIncarichi.getEsfUserId()) {
			value = -1;
		}
		else if (getEsfUserId() > vw_esfListaIncarichi.getEsfUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VW_ESFListaIncarichi)) {
			return false;
		}

		VW_ESFListaIncarichi vw_esfListaIncarichi = (VW_ESFListaIncarichi)obj;

		VW_ESFListaIncarichiPK primaryKey = vw_esfListaIncarichi.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		VW_ESFListaIncarichiModelImpl vw_esfListaIncarichiModelImpl = this;

		vw_esfListaIncarichiModelImpl._originalEsfOrganizationId = vw_esfListaIncarichiModelImpl._esfOrganizationId;

		vw_esfListaIncarichiModelImpl._setOriginalEsfOrganizationId = false;

		vw_esfListaIncarichiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VW_ESFListaIncarichi> toCacheModel() {
		VW_ESFListaIncarichiCacheModel vw_esfListaIncarichiCacheModel = new VW_ESFListaIncarichiCacheModel();

		vw_esfListaIncarichiCacheModel.AnniPrecedenti = getAnniPrecedenti();

		vw_esfListaIncarichiCacheModel.AnnoFineIncarico = getAnnoFineIncarico();

		vw_esfListaIncarichiCacheModel.AnnoInizioIncarico = getAnnoInizioIncarico();

		vw_esfListaIncarichiCacheModel.AnnoCorrente = getAnnoCorrente();

		vw_esfListaIncarichiCacheModel.NomeRuolo = getNomeRuolo();

		String NomeRuolo = vw_esfListaIncarichiCacheModel.NomeRuolo;

		if ((NomeRuolo != null) && (NomeRuolo.length() == 0)) {
			vw_esfListaIncarichiCacheModel.NomeRuolo = null;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			vw_esfListaIncarichiCacheModel.endDate = endDate.getTime();
		}
		else {
			vw_esfListaIncarichiCacheModel.endDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			vw_esfListaIncarichiCacheModel.startDate = startDate.getTime();
		}
		else {
			vw_esfListaIncarichiCacheModel.startDate = Long.MIN_VALUE;
		}

		vw_esfListaIncarichiCacheModel.esfUserId = getEsfUserId();

		vw_esfListaIncarichiCacheModel.esfOrganizationId = getEsfOrganizationId();

		vw_esfListaIncarichiCacheModel.lastName = getLastName();

		String lastName = vw_esfListaIncarichiCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			vw_esfListaIncarichiCacheModel.lastName = null;
		}

		vw_esfListaIncarichiCacheModel.firstName = getFirstName();

		String firstName = vw_esfListaIncarichiCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			vw_esfListaIncarichiCacheModel.firstName = null;
		}

		return vw_esfListaIncarichiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{AnniPrecedenti=");
		sb.append(getAnniPrecedenti());
		sb.append(", AnnoFineIncarico=");
		sb.append(getAnnoFineIncarico());
		sb.append(", AnnoInizioIncarico=");
		sb.append(getAnnoInizioIncarico());
		sb.append(", AnnoCorrente=");
		sb.append(getAnnoCorrente());
		sb.append(", NomeRuolo=");
		sb.append(getNomeRuolo());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.VW_ESFListaIncarichi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>AnniPrecedenti</column-name><column-value><![CDATA[");
		sb.append(getAnniPrecedenti());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoFineIncarico</column-name><column-value><![CDATA[");
		sb.append(getAnnoFineIncarico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoInizioIncarico</column-name><column-value><![CDATA[");
		sb.append(getAnnoInizioIncarico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoCorrente</column-name><column-value><![CDATA[");
		sb.append(getAnnoCorrente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NomeRuolo</column-name><column-value><![CDATA[");
		sb.append(getNomeRuolo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VW_ESFListaIncarichi.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VW_ESFListaIncarichi.class
		};
	private int _AnniPrecedenti;
	private int _AnnoFineIncarico;
	private int _AnnoInizioIncarico;
	private int _AnnoCorrente;
	private String _NomeRuolo;
	private Date _endDate;
	private Date _startDate;
	private long _esfUserId;
	private String _esfUserUuid;
	private long _esfOrganizationId;
	private long _originalEsfOrganizationId;
	private boolean _setOriginalEsfOrganizationId;
	private String _lastName;
	private String _firstName;
	private long _columnBitmask;
	private VW_ESFListaIncarichi _escapedModel;
}