/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFAirport service. Represents a row in the &quot;ESFAirport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFAirportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFAirportImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFAirport
 * @see it.ethica.esf.model.impl.ESFAirportImpl
 * @see it.ethica.esf.model.impl.ESFAirportModelImpl
 * @generated
 */
public interface ESFAirportModel extends BaseModel<ESFAirport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f airport model instance should use the {@link ESFAirport} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f airport.
	 *
	 * @return the primary key of this e s f airport
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f airport.
	 *
	 * @param primaryKey the primary key of this e s f airport
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf airport ID of this e s f airport.
	 *
	 * @return the esf airport ID of this e s f airport
	 */
	public long getEsfAirportId();

	/**
	 * Sets the esf airport ID of this e s f airport.
	 *
	 * @param esfAirportId the esf airport ID of this e s f airport
	 */
	public void setEsfAirportId(long esfAirportId);

	/**
	 * Returns the name of this e s f airport.
	 *
	 * @return the name of this e s f airport
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f airport.
	 *
	 * @param name the name of this e s f airport
	 */
	public void setName(String name);

	/**
	 * Returns the city of this e s f airport.
	 *
	 * @return the city of this e s f airport
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this e s f airport.
	 *
	 * @param city the city of this e s f airport
	 */
	public void setCity(String city);

	/**
	 * Returns the country of this e s f airport.
	 *
	 * @return the country of this e s f airport
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this e s f airport.
	 *
	 * @param country the country of this e s f airport
	 */
	public void setCountry(String country);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFAirport esfAirport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFAirport> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFAirport toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFAirport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}