/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFAddress service. Represents a row in the &quot;ESFAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFAddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFAddressImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFAddress
 * @see it.ethica.esf.model.impl.ESFAddressImpl
 * @see it.ethica.esf.model.impl.ESFAddressModelImpl
 * @generated
 */
public interface ESFAddressModel extends BaseModel<ESFAddress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f address model instance should use the {@link ESFAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f address.
	 *
	 * @return the primary key of this e s f address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f address.
	 *
	 * @param primaryKey the primary key of this e s f address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f address.
	 *
	 * @return the uuid of this e s f address
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f address.
	 *
	 * @param uuid the uuid of this e s f address
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf address ID of this e s f address.
	 *
	 * @return the esf address ID of this e s f address
	 */
	public long getEsfAddressId();

	/**
	 * Sets the esf address ID of this e s f address.
	 *
	 * @param esfAddressId the esf address ID of this e s f address
	 */
	public void setEsfAddressId(long esfAddressId);

	/**
	 * Returns the longitude of this e s f address.
	 *
	 * @return the longitude of this e s f address
	 */
	public double getLongitude();

	/**
	 * Sets the longitude of this e s f address.
	 *
	 * @param longitude the longitude of this e s f address
	 */
	public void setLongitude(double longitude);

	/**
	 * Returns the latitude of this e s f address.
	 *
	 * @return the latitude of this e s f address
	 */
	public double getLatitude();

	/**
	 * Sets the latitude of this e s f address.
	 *
	 * @param latitude the latitude of this e s f address
	 */
	public void setLatitude(double latitude);

	/**
	 * Returns the esf country ID of this e s f address.
	 *
	 * @return the esf country ID of this e s f address
	 */
	@AutoEscape
	public String getEsfCountryId();

	/**
	 * Sets the esf country ID of this e s f address.
	 *
	 * @param esfCountryId the esf country ID of this e s f address
	 */
	public void setEsfCountryId(String esfCountryId);

	/**
	 * Returns the esf region ID of this e s f address.
	 *
	 * @return the esf region ID of this e s f address
	 */
	@AutoEscape
	public String getEsfRegionId();

	/**
	 * Sets the esf region ID of this e s f address.
	 *
	 * @param esfRegionId the esf region ID of this e s f address
	 */
	public void setEsfRegionId(String esfRegionId);

	/**
	 * Returns the esf province ID of this e s f address.
	 *
	 * @return the esf province ID of this e s f address
	 */
	@AutoEscape
	public String getEsfProvinceId();

	/**
	 * Sets the esf province ID of this e s f address.
	 *
	 * @param esfProvinceId the esf province ID of this e s f address
	 */
	public void setEsfProvinceId(String esfProvinceId);

	/**
	 * Returns the esf city ID of this e s f address.
	 *
	 * @return the esf city ID of this e s f address
	 */
	public long getEsfCityId();

	/**
	 * Sets the esf city ID of this e s f address.
	 *
	 * @param esfCityId the esf city ID of this e s f address
	 */
	public void setEsfCityId(long esfCityId);

	/**
	 * Returns the group ID of this e s f address.
	 *
	 * @return the group ID of this e s f address
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f address.
	 *
	 * @param groupId the group ID of this e s f address
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the type of this e s f address.
	 *
	 * @return the type of this e s f address
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this e s f address.
	 *
	 * @param type the type of this e s f address
	 */
	public void setType(String type);

	/**
	 * Returns the list type ID of this e s f address.
	 *
	 * @return the list type ID of this e s f address
	 */
	public int getListTypeId();

	/**
	 * Sets the list type ID of this e s f address.
	 *
	 * @param listTypeId the list type ID of this e s f address
	 */
	public void setListTypeId(int listTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFAddress esfAddress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFAddress> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFAddress toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFAddress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}