/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFCountry service. Represents a row in the &quot;ESFCountry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFCountryImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFCountry
 * @see it.ethica.esf.model.impl.ESFCountryImpl
 * @see it.ethica.esf.model.impl.ESFCountryModelImpl
 * @generated
 */
public interface ESFCountryModel extends BaseModel<ESFCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f country model instance should use the {@link ESFCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f country.
	 *
	 * @return the primary key of this e s f country
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this e s f country.
	 *
	 * @param primaryKey the primary key of this e s f country
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the id country of this e s f country.
	 *
	 * @return the id country of this e s f country
	 */
	@AutoEscape
	public String getIdCountry();

	/**
	 * Sets the id country of this e s f country.
	 *
	 * @param idCountry the id country of this e s f country
	 */
	public void setIdCountry(String idCountry);

	/**
	 * Returns the name of this e s f country.
	 *
	 * @return the name of this e s f country
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f country.
	 *
	 * @param name the name of this e s f country
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFCountry esfCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFCountry> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFCountry toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}