/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFOrganizationUnitservice service. Represents a row in the &quot;ESFOrganizationUnitservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFOrganizationUnitserviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFOrganizationUnitserviceImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrganizationUnitservice
 * @see it.ethica.esf.model.impl.ESFOrganizationUnitserviceImpl
 * @see it.ethica.esf.model.impl.ESFOrganizationUnitserviceModelImpl
 * @generated
 */
public interface ESFOrganizationUnitserviceModel extends BaseModel<ESFOrganizationUnitservice>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f organization unitservice model instance should use the {@link ESFOrganizationUnitservice} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f organization unitservice.
	 *
	 * @return the primary key of this e s f organization unitservice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f organization unitservice.
	 *
	 * @param primaryKey the primary key of this e s f organization unitservice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f organization unitservice.
	 *
	 * @return the uuid of this e s f organization unitservice
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this e s f organization unitservice.
	 *
	 * @param uuid the uuid of this e s f organization unitservice
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the esf organization unitservice ID of this e s f organization unitservice.
	 *
	 * @return the esf organization unitservice ID of this e s f organization unitservice
	 */
	public long getEsfOrganizationUnitserviceId();

	/**
	 * Sets the esf organization unitservice ID of this e s f organization unitservice.
	 *
	 * @param esfOrganizationUnitserviceId the esf organization unitservice ID of this e s f organization unitservice
	 */
	public void setEsfOrganizationUnitserviceId(
		long esfOrganizationUnitserviceId);

	/**
	 * Returns the esf organization ID of this e s f organization unitservice.
	 *
	 * @return the esf organization ID of this e s f organization unitservice
	 */
	public long getEsfOrganizationId();

	/**
	 * Sets the esf organization ID of this e s f organization unitservice.
	 *
	 * @param esfOrganizationId the esf organization ID of this e s f organization unitservice
	 */
	public void setEsfOrganizationId(long esfOrganizationId);

	/**
	 * Returns the esf unitservice ID of this e s f organization unitservice.
	 *
	 * @return the esf unitservice ID of this e s f organization unitservice
	 */
	public long getEsfUnitserviceId();

	/**
	 * Sets the esf unitservice ID of this e s f organization unitservice.
	 *
	 * @param esfUnitserviceId the esf unitservice ID of this e s f organization unitservice
	 */
	public void setEsfUnitserviceId(long esfUnitserviceId);

	/**
	 * Returns the number unitservices of this e s f organization unitservice.
	 *
	 * @return the number unitservices of this e s f organization unitservice
	 */
	public long getNumberUnitservices();

	/**
	 * Sets the number unitservices of this e s f organization unitservice.
	 *
	 * @param numberUnitservices the number unitservices of this e s f organization unitservice
	 */
	public void setNumberUnitservices(long numberUnitservices);

	/**
	 * Returns the description of this e s f organization unitservice.
	 *
	 * @return the description of this e s f organization unitservice
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f organization unitservice.
	 *
	 * @param description the description of this e s f organization unitservice
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this e s f organization unitservice.
	 *
	 * @return the group ID of this e s f organization unitservice
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f organization unitservice.
	 *
	 * @param groupId the group ID of this e s f organization unitservice
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e s f organization unitservice.
	 *
	 * @return the company ID of this e s f organization unitservice
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e s f organization unitservice.
	 *
	 * @param companyId the company ID of this e s f organization unitservice
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e s f organization unitservice.
	 *
	 * @return the user ID of this e s f organization unitservice
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e s f organization unitservice.
	 *
	 * @param userId the user ID of this e s f organization unitservice
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f organization unitservice.
	 *
	 * @return the user uuid of this e s f organization unitservice
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f organization unitservice.
	 *
	 * @param userUuid the user uuid of this e s f organization unitservice
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e s f organization unitservice.
	 *
	 * @return the user name of this e s f organization unitservice
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e s f organization unitservice.
	 *
	 * @param userName the user name of this e s f organization unitservice
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e s f organization unitservice.
	 *
	 * @return the create date of this e s f organization unitservice
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e s f organization unitservice.
	 *
	 * @param createDate the create date of this e s f organization unitservice
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e s f organization unitservice.
	 *
	 * @return the modified date of this e s f organization unitservice
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e s f organization unitservice.
	 *
	 * @param modifiedDate the modified date of this e s f organization unitservice
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.ethica.esf.model.ESFOrganizationUnitservice esfOrganizationUnitservice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFOrganizationUnitservice> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFOrganizationUnitservice toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFOrganizationUnitservice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}