/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFState service. Represents a row in the &quot;ESFState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFStateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFStateImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFState
 * @see it.ethica.esf.model.impl.ESFStateImpl
 * @see it.ethica.esf.model.impl.ESFStateModelImpl
 * @generated
 */
public interface ESFStateModel extends BaseModel<ESFState> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f state model instance should use the {@link ESFState} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f state.
	 *
	 * @return the primary key of this e s f state
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f state.
	 *
	 * @param primaryKey the primary key of this e s f state
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf state ID of this e s f state.
	 *
	 * @return the esf state ID of this e s f state
	 */
	public long getEsfStateId();

	/**
	 * Sets the esf state ID of this e s f state.
	 *
	 * @param esfStateId the esf state ID of this e s f state
	 */
	public void setEsfStateId(long esfStateId);

	/**
	 * Returns the name of this e s f state.
	 *
	 * @return the name of this e s f state
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f state.
	 *
	 * @param name the name of this e s f state
	 */
	public void setName(String name);

	/**
	 * Returns the description of this e s f state.
	 *
	 * @return the description of this e s f state
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f state.
	 *
	 * @param description the description of this e s f state
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.ethica.esf.model.ESFState esfState);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.ethica.esf.model.ESFState> toCacheModel();

	@Override
	public it.ethica.esf.model.ESFState toEscapedModel();

	@Override
	public it.ethica.esf.model.ESFState toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}