/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFOrder service. Represents a row in the &quot;ESFOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFOrderImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrder
 * @see com.ethica.esf.model.impl.ESFOrderImpl
 * @see com.ethica.esf.model.impl.ESFOrderModelImpl
 * @generated
 */
public interface ESFOrderModel extends BaseModel<ESFOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f order model instance should use the {@link ESFOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f order.
	 *
	 * @return the primary key of this e s f order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f order.
	 *
	 * @param primaryKey the primary key of this e s f order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf order ID of this e s f order.
	 *
	 * @return the esf order ID of this e s f order
	 */
	public long getEsfOrderId();

	/**
	 * Sets the esf order ID of this e s f order.
	 *
	 * @param esfOrderId the esf order ID of this e s f order
	 */
	public void setEsfOrderId(long esfOrderId);

	/**
	 * Returns the code of this e s f order.
	 *
	 * @return the code of this e s f order
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f order.
	 *
	 * @param code the code of this e s f order
	 */
	public void setCode(String code);

	/**
	 * Returns the data of this e s f order.
	 *
	 * @return the data of this e s f order
	 */
	public Date getData();

	/**
	 * Sets the data of this e s f order.
	 *
	 * @param data the data of this e s f order
	 */
	public void setData(Date data);

	/**
	 * Returns the description of this e s f order.
	 *
	 * @return the description of this e s f order
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f order.
	 *
	 * @param description the description of this e s f order
	 */
	public void setDescription(String description);

	/**
	 * Returns the esf stockist ID of this e s f order.
	 *
	 * @return the esf stockist ID of this e s f order
	 */
	public long getEsfStockistId();

	/**
	 * Sets the esf stockist ID of this e s f order.
	 *
	 * @param esfStockistId the esf stockist ID of this e s f order
	 */
	public void setEsfStockistId(long esfStockistId);

	/**
	 * Returns the qty of this e s f order.
	 *
	 * @return the qty of this e s f order
	 */
	public long getQty();

	/**
	 * Sets the qty of this e s f order.
	 *
	 * @param qty the qty of this e s f order
	 */
	public void setQty(long qty);

	/**
	 * Returns the esf article ID of this e s f order.
	 *
	 * @return the esf article ID of this e s f order
	 */
	public long getEsfArticleId();

	/**
	 * Sets the esf article ID of this e s f order.
	 *
	 * @param esfArticleId the esf article ID of this e s f order
	 */
	public void setEsfArticleId(long esfArticleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFOrder esfOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFOrder> toCacheModel();

	@Override
	public ESFOrder toEscapedModel();

	@Override
	public ESFOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}