/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFBill service. Represents a row in the &quot;ESFBill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFBillModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFBillImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFBill
 * @see com.ethica.esf.model.impl.ESFBillImpl
 * @see com.ethica.esf.model.impl.ESFBillModelImpl
 * @generated
 */
public interface ESFBillModel extends BaseModel<ESFBill> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f bill model instance should use the {@link ESFBill} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f bill.
	 *
	 * @return the primary key of this e s f bill
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f bill.
	 *
	 * @param primaryKey the primary key of this e s f bill
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf bill ID of this e s f bill.
	 *
	 * @return the esf bill ID of this e s f bill
	 */
	public long getEsfBillId();

	/**
	 * Sets the esf bill ID of this e s f bill.
	 *
	 * @param esfBillId the esf bill ID of this e s f bill
	 */
	public void setEsfBillId(long esfBillId);

	/**
	 * Returns the esf article ID of this e s f bill.
	 *
	 * @return the esf article ID of this e s f bill
	 */
	public long getEsfArticleId();

	/**
	 * Sets the esf article ID of this e s f bill.
	 *
	 * @param esfArticleId the esf article ID of this e s f bill
	 */
	public void setEsfArticleId(long esfArticleId);

	/**
	 * Returns the esf order ID of this e s f bill.
	 *
	 * @return the esf order ID of this e s f bill
	 */
	public long getEsfOrderId();

	/**
	 * Sets the esf order ID of this e s f bill.
	 *
	 * @param esfOrderId the esf order ID of this e s f bill
	 */
	public void setEsfOrderId(long esfOrderId);

	/**
	 * Returns the bill number of this e s f bill.
	 *
	 * @return the bill number of this e s f bill
	 */
	@AutoEscape
	public String getBillNumber();

	/**
	 * Sets the bill number of this e s f bill.
	 *
	 * @param billNumber the bill number of this e s f bill
	 */
	public void setBillNumber(String billNumber);

	/**
	 * Returns the xxxl qty of this e s f bill.
	 *
	 * @return the xxxl qty of this e s f bill
	 */
	public long getXxxlQty();

	/**
	 * Sets the xxxl qty of this e s f bill.
	 *
	 * @param xxxlQty the xxxl qty of this e s f bill
	 */
	public void setXxxlQty(long xxxlQty);

	/**
	 * Returns the xxl qty of this e s f bill.
	 *
	 * @return the xxl qty of this e s f bill
	 */
	public long getXxlQty();

	/**
	 * Sets the xxl qty of this e s f bill.
	 *
	 * @param xxlQty the xxl qty of this e s f bill
	 */
	public void setXxlQty(long xxlQty);

	/**
	 * Returns the xl qty of this e s f bill.
	 *
	 * @return the xl qty of this e s f bill
	 */
	public long getXlQty();

	/**
	 * Sets the xl qty of this e s f bill.
	 *
	 * @param xlQty the xl qty of this e s f bill
	 */
	public void setXlQty(long xlQty);

	/**
	 * Returns the l qty of this e s f bill.
	 *
	 * @return the l qty of this e s f bill
	 */
	public long getLQty();

	/**
	 * Sets the l qty of this e s f bill.
	 *
	 * @param lQty the l qty of this e s f bill
	 */
	public void setLQty(long lQty);

	/**
	 * Returns the m qty of this e s f bill.
	 *
	 * @return the m qty of this e s f bill
	 */
	public long getMQty();

	/**
	 * Sets the m qty of this e s f bill.
	 *
	 * @param mQty the m qty of this e s f bill
	 */
	public void setMQty(long mQty);

	/**
	 * Returns the s qty of this e s f bill.
	 *
	 * @return the s qty of this e s f bill
	 */
	public long getSQty();

	/**
	 * Sets the s qty of this e s f bill.
	 *
	 * @param sQty the s qty of this e s f bill
	 */
	public void setSQty(long sQty);

	/**
	 * Returns the xs qty of this e s f bill.
	 *
	 * @return the xs qty of this e s f bill
	 */
	public long getXsQty();

	/**
	 * Sets the xs qty of this e s f bill.
	 *
	 * @param xsQty the xs qty of this e s f bill
	 */
	public void setXsQty(long xsQty);

	/**
	 * Returns the xxs qty of this e s f bill.
	 *
	 * @return the xxs qty of this e s f bill
	 */
	public long getXxsQty();

	/**
	 * Sets the xxs qty of this e s f bill.
	 *
	 * @param xxsQty the xxs qty of this e s f bill
	 */
	public void setXxsQty(long xxsQty);

	/**
	 * Returns the other qty of this e s f bill.
	 *
	 * @return the other qty of this e s f bill
	 */
	public long getOtherQty();

	/**
	 * Sets the other qty of this e s f bill.
	 *
	 * @param otherQty the other qty of this e s f bill
	 */
	public void setOtherQty(long otherQty);

	/**
	 * Returns the total qty of this e s f bill.
	 *
	 * @return the total qty of this e s f bill
	 */
	public long getTotalQty();

	/**
	 * Sets the total qty of this e s f bill.
	 *
	 * @param totalQty the total qty of this e s f bill
	 */
	public void setTotalQty(long totalQty);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFBill esfBill);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFBill> toCacheModel();

	@Override
	public ESFBill toEscapedModel();

	@Override
	public ESFBill toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}