/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFUser service. Represents a row in the &quot;ESFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFUserImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFUser
 * @see it.ethica.esf.model.impl.ESFUserImpl
 * @see it.ethica.esf.model.impl.ESFUserModelImpl
 * @generated
 */
public interface ESFUserModel extends BaseModel<ESFUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f user model instance should use the {@link ESFUser} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f user.
	 *
	 * @return the primary key of this e s f user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f user.
	 *
	 * @param primaryKey the primary key of this e s f user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f user.
	 *
	 * @return the uuid of this e s f user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f user.
	 *
	 * @param uuid the uuid of this e s f user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf user ID of this e s f user.
	 *
	 * @return the esf user ID of this e s f user
	 */
	public long getEsfUserId();

	/**
	 * Sets the esf user ID of this e s f user.
	 *
	 * @param esfUserId the esf user ID of this e s f user
	 */
	public void setEsfUserId(long esfUserId);

	/**
	 * Returns the esf user uuid of this e s f user.
	 *
	 * @return the esf user uuid of this e s f user
	 * @throws SystemException if a system exception occurred
	 */
	public String getEsfUserUuid() throws SystemException;

	/**
	 * Sets the esf user uuid of this e s f user.
	 *
	 * @param esfUserUuid the esf user uuid of this e s f user
	 */
	public void setEsfUserUuid(String esfUserUuid);

	/**
	 * Returns the code of this e s f user.
	 *
	 * @return the code of this e s f user
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f user.
	 *
	 * @param code the code of this e s f user
	 */
	public void setCode(String code);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFUser esfUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFUser> toCacheModel();

	@Override
	public ESFUser toEscapedModel();

	@Override
	public ESFUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}