/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.renewal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera;
import it.ethica.esf.renewal.model.VW_ESFListaIncarichiTesseraModel;
import it.ethica.esf.renewal.service.persistence.VW_ESFListaIncarichiTesseraPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VW_ESFListaIncarichiTessera service. Represents a row in the &quot;vw_listaincarichitessera&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.renewal.model.VW_ESFListaIncarichiTesseraModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VW_ESFListaIncarichiTesseraImpl}.
 * </p>
 *
 * @author Ethica
 * @see VW_ESFListaIncarichiTesseraImpl
 * @see it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera
 * @see it.ethica.esf.renewal.model.VW_ESFListaIncarichiTesseraModel
 * @generated
 */
public class VW_ESFListaIncarichiTesseraModelImpl extends BaseModelImpl<VW_ESFListaIncarichiTessera>
	implements VW_ESFListaIncarichiTesseraModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v w_ e s f lista incarichi tessera model instance should use the {@link it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera} interface instead.
	 */
	public static final String TABLE_NAME = "vw_listaincarichitessera";
	public static final Object[][] TABLE_COLUMNS = {
			{ "AnniPrecedenti", Types.INTEGER },
			{ "AnnoFineIncarico", Types.INTEGER },
			{ "AnnoInizioIncarico", Types.INTEGER },
			{ "AnnoCorrente", Types.INTEGER },
			{ "NomeRuolo", Types.VARCHAR },
			{ "endDate", Types.TIMESTAMP },
			{ "startDate", Types.TIMESTAMP },
			{ "esfUserId", Types.BIGINT },
			{ "esfOrganizationId", Types.BIGINT },
			{ "lastName", Types.VARCHAR },
			{ "firstName", Types.VARCHAR },
			{ "CodiceTessera", Types.VARCHAR },
			{ "DataTesseramento", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table vw_listaincarichitessera (AnniPrecedenti INTEGER not null,AnnoFineIncarico INTEGER not null,AnnoInizioIncarico INTEGER not null,AnnoCorrente INTEGER not null,NomeRuolo VARCHAR(75) not null,endDate DATE null,startDate DATE not null,esfUserId LONG not null,esfOrganizationId LONG not null,lastName VARCHAR(75) not null,firstName VARCHAR(75) not null,CodiceTessera VARCHAR(75) null,DataTesseramento DATE null,primary key (AnniPrecedenti, AnnoFineIncarico, AnnoInizioIncarico, AnnoCorrente, NomeRuolo, startDate, esfUserId, esfOrganizationId, lastName, firstName))";
	public static final String TABLE_SQL_DROP = "drop table vw_listaincarichitessera";
	public static final String ORDER_BY_JPQL = " ORDER BY vw_esfListaIncarichiTessera.endDate ASC, vw_esfListaIncarichiTessera.id.esfUserId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vw_listaincarichitessera.endDate ASC, vw_listaincarichitessera.esfUserId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera"),
			true);
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 1L;
	public static long ENDDATE_COLUMN_BITMASK = 2L;
	public static long ESFUSERID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera"));

	public VW_ESFListaIncarichiTesseraModelImpl() {
	}

	@Override
	public VW_ESFListaIncarichiTesseraPK getPrimaryKey() {
		return new VW_ESFListaIncarichiTesseraPK(_AnniPrecedenti,
			_AnnoFineIncarico, _AnnoInizioIncarico, _AnnoCorrente, _NomeRuolo,
			_startDate, _esfUserId, _esfOrganizationId, _lastName, _firstName);
	}

	@Override
	public void setPrimaryKey(VW_ESFListaIncarichiTesseraPK primaryKey) {
		setAnniPrecedenti(primaryKey.AnniPrecedenti);
		setAnnoFineIncarico(primaryKey.AnnoFineIncarico);
		setAnnoInizioIncarico(primaryKey.AnnoInizioIncarico);
		setAnnoCorrente(primaryKey.AnnoCorrente);
		setNomeRuolo(primaryKey.NomeRuolo);
		setStartDate(primaryKey.startDate);
		setEsfUserId(primaryKey.esfUserId);
		setEsfOrganizationId(primaryKey.esfOrganizationId);
		setLastName(primaryKey.lastName);
		setFirstName(primaryKey.firstName);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new VW_ESFListaIncarichiTesseraPK(_AnniPrecedenti,
			_AnnoFineIncarico, _AnnoInizioIncarico, _AnnoCorrente, _NomeRuolo,
			_startDate, _esfUserId, _esfOrganizationId, _lastName, _firstName);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((VW_ESFListaIncarichiTesseraPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return VW_ESFListaIncarichiTessera.class;
	}

	@Override
	public String getModelClassName() {
		return VW_ESFListaIncarichiTessera.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("AnniPrecedenti", getAnniPrecedenti());
		attributes.put("AnnoFineIncarico", getAnnoFineIncarico());
		attributes.put("AnnoInizioIncarico", getAnnoInizioIncarico());
		attributes.put("AnnoCorrente", getAnnoCorrente());
		attributes.put("NomeRuolo", getNomeRuolo());
		attributes.put("endDate", getEndDate());
		attributes.put("startDate", getStartDate());
		attributes.put("esfUserId", getEsfUserId());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("lastName", getLastName());
		attributes.put("firstName", getFirstName());
		attributes.put("CodiceTessera", getCodiceTessera());
		attributes.put("DataTesseramento", getDataTesseramento());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer AnniPrecedenti = (Integer)attributes.get("AnniPrecedenti");

		if (AnniPrecedenti != null) {
			setAnniPrecedenti(AnniPrecedenti);
		}

		Integer AnnoFineIncarico = (Integer)attributes.get("AnnoFineIncarico");

		if (AnnoFineIncarico != null) {
			setAnnoFineIncarico(AnnoFineIncarico);
		}

		Integer AnnoInizioIncarico = (Integer)attributes.get(
				"AnnoInizioIncarico");

		if (AnnoInizioIncarico != null) {
			setAnnoInizioIncarico(AnnoInizioIncarico);
		}

		Integer AnnoCorrente = (Integer)attributes.get("AnnoCorrente");

		if (AnnoCorrente != null) {
			setAnnoCorrente(AnnoCorrente);
		}

		String NomeRuolo = (String)attributes.get("NomeRuolo");

		if (NomeRuolo != null) {
			setNomeRuolo(NomeRuolo);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Long esfUserId = (Long)attributes.get("esfUserId");

		if (esfUserId != null) {
			setEsfUserId(esfUserId);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		String lastName = (String)attributes.get("lastName");

		if (lastName != null) {
			setLastName(lastName);
		}

		String firstName = (String)attributes.get("firstName");

		if (firstName != null) {
			setFirstName(firstName);
		}

		String CodiceTessera = (String)attributes.get("CodiceTessera");

		if (CodiceTessera != null) {
			setCodiceTessera(CodiceTessera);
		}

		Date DataTesseramento = (Date)attributes.get("DataTesseramento");

		if (DataTesseramento != null) {
			setDataTesseramento(DataTesseramento);
		}
	}

	@Override
	public int getAnniPrecedenti() {
		return _AnniPrecedenti;
	}

	@Override
	public void setAnniPrecedenti(int AnniPrecedenti) {
		_AnniPrecedenti = AnniPrecedenti;
	}

	@Override
	public int getAnnoFineIncarico() {
		return _AnnoFineIncarico;
	}

	@Override
	public void setAnnoFineIncarico(int AnnoFineIncarico) {
		_AnnoFineIncarico = AnnoFineIncarico;
	}

	@Override
	public int getAnnoInizioIncarico() {
		return _AnnoInizioIncarico;
	}

	@Override
	public void setAnnoInizioIncarico(int AnnoInizioIncarico) {
		_AnnoInizioIncarico = AnnoInizioIncarico;
	}

	@Override
	public int getAnnoCorrente() {
		return _AnnoCorrente;
	}

	@Override
	public void setAnnoCorrente(int AnnoCorrente) {
		_AnnoCorrente = AnnoCorrente;
	}

	@Override
	public String getNomeRuolo() {
		if (_NomeRuolo == null) {
			return StringPool.BLANK;
		}
		else {
			return _NomeRuolo;
		}
	}

	@Override
	public void setNomeRuolo(String NomeRuolo) {
		_NomeRuolo = NomeRuolo;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_columnBitmask = -1L;

		_endDate = endDate;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public long getEsfUserId() {
		return _esfUserId;
	}

	@Override
	public void setEsfUserId(long esfUserId) {
		_columnBitmask = -1L;

		_esfUserId = esfUserId;
	}

	@Override
	public String getEsfUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getEsfUserId(), "uuid", _esfUserUuid);
	}

	@Override
	public void setEsfUserUuid(String esfUserUuid) {
		_esfUserUuid = esfUserUuid;
	}

	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_columnBitmask |= ESFORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalEsfOrganizationId) {
			_setOriginalEsfOrganizationId = true;

			_originalEsfOrganizationId = _esfOrganizationId;
		}

		_esfOrganizationId = esfOrganizationId;
	}

	public long getOriginalEsfOrganizationId() {
		return _originalEsfOrganizationId;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@Override
	public String getCodiceTessera() {
		if (_CodiceTessera == null) {
			return StringPool.BLANK;
		}
		else {
			return _CodiceTessera;
		}
	}

	@Override
	public void setCodiceTessera(String CodiceTessera) {
		_CodiceTessera = CodiceTessera;
	}

	@Override
	public Date getDataTesseramento() {
		return _DataTesseramento;
	}

	@Override
	public void setDataTesseramento(Date DataTesseramento) {
		_DataTesseramento = DataTesseramento;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public VW_ESFListaIncarichiTessera toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VW_ESFListaIncarichiTessera)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VW_ESFListaIncarichiTesseraImpl vw_esfListaIncarichiTesseraImpl = new VW_ESFListaIncarichiTesseraImpl();

		vw_esfListaIncarichiTesseraImpl.setAnniPrecedenti(getAnniPrecedenti());
		vw_esfListaIncarichiTesseraImpl.setAnnoFineIncarico(getAnnoFineIncarico());
		vw_esfListaIncarichiTesseraImpl.setAnnoInizioIncarico(getAnnoInizioIncarico());
		vw_esfListaIncarichiTesseraImpl.setAnnoCorrente(getAnnoCorrente());
		vw_esfListaIncarichiTesseraImpl.setNomeRuolo(getNomeRuolo());
		vw_esfListaIncarichiTesseraImpl.setEndDate(getEndDate());
		vw_esfListaIncarichiTesseraImpl.setStartDate(getStartDate());
		vw_esfListaIncarichiTesseraImpl.setEsfUserId(getEsfUserId());
		vw_esfListaIncarichiTesseraImpl.setEsfOrganizationId(getEsfOrganizationId());
		vw_esfListaIncarichiTesseraImpl.setLastName(getLastName());
		vw_esfListaIncarichiTesseraImpl.setFirstName(getFirstName());
		vw_esfListaIncarichiTesseraImpl.setCodiceTessera(getCodiceTessera());
		vw_esfListaIncarichiTesseraImpl.setDataTesseramento(getDataTesseramento());

		vw_esfListaIncarichiTesseraImpl.resetOriginalValues();

		return vw_esfListaIncarichiTesseraImpl;
	}

	@Override
	public int compareTo(
		VW_ESFListaIncarichiTessera vw_esfListaIncarichiTessera) {
		int value = 0;

		value = DateUtil.compareTo(getEndDate(),
				vw_esfListaIncarichiTessera.getEndDate());

		if (value != 0) {
			return value;
		}

		if (getEsfUserId() < vw_esfListaIncarichiTessera.getEsfUserId()) {
			value = -1;
		}
		else if (getEsfUserId() > vw_esfListaIncarichiTessera.getEsfUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VW_ESFListaIncarichiTessera)) {
			return false;
		}

		VW_ESFListaIncarichiTessera vw_esfListaIncarichiTessera = (VW_ESFListaIncarichiTessera)obj;

		VW_ESFListaIncarichiTesseraPK primaryKey = vw_esfListaIncarichiTessera.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		VW_ESFListaIncarichiTesseraModelImpl vw_esfListaIncarichiTesseraModelImpl =
			this;

		vw_esfListaIncarichiTesseraModelImpl._originalEsfOrganizationId = vw_esfListaIncarichiTesseraModelImpl._esfOrganizationId;

		vw_esfListaIncarichiTesseraModelImpl._setOriginalEsfOrganizationId = false;

		vw_esfListaIncarichiTesseraModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VW_ESFListaIncarichiTessera> toCacheModel() {
		VW_ESFListaIncarichiTesseraCacheModel vw_esfListaIncarichiTesseraCacheModel =
			new VW_ESFListaIncarichiTesseraCacheModel();

		vw_esfListaIncarichiTesseraCacheModel.AnniPrecedenti = getAnniPrecedenti();

		vw_esfListaIncarichiTesseraCacheModel.AnnoFineIncarico = getAnnoFineIncarico();

		vw_esfListaIncarichiTesseraCacheModel.AnnoInizioIncarico = getAnnoInizioIncarico();

		vw_esfListaIncarichiTesseraCacheModel.AnnoCorrente = getAnnoCorrente();

		vw_esfListaIncarichiTesseraCacheModel.NomeRuolo = getNomeRuolo();

		String NomeRuolo = vw_esfListaIncarichiTesseraCacheModel.NomeRuolo;

		if ((NomeRuolo != null) && (NomeRuolo.length() == 0)) {
			vw_esfListaIncarichiTesseraCacheModel.NomeRuolo = null;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			vw_esfListaIncarichiTesseraCacheModel.endDate = endDate.getTime();
		}
		else {
			vw_esfListaIncarichiTesseraCacheModel.endDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			vw_esfListaIncarichiTesseraCacheModel.startDate = startDate.getTime();
		}
		else {
			vw_esfListaIncarichiTesseraCacheModel.startDate = Long.MIN_VALUE;
		}

		vw_esfListaIncarichiTesseraCacheModel.esfUserId = getEsfUserId();

		vw_esfListaIncarichiTesseraCacheModel.esfOrganizationId = getEsfOrganizationId();

		vw_esfListaIncarichiTesseraCacheModel.lastName = getLastName();

		String lastName = vw_esfListaIncarichiTesseraCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			vw_esfListaIncarichiTesseraCacheModel.lastName = null;
		}

		vw_esfListaIncarichiTesseraCacheModel.firstName = getFirstName();

		String firstName = vw_esfListaIncarichiTesseraCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			vw_esfListaIncarichiTesseraCacheModel.firstName = null;
		}

		vw_esfListaIncarichiTesseraCacheModel.CodiceTessera = getCodiceTessera();

		String CodiceTessera = vw_esfListaIncarichiTesseraCacheModel.CodiceTessera;

		if ((CodiceTessera != null) && (CodiceTessera.length() == 0)) {
			vw_esfListaIncarichiTesseraCacheModel.CodiceTessera = null;
		}

		Date DataTesseramento = getDataTesseramento();

		if (DataTesseramento != null) {
			vw_esfListaIncarichiTesseraCacheModel.DataTesseramento = DataTesseramento.getTime();
		}
		else {
			vw_esfListaIncarichiTesseraCacheModel.DataTesseramento = Long.MIN_VALUE;
		}

		return vw_esfListaIncarichiTesseraCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{AnniPrecedenti=");
		sb.append(getAnniPrecedenti());
		sb.append(", AnnoFineIncarico=");
		sb.append(getAnnoFineIncarico());
		sb.append(", AnnoInizioIncarico=");
		sb.append(getAnnoInizioIncarico());
		sb.append(", AnnoCorrente=");
		sb.append(getAnnoCorrente());
		sb.append(", NomeRuolo=");
		sb.append(getNomeRuolo());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", esfUserId=");
		sb.append(getEsfUserId());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append(", CodiceTessera=");
		sb.append(getCodiceTessera());
		sb.append(", DataTesseramento=");
		sb.append(getDataTesseramento());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.renewal.model.VW_ESFListaIncarichiTessera");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>AnniPrecedenti</column-name><column-value><![CDATA[");
		sb.append(getAnniPrecedenti());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoFineIncarico</column-name><column-value><![CDATA[");
		sb.append(getAnnoFineIncarico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoInizioIncarico</column-name><column-value><![CDATA[");
		sb.append(getAnnoInizioIncarico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AnnoCorrente</column-name><column-value><![CDATA[");
		sb.append(getAnnoCorrente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NomeRuolo</column-name><column-value><![CDATA[");
		sb.append(getNomeRuolo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfUserId</column-name><column-value><![CDATA[");
		sb.append(getEsfUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CodiceTessera</column-name><column-value><![CDATA[");
		sb.append(getCodiceTessera());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DataTesseramento</column-name><column-value><![CDATA[");
		sb.append(getDataTesseramento());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VW_ESFListaIncarichiTessera.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VW_ESFListaIncarichiTessera.class
		};
	private int _AnniPrecedenti;
	private int _AnnoFineIncarico;
	private int _AnnoInizioIncarico;
	private int _AnnoCorrente;
	private String _NomeRuolo;
	private Date _endDate;
	private Date _startDate;
	private long _esfUserId;
	private String _esfUserUuid;
	private long _esfOrganizationId;
	private long _originalEsfOrganizationId;
	private boolean _setOriginalEsfOrganizationId;
	private String _lastName;
	private String _firstName;
	private String _CodiceTessera;
	private Date _DataTesseramento;
	private long _columnBitmask;
	private VW_ESFListaIncarichiTessera _escapedModel;
}