/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFOrganization service. Represents a row in the &quot;ESF_ESFOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.model.impl.ESFOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.model.impl.ESFOrganizationImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrganization
 * @see it.ethica.esf.model.impl.ESFOrganizationImpl
 * @see it.ethica.esf.model.impl.ESFOrganizationModelImpl
 * @generated
 */
public interface ESFOrganizationModel extends BaseModel<ESFOrganization> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f organization model instance should use the {@link ESFOrganization} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f organization.
	 *
	 * @return the primary key of this e s f organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f organization.
	 *
	 * @param primaryKey the primary key of this e s f organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this e s f organization.
	 *
	 * @return the uuid of this e s f organization
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e s f organization.
	 *
	 * @param uuid the uuid of this e s f organization
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the esf organization ID of this e s f organization.
	 *
	 * @return the esf organization ID of this e s f organization
	 */
	public long getEsfOrganizationId();

	/**
	 * Sets the esf organization ID of this e s f organization.
	 *
	 * @param esfOrganizationId the esf organization ID of this e s f organization
	 */
	public void setEsfOrganizationId(long esfOrganizationId);

	/**
	 * Returns the code of this e s f organization.
	 *
	 * @return the code of this e s f organization
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this e s f organization.
	 *
	 * @param code the code of this e s f organization
	 */
	public void setCode(String code);

	/**
	 * Returns the vat of this e s f organization.
	 *
	 * @return the vat of this e s f organization
	 */
	@AutoEscape
	public String getVat();

	/**
	 * Sets the vat of this e s f organization.
	 *
	 * @param vat the vat of this e s f organization
	 */
	public void setVat(String vat);

	/**
	 * Returns the fiscal code of this e s f organization.
	 *
	 * @return the fiscal code of this e s f organization
	 */
	@AutoEscape
	public String getFiscalCode();

	/**
	 * Sets the fiscal code of this e s f organization.
	 *
	 * @param fiscalCode the fiscal code of this e s f organization
	 */
	public void setFiscalCode(String fiscalCode);

	/**
	 * Returns the establishment date of this e s f organization.
	 *
	 * @return the establishment date of this e s f organization
	 */
	public Date getEstablishmentDate();

	/**
	 * Sets the establishment date of this e s f organization.
	 *
	 * @param establishmentDate the establishment date of this e s f organization
	 */
	public void setEstablishmentDate(Date establishmentDate);

	/**
	 * Returns the closure date of this e s f organization.
	 *
	 * @return the closure date of this e s f organization
	 */
	public Date getClosureDate();

	/**
	 * Sets the closure date of this e s f organization.
	 *
	 * @param closureDate the closure date of this e s f organization
	 */
	public void setClosureDate(Date closureDate);

	/**
	 * Returns the group ID of this e s f organization.
	 *
	 * @return the group ID of this e s f organization
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e s f organization.
	 *
	 * @param groupId the group ID of this e s f organization
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFOrganization esfOrganization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFOrganization> toCacheModel();

	@Override
	public ESFOrganization toEscapedModel();

	@Override
	public ESFOrganization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}