/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import it.ethica.esf.model.ESFEntityState;
import it.ethica.esf.model.ESFEntityStateModel;
import it.ethica.esf.service.persistence.ESFEntityStatePK;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFEntityState service. Represents a row in the &quot;ESF_ESFEntityState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFEntityStateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFEntityStateImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFEntityStateImpl
 * @see it.ethica.esf.model.ESFEntityState
 * @see it.ethica.esf.model.ESFEntityStateModel
 * @generated
 */
public class ESFEntityStateModelImpl extends BaseModelImpl<ESFEntityState>
	implements ESFEntityStateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f entity state model instance should use the {@link it.ethica.esf.model.ESFEntityState} interface instead.
	 */
	public static final String TABLE_NAME = "ESF_ESFEntityState";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "className", Types.VARCHAR },
			{ "classPk", Types.BIGINT },
			{ "stateId", Types.BIGINT },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ESF_ESFEntityState (uuid_ VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,className VARCHAR(75) not null,classPk LONG not null,stateId LONG not null,startDate DATE null,endDate DATE null,primary key (className, classPk, stateId))";
	public static final String TABLE_SQL_DROP = "drop table ESF_ESFEntityState";
	public static final String ORDER_BY_JPQL = " ORDER BY esfEntityState.id.className ASC, esfEntityState.id.classPk ASC, esfEntityState.id.stateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESF_ESFEntityState.className ASC, ESF_ESFEntityState.classPk ASC, ESF_ESFEntityState.stateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFEntityState"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFEntityState"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFEntityState"),
			true);
	public static long CLASSNAME_COLUMN_BITMASK = 1L;
	public static long CLASSPK_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static long STATEID_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFEntityState"));

	public ESFEntityStateModelImpl() {
	}

	@Override
	public ESFEntityStatePK getPrimaryKey() {
		return new ESFEntityStatePK(_className, _classPk, _stateId);
	}

	@Override
	public void setPrimaryKey(ESFEntityStatePK primaryKey) {
		setClassName(primaryKey.className);
		setClassPk(primaryKey.classPk);
		setStateId(primaryKey.stateId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ESFEntityStatePK(_className, _classPk, _stateId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ESFEntityStatePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ESFEntityState.class;
	}

	@Override
	public String getModelClassName() {
		return ESFEntityState.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("className", getClassName());
		attributes.put("classPk", getClassPk());
		attributes.put("stateId", getStateId());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String className = (String)attributes.get("className");

		if (className != null) {
			setClassName(className);
		}

		Long classPk = (Long)attributes.get("classPk");

		if (classPk != null) {
			setClassPk(classPk);
		}

		Long stateId = (Long)attributes.get("stateId");

		if (stateId != null) {
			setStateId(stateId);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_columnBitmask |= CLASSNAME_COLUMN_BITMASK;

		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	@Override
	public long getClassPk() {
		return _classPk;
	}

	@Override
	public void setClassPk(long classPk) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPk) {
			_setOriginalClassPk = true;

			_originalClassPk = _classPk;
		}

		_classPk = classPk;
	}

	public long getOriginalClassPk() {
		return _originalClassPk;
	}

	@Override
	public long getStateId() {
		return _stateId;
	}

	@Override
	public void setStateId(long stateId) {
		_stateId = stateId;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ESFEntityState.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ESFEntityState toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFEntityState)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFEntityStateImpl esfEntityStateImpl = new ESFEntityStateImpl();

		esfEntityStateImpl.setUuid(getUuid());
		esfEntityStateImpl.setGroupId(getGroupId());
		esfEntityStateImpl.setCompanyId(getCompanyId());
		esfEntityStateImpl.setUserId(getUserId());
		esfEntityStateImpl.setUserName(getUserName());
		esfEntityStateImpl.setCreateDate(getCreateDate());
		esfEntityStateImpl.setModifiedDate(getModifiedDate());
		esfEntityStateImpl.setClassName(getClassName());
		esfEntityStateImpl.setClassPk(getClassPk());
		esfEntityStateImpl.setStateId(getStateId());
		esfEntityStateImpl.setStartDate(getStartDate());
		esfEntityStateImpl.setEndDate(getEndDate());

		esfEntityStateImpl.resetOriginalValues();

		return esfEntityStateImpl;
	}

	@Override
	public int compareTo(ESFEntityState esfEntityState) {
		ESFEntityStatePK primaryKey = esfEntityState.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFEntityState)) {
			return false;
		}

		ESFEntityState esfEntityState = (ESFEntityState)obj;

		ESFEntityStatePK primaryKey = esfEntityState.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ESFEntityStateModelImpl esfEntityStateModelImpl = this;

		esfEntityStateModelImpl._originalUuid = esfEntityStateModelImpl._uuid;

		esfEntityStateModelImpl._originalGroupId = esfEntityStateModelImpl._groupId;

		esfEntityStateModelImpl._setOriginalGroupId = false;

		esfEntityStateModelImpl._originalCompanyId = esfEntityStateModelImpl._companyId;

		esfEntityStateModelImpl._setOriginalCompanyId = false;

		esfEntityStateModelImpl._originalClassName = esfEntityStateModelImpl._className;

		esfEntityStateModelImpl._originalClassPk = esfEntityStateModelImpl._classPk;

		esfEntityStateModelImpl._setOriginalClassPk = false;

		esfEntityStateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFEntityState> toCacheModel() {
		ESFEntityStateCacheModel esfEntityStateCacheModel = new ESFEntityStateCacheModel();

		esfEntityStateCacheModel.uuid = getUuid();

		String uuid = esfEntityStateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfEntityStateCacheModel.uuid = null;
		}

		esfEntityStateCacheModel.groupId = getGroupId();

		esfEntityStateCacheModel.companyId = getCompanyId();

		esfEntityStateCacheModel.userId = getUserId();

		esfEntityStateCacheModel.userName = getUserName();

		String userName = esfEntityStateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfEntityStateCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfEntityStateCacheModel.createDate = createDate.getTime();
		}
		else {
			esfEntityStateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfEntityStateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfEntityStateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		esfEntityStateCacheModel.className = getClassName();

		String className = esfEntityStateCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			esfEntityStateCacheModel.className = null;
		}

		esfEntityStateCacheModel.classPk = getClassPk();

		esfEntityStateCacheModel.stateId = getStateId();

		Date startDate = getStartDate();

		if (startDate != null) {
			esfEntityStateCacheModel.startDate = startDate.getTime();
		}
		else {
			esfEntityStateCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			esfEntityStateCacheModel.endDate = endDate.getTime();
		}
		else {
			esfEntityStateCacheModel.endDate = Long.MIN_VALUE;
		}

		return esfEntityStateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", classPk=");
		sb.append(getClassPk());
		sb.append(", stateId=");
		sb.append(getStateId());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFEntityState");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPk</column-name><column-value><![CDATA[");
		sb.append(getClassPk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stateId</column-name><column-value><![CDATA[");
		sb.append(getStateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFEntityState.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFEntityState.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _className;
	private String _originalClassName;
	private long _classPk;
	private long _originalClassPk;
	private boolean _setOriginalClassPk;
	private long _stateId;
	private Date _startDate;
	private Date _endDate;
	private long _columnBitmask;
	private ESFEntityState _escapedModel;
}