/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.renewal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFRenewalCompany service. Represents a row in the &quot;ESFRenewalCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.ethica.esf.renewal.model.impl.ESFRenewalCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.ethica.esf.renewal.model.impl.ESFRenewalCompanyImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFRenewalCompany
 * @see it.ethica.esf.renewal.model.impl.ESFRenewalCompanyImpl
 * @see it.ethica.esf.renewal.model.impl.ESFRenewalCompanyModelImpl
 * @generated
 */
public interface ESFRenewalCompanyModel extends BaseModel<ESFRenewalCompany> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f renewal company model instance should use the {@link ESFRenewalCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f renewal company.
	 *
	 * @return the primary key of this e s f renewal company
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f renewal company.
	 *
	 * @param primaryKey the primary key of this e s f renewal company
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf renewal company ID of this e s f renewal company.
	 *
	 * @return the esf renewal company ID of this e s f renewal company
	 */
	public long getEsfRenewalCompanyId();

	/**
	 * Sets the esf renewal company ID of this e s f renewal company.
	 *
	 * @param esfRenewalCompanyId the esf renewal company ID of this e s f renewal company
	 */
	public void setEsfRenewalCompanyId(long esfRenewalCompanyId);

	/**
	 * Returns the user ID of this e s f renewal company.
	 *
	 * @return the user ID of this e s f renewal company
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this e s f renewal company.
	 *
	 * @param userId the user ID of this e s f renewal company
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e s f renewal company.
	 *
	 * @return the user uuid of this e s f renewal company
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e s f renewal company.
	 *
	 * @param userUuid the user uuid of this e s f renewal company
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the esf organization ID of this e s f renewal company.
	 *
	 * @return the esf organization ID of this e s f renewal company
	 */
	public long getEsfOrganizationId();

	/**
	 * Sets the esf organization ID of this e s f renewal company.
	 *
	 * @param esfOrganizationId the esf organization ID of this e s f renewal company
	 */
	public void setEsfOrganizationId(long esfOrganizationId);

	/**
	 * Returns the cards number of this e s f renewal company.
	 *
	 * @return the cards number of this e s f renewal company
	 */
	public int getCardsNumber();

	/**
	 * Sets the cards number of this e s f renewal company.
	 *
	 * @param cardsNumber the cards number of this e s f renewal company
	 */
	public void setCardsNumber(int cardsNumber);

	/**
	 * Returns the year of this e s f renewal company.
	 *
	 * @return the year of this e s f renewal company
	 */
	public int getYear();

	/**
	 * Sets the year of this e s f renewal company.
	 *
	 * @param year the year of this e s f renewal company
	 */
	public void setYear(int year);

	/**
	 * Returns the date of this e s f renewal company.
	 *
	 * @return the date of this e s f renewal company
	 */
	public Date getDate();

	/**
	 * Sets the date of this e s f renewal company.
	 *
	 * @param date the date of this e s f renewal company
	 */
	public void setDate(Date date);

	/**
	 * Returns the payment type of this e s f renewal company.
	 *
	 * @return the payment type of this e s f renewal company
	 */
	public int getPaymentType();

	/**
	 * Sets the payment type of this e s f renewal company.
	 *
	 * @param paymentType the payment type of this e s f renewal company
	 */
	public void setPaymentType(int paymentType);

	/**
	 * Returns the status of this e s f renewal company.
	 *
	 * @return the status of this e s f renewal company
	 */
	public int getStatus();

	/**
	 * Sets the status of this e s f renewal company.
	 *
	 * @param status the status of this e s f renewal company
	 */
	public void setStatus(int status);

	/**
	 * Returns the amount of this e s f renewal company.
	 *
	 * @return the amount of this e s f renewal company
	 */
	public double getAmount();

	/**
	 * Sets the amount of this e s f renewal company.
	 *
	 * @param amount the amount of this e s f renewal company
	 */
	public void setAmount(double amount);

	/**
	 * Returns the info of this e s f renewal company.
	 *
	 * @return the info of this e s f renewal company
	 */
	@AutoEscape
	public String getInfo();

	/**
	 * Sets the info of this e s f renewal company.
	 *
	 * @param info the info of this e s f renewal company
	 */
	public void setInfo(String info);

	/**
	 * Returns the accountholder of this e s f renewal company.
	 *
	 * @return the accountholder of this e s f renewal company
	 */
	@AutoEscape
	public String getAccountholder();

	/**
	 * Sets the accountholder of this e s f renewal company.
	 *
	 * @param accountholder the accountholder of this e s f renewal company
	 */
	public void setAccountholder(String accountholder);

	/**
	 * Returns the payment date of this e s f renewal company.
	 *
	 * @return the payment date of this e s f renewal company
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this e s f renewal company.
	 *
	 * @param paymentDate the payment date of this e s f renewal company
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the integration amount of this e s f renewal company.
	 *
	 * @return the integration amount of this e s f renewal company
	 */
	public double getIntegrationAmount();

	/**
	 * Sets the integration amount of this e s f renewal company.
	 *
	 * @param integrationAmount the integration amount of this e s f renewal company
	 */
	public void setIntegrationAmount(double integrationAmount);

	/**
	 * Returns the integration date of this e s f renewal company.
	 *
	 * @return the integration date of this e s f renewal company
	 */
	public Date getIntegrationDate();

	/**
	 * Sets the integration date of this e s f renewal company.
	 *
	 * @param integrationDate the integration date of this e s f renewal company
	 */
	public void setIntegrationDate(Date integrationDate);

	/**
	 * Returns the integration type of this e s f renewal company.
	 *
	 * @return the integration type of this e s f renewal company
	 */
	public int getIntegrationType();

	/**
	 * Sets the integration type of this e s f renewal company.
	 *
	 * @param integrationType the integration type of this e s f renewal company
	 */
	public void setIntegrationType(int integrationType);

	/**
	 * Returns the integration accountholder of this e s f renewal company.
	 *
	 * @return the integration accountholder of this e s f renewal company
	 */
	@AutoEscape
	public String getIntegrationAccountholder();

	/**
	 * Sets the integration accountholder of this e s f renewal company.
	 *
	 * @param integrationAccountholder the integration accountholder of this e s f renewal company
	 */
	public void setIntegrationAccountholder(String integrationAccountholder);

	/**
	 * Returns the join of this e s f renewal company.
	 *
	 * @return the join of this e s f renewal company
	 */
	public boolean getJoin();

	/**
	 * Returns <code>true</code> if this e s f renewal company is join.
	 *
	 * @return <code>true</code> if this e s f renewal company is join; <code>false</code> otherwise
	 */
	public boolean isJoin();

	/**
	 * Sets whether this e s f renewal company is join.
	 *
	 * @param join the join of this e s f renewal company
	 */
	public void setJoin(boolean join);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFRenewalCompany esfRenewalCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFRenewalCompany> toCacheModel();

	@Override
	public ESFRenewalCompany toEscapedModel();

	@Override
	public ESFRenewalCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}