/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.ethica.esf.model.City;
import it.ethica.esf.model.CityModel;
import it.ethica.esf.service.persistence.CityPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the City service. Represents a row in the &quot;City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.CityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CityImpl}.
 * </p>
 *
 * @author Ethica
 * @see CityImpl
 * @see it.ethica.esf.model.City
 * @see it.ethica.esf.model.CityModel
 * @generated
 */
public class CityModelImpl extends BaseModelImpl<City> implements CityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a city model instance should use the {@link it.ethica.esf.model.City} interface instead.
	 */
	public static final String TABLE_NAME = "City";
	public static final Object[][] TABLE_COLUMNS = {
			{ "idCity", Types.BIGINT },
			{ "idProvince", Types.VARCHAR },
			{ "idRegion", Types.VARCHAR },
			{ "idCountry", Types.VARCHAR },
			{ "zip", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "latitude", Types.DOUBLE },
			{ "longitude", Types.DOUBLE },
			{ "altitude", Types.DOUBLE },
			{ "website", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table City (idCity LONG not null,idProvince VARCHAR(75) not null,idRegion VARCHAR(75) not null,idCountry VARCHAR(75) not null,zip LONG,name VARCHAR(75) null,latitude DOUBLE,longitude DOUBLE,altitude DOUBLE,website VARCHAR(75) null,primary key (idCity, idProvince, idRegion, idCountry))";
	public static final String TABLE_SQL_DROP = "drop table City";
	public static final String ORDER_BY_JPQL = " ORDER BY city.id.idCity ASC, city.id.idProvince ASC, city.id.idRegion ASC, city.id.idCountry ASC";
	public static final String ORDER_BY_SQL = " ORDER BY City.idCity ASC, City.idProvince ASC, City.idRegion ASC, City.idCountry ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.City"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.City"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.City"),
			true);
	public static long IDCOUNTRY_COLUMN_BITMASK = 1L;
	public static long IDPROVINCE_COLUMN_BITMASK = 2L;
	public static long IDREGION_COLUMN_BITMASK = 4L;
	public static long IDCITY_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.City"));

	public CityModelImpl() {
	}

	@Override
	public CityPK getPrimaryKey() {
		return new CityPK(_idCity, _idProvince, _idRegion, _idCountry);
	}

	@Override
	public void setPrimaryKey(CityPK primaryKey) {
		setIdCity(primaryKey.idCity);
		setIdProvince(primaryKey.idProvince);
		setIdRegion(primaryKey.idRegion);
		setIdCountry(primaryKey.idCountry);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new CityPK(_idCity, _idProvince, _idRegion, _idCountry);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((CityPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return City.class;
	}

	@Override
	public String getModelClassName() {
		return City.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idCity", getIdCity());
		attributes.put("idProvince", getIdProvince());
		attributes.put("idRegion", getIdRegion());
		attributes.put("idCountry", getIdCountry());
		attributes.put("zip", getZip());
		attributes.put("name", getName());
		attributes.put("latitude", getLatitude());
		attributes.put("longitude", getLongitude());
		attributes.put("altitude", getAltitude());
		attributes.put("website", getWebsite());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idCity = (Long)attributes.get("idCity");

		if (idCity != null) {
			setIdCity(idCity);
		}

		String idProvince = (String)attributes.get("idProvince");

		if (idProvince != null) {
			setIdProvince(idProvince);
		}

		String idRegion = (String)attributes.get("idRegion");

		if (idRegion != null) {
			setIdRegion(idRegion);
		}

		String idCountry = (String)attributes.get("idCountry");

		if (idCountry != null) {
			setIdCountry(idCountry);
		}

		Long zip = (Long)attributes.get("zip");

		if (zip != null) {
			setZip(zip);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Double latitude = (Double)attributes.get("latitude");

		if (latitude != null) {
			setLatitude(latitude);
		}

		Double longitude = (Double)attributes.get("longitude");

		if (longitude != null) {
			setLongitude(longitude);
		}

		Double altitude = (Double)attributes.get("altitude");

		if (altitude != null) {
			setAltitude(altitude);
		}

		String website = (String)attributes.get("website");

		if (website != null) {
			setWebsite(website);
		}
	}

	@Override
	public long getIdCity() {
		return _idCity;
	}

	@Override
	public void setIdCity(long idCity) {
		_idCity = idCity;
	}

	@Override
	public String getIdProvince() {
		if (_idProvince == null) {
			return StringPool.BLANK;
		}
		else {
			return _idProvince;
		}
	}

	@Override
	public void setIdProvince(String idProvince) {
		_columnBitmask |= IDPROVINCE_COLUMN_BITMASK;

		if (_originalIdProvince == null) {
			_originalIdProvince = _idProvince;
		}

		_idProvince = idProvince;
	}

	public String getOriginalIdProvince() {
		return GetterUtil.getString(_originalIdProvince);
	}

	@Override
	public String getIdRegion() {
		if (_idRegion == null) {
			return StringPool.BLANK;
		}
		else {
			return _idRegion;
		}
	}

	@Override
	public void setIdRegion(String idRegion) {
		_columnBitmask |= IDREGION_COLUMN_BITMASK;

		if (_originalIdRegion == null) {
			_originalIdRegion = _idRegion;
		}

		_idRegion = idRegion;
	}

	public String getOriginalIdRegion() {
		return GetterUtil.getString(_originalIdRegion);
	}

	@Override
	public String getIdCountry() {
		if (_idCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _idCountry;
		}
	}

	@Override
	public void setIdCountry(String idCountry) {
		_columnBitmask |= IDCOUNTRY_COLUMN_BITMASK;

		if (_originalIdCountry == null) {
			_originalIdCountry = _idCountry;
		}

		_idCountry = idCountry;
	}

	public String getOriginalIdCountry() {
		return GetterUtil.getString(_originalIdCountry);
	}

	@Override
	public long getZip() {
		return _zip;
	}

	@Override
	public void setZip(long zip) {
		_zip = zip;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		_latitude = latitude;
	}

	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		_longitude = longitude;
	}

	@Override
	public double getAltitude() {
		return _altitude;
	}

	@Override
	public void setAltitude(double altitude) {
		_altitude = altitude;
	}

	@Override
	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	@Override
	public void setWebsite(String website) {
		_website = website;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public City toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (City)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CityImpl cityImpl = new CityImpl();

		cityImpl.setIdCity(getIdCity());
		cityImpl.setIdProvince(getIdProvince());
		cityImpl.setIdRegion(getIdRegion());
		cityImpl.setIdCountry(getIdCountry());
		cityImpl.setZip(getZip());
		cityImpl.setName(getName());
		cityImpl.setLatitude(getLatitude());
		cityImpl.setLongitude(getLongitude());
		cityImpl.setAltitude(getAltitude());
		cityImpl.setWebsite(getWebsite());

		cityImpl.resetOriginalValues();

		return cityImpl;
	}

	@Override
	public int compareTo(City city) {
		CityPK primaryKey = city.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof City)) {
			return false;
		}

		City city = (City)obj;

		CityPK primaryKey = city.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		CityModelImpl cityModelImpl = this;

		cityModelImpl._originalIdProvince = cityModelImpl._idProvince;

		cityModelImpl._originalIdRegion = cityModelImpl._idRegion;

		cityModelImpl._originalIdCountry = cityModelImpl._idCountry;

		cityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<City> toCacheModel() {
		CityCacheModel cityCacheModel = new CityCacheModel();

		cityCacheModel.idCity = getIdCity();

		cityCacheModel.idProvince = getIdProvince();

		String idProvince = cityCacheModel.idProvince;

		if ((idProvince != null) && (idProvince.length() == 0)) {
			cityCacheModel.idProvince = null;
		}

		cityCacheModel.idRegion = getIdRegion();

		String idRegion = cityCacheModel.idRegion;

		if ((idRegion != null) && (idRegion.length() == 0)) {
			cityCacheModel.idRegion = null;
		}

		cityCacheModel.idCountry = getIdCountry();

		String idCountry = cityCacheModel.idCountry;

		if ((idCountry != null) && (idCountry.length() == 0)) {
			cityCacheModel.idCountry = null;
		}

		cityCacheModel.zip = getZip();

		cityCacheModel.name = getName();

		String name = cityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cityCacheModel.name = null;
		}

		cityCacheModel.latitude = getLatitude();

		cityCacheModel.longitude = getLongitude();

		cityCacheModel.altitude = getAltitude();

		cityCacheModel.website = getWebsite();

		String website = cityCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			cityCacheModel.website = null;
		}

		return cityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{idCity=");
		sb.append(getIdCity());
		sb.append(", idProvince=");
		sb.append(getIdProvince());
		sb.append(", idRegion=");
		sb.append(getIdRegion());
		sb.append(", idCountry=");
		sb.append(getIdCountry());
		sb.append(", zip=");
		sb.append(getZip());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", latitude=");
		sb.append(getLatitude());
		sb.append(", longitude=");
		sb.append(getLongitude());
		sb.append(", altitude=");
		sb.append(getAltitude());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.City");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idCity</column-name><column-value><![CDATA[");
		sb.append(getIdCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idProvince</column-name><column-value><![CDATA[");
		sb.append(getIdProvince());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idRegion</column-name><column-value><![CDATA[");
		sb.append(getIdRegion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idCountry</column-name><column-value><![CDATA[");
		sb.append(getIdCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zip</column-name><column-value><![CDATA[");
		sb.append(getZip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>latitude</column-name><column-value><![CDATA[");
		sb.append(getLatitude());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>longitude</column-name><column-value><![CDATA[");
		sb.append(getLongitude());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>altitude</column-name><column-value><![CDATA[");
		sb.append(getAltitude());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = City.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { City.class };
	private long _idCity;
	private String _idProvince;
	private String _originalIdProvince;
	private String _idRegion;
	private String _originalIdRegion;
	private String _idCountry;
	private String _originalIdCountry;
	private long _zip;
	private String _name;
	private double _latitude;
	private double _longitude;
	private double _altitude;
	private String _website;
	private long _columnBitmask;
	private City _escapedModel;
}