/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ESFArticleDelivered service. Represents a row in the &quot;ESFArticleDelivered&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFArticleDeliveredModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFArticleDeliveredImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFArticleDelivered
 * @see com.ethica.esf.model.impl.ESFArticleDeliveredImpl
 * @see com.ethica.esf.model.impl.ESFArticleDeliveredModelImpl
 * @generated
 */
public interface ESFArticleDeliveredModel extends BaseModel<ESFArticleDelivered> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f article delivered model instance should use the {@link ESFArticleDelivered} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f article delivered.
	 *
	 * @return the primary key of this e s f article delivered
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f article delivered.
	 *
	 * @param primaryKey the primary key of this e s f article delivered
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf article delivered ID of this e s f article delivered.
	 *
	 * @return the esf article delivered ID of this e s f article delivered
	 */
	public long getEsfArticleDeliveredId();

	/**
	 * Sets the esf article delivered ID of this e s f article delivered.
	 *
	 * @param esfArticleDeliveredId the esf article delivered ID of this e s f article delivered
	 */
	public void setEsfArticleDeliveredId(long esfArticleDeliveredId);

	/**
	 * Returns the data of this e s f article delivered.
	 *
	 * @return the data of this e s f article delivered
	 */
	public Date getData();

	/**
	 * Sets the data of this e s f article delivered.
	 *
	 * @param data the data of this e s f article delivered
	 */
	public void setData(Date data);

	/**
	 * Returns the description of this e s f article delivered.
	 *
	 * @return the description of this e s f article delivered
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f article delivered.
	 *
	 * @param description the description of this e s f article delivered
	 */
	public void setDescription(String description);

	/**
	 * Returns the esf article ID of this e s f article delivered.
	 *
	 * @return the esf article ID of this e s f article delivered
	 */
	public long getEsfArticleId();

	/**
	 * Sets the esf article ID of this e s f article delivered.
	 *
	 * @param esfArticleId the esf article ID of this e s f article delivered
	 */
	public void setEsfArticleId(long esfArticleId);

	/**
	 * Returns the esf shooter ID of this e s f article delivered.
	 *
	 * @return the esf shooter ID of this e s f article delivered
	 */
	public long getEsfShooterId();

	/**
	 * Sets the esf shooter ID of this e s f article delivered.
	 *
	 * @param esfShooterId the esf shooter ID of this e s f article delivered
	 */
	public void setEsfShooterId(long esfShooterId);

	/**
	 * Returns the xxxl qty of this e s f article delivered.
	 *
	 * @return the xxxl qty of this e s f article delivered
	 */
	public long getXxxlQty();

	/**
	 * Sets the xxxl qty of this e s f article delivered.
	 *
	 * @param xxxlQty the xxxl qty of this e s f article delivered
	 */
	public void setXxxlQty(long xxxlQty);

	/**
	 * Returns the xxl qty of this e s f article delivered.
	 *
	 * @return the xxl qty of this e s f article delivered
	 */
	public long getXxlQty();

	/**
	 * Sets the xxl qty of this e s f article delivered.
	 *
	 * @param xxlQty the xxl qty of this e s f article delivered
	 */
	public void setXxlQty(long xxlQty);

	/**
	 * Returns the xl qty of this e s f article delivered.
	 *
	 * @return the xl qty of this e s f article delivered
	 */
	public long getXlQty();

	/**
	 * Sets the xl qty of this e s f article delivered.
	 *
	 * @param xlQty the xl qty of this e s f article delivered
	 */
	public void setXlQty(long xlQty);

	/**
	 * Returns the l qty of this e s f article delivered.
	 *
	 * @return the l qty of this e s f article delivered
	 */
	public long getLQty();

	/**
	 * Sets the l qty of this e s f article delivered.
	 *
	 * @param lQty the l qty of this e s f article delivered
	 */
	public void setLQty(long lQty);

	/**
	 * Returns the m qty of this e s f article delivered.
	 *
	 * @return the m qty of this e s f article delivered
	 */
	public long getMQty();

	/**
	 * Sets the m qty of this e s f article delivered.
	 *
	 * @param mQty the m qty of this e s f article delivered
	 */
	public void setMQty(long mQty);

	/**
	 * Returns the s qty of this e s f article delivered.
	 *
	 * @return the s qty of this e s f article delivered
	 */
	public long getSQty();

	/**
	 * Sets the s qty of this e s f article delivered.
	 *
	 * @param sQty the s qty of this e s f article delivered
	 */
	public void setSQty(long sQty);

	/**
	 * Returns the xs qty of this e s f article delivered.
	 *
	 * @return the xs qty of this e s f article delivered
	 */
	public long getXsQty();

	/**
	 * Sets the xs qty of this e s f article delivered.
	 *
	 * @param xsQty the xs qty of this e s f article delivered
	 */
	public void setXsQty(long xsQty);

	/**
	 * Returns the xxs qty of this e s f article delivered.
	 *
	 * @return the xxs qty of this e s f article delivered
	 */
	public long getXxsQty();

	/**
	 * Sets the xxs qty of this e s f article delivered.
	 *
	 * @param xxsQty the xxs qty of this e s f article delivered
	 */
	public void setXxsQty(long xxsQty);

	/**
	 * Returns the other qty of this e s f article delivered.
	 *
	 * @return the other qty of this e s f article delivered
	 */
	public long getOtherQty();

	/**
	 * Sets the other qty of this e s f article delivered.
	 *
	 * @param otherQty the other qty of this e s f article delivered
	 */
	public void setOtherQty(long otherQty);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFArticleDelivered esfArticleDelivered);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFArticleDelivered> toCacheModel();

	@Override
	public ESFArticleDelivered toEscapedModel();

	@Override
	public ESFArticleDelivered toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}