/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ethica.esf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ESFStockist service. Represents a row in the &quot;ESFStockist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ethica.esf.model.impl.ESFStockistModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ethica.esf.model.impl.ESFStockistImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFStockist
 * @see com.ethica.esf.model.impl.ESFStockistImpl
 * @see com.ethica.esf.model.impl.ESFStockistModelImpl
 * @generated
 */
public interface ESFStockistModel extends BaseModel<ESFStockist> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e s f stockist model instance should use the {@link ESFStockist} interface instead.
	 */

	/**
	 * Returns the primary key of this e s f stockist.
	 *
	 * @return the primary key of this e s f stockist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e s f stockist.
	 *
	 * @param primaryKey the primary key of this e s f stockist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the esf stockist ID of this e s f stockist.
	 *
	 * @return the esf stockist ID of this e s f stockist
	 */
	public long getEsfStockistId();

	/**
	 * Sets the esf stockist ID of this e s f stockist.
	 *
	 * @param esfStockistId the esf stockist ID of this e s f stockist
	 */
	public void setEsfStockistId(long esfStockistId);

	/**
	 * Returns the name of this e s f stockist.
	 *
	 * @return the name of this e s f stockist
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e s f stockist.
	 *
	 * @param name the name of this e s f stockist
	 */
	public void setName(String name);

	/**
	 * Returns the email of this e s f stockist.
	 *
	 * @return the email of this e s f stockist
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this e s f stockist.
	 *
	 * @param email the email of this e s f stockist
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this e s f stockist.
	 *
	 * @return the phone of this e s f stockist
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this e s f stockist.
	 *
	 * @param phone the phone of this e s f stockist
	 */
	public void setPhone(String phone);

	/**
	 * Returns the address of this e s f stockist.
	 *
	 * @return the address of this e s f stockist
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this e s f stockist.
	 *
	 * @param address the address of this e s f stockist
	 */
	public void setAddress(String address);

	/**
	 * Returns the name reference of this e s f stockist.
	 *
	 * @return the name reference of this e s f stockist
	 */
	@AutoEscape
	public String getNameReference();

	/**
	 * Sets the name reference of this e s f stockist.
	 *
	 * @param nameReference the name reference of this e s f stockist
	 */
	public void setNameReference(String nameReference);

	/**
	 * Returns the last name reference of this e s f stockist.
	 *
	 * @return the last name reference of this e s f stockist
	 */
	@AutoEscape
	public String getLastNameReference();

	/**
	 * Sets the last name reference of this e s f stockist.
	 *
	 * @param lastNameReference the last name reference of this e s f stockist
	 */
	public void setLastNameReference(String lastNameReference);

	/**
	 * Returns the email reference of this e s f stockist.
	 *
	 * @return the email reference of this e s f stockist
	 */
	@AutoEscape
	public String getEmailReference();

	/**
	 * Sets the email reference of this e s f stockist.
	 *
	 * @param emailReference the email reference of this e s f stockist
	 */
	public void setEmailReference(String emailReference);

	/**
	 * Returns the phone reference of this e s f stockist.
	 *
	 * @return the phone reference of this e s f stockist
	 */
	@AutoEscape
	public String getPhoneReference();

	/**
	 * Sets the phone reference of this e s f stockist.
	 *
	 * @param phoneReference the phone reference of this e s f stockist
	 */
	public void setPhoneReference(String phoneReference);

	/**
	 * Returns the description of this e s f stockist.
	 *
	 * @return the description of this e s f stockist
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e s f stockist.
	 *
	 * @param description the description of this e s f stockist
	 */
	public void setDescription(String description);

	/**
	 * Returns the other of this e s f stockist.
	 *
	 * @return the other of this e s f stockist
	 */
	@AutoEscape
	public String getOther();

	/**
	 * Sets the other of this e s f stockist.
	 *
	 * @param other the other of this e s f stockist
	 */
	public void setOther(String other);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ESFStockist esfStockist);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ESFStockist> toCacheModel();

	@Override
	public ESFStockist toEscapedModel();

	@Override
	public ESFStockist toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}