/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFOrganizationType;
import it.ethica.esf.model.ESFOrganizationTypeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFOrganizationType service. Represents a row in the &quot;ESFOrganizationType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFOrganizationTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFOrganizationTypeImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrganizationTypeImpl
 * @see it.ethica.esf.model.ESFOrganizationType
 * @see it.ethica.esf.model.ESFOrganizationTypeModel
 * @generated
 */
public class ESFOrganizationTypeModelImpl extends BaseModelImpl<ESFOrganizationType>
	implements ESFOrganizationTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f organization type model instance should use the {@link it.ethica.esf.model.ESFOrganizationType} interface instead.
	 */
	public static final String TABLE_NAME = "ESFOrganizationType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "esfOrganizationTypeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "esfOrganizationId", Types.BIGINT },
			{ "esfTypeId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ESFOrganizationType (esfOrganizationTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,esfOrganizationId LONG,esfTypeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ESFOrganizationType";
	public static final String ORDER_BY_JPQL = " ORDER BY esfOrganizationType.esfOrganizationTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESFOrganizationType.esfOrganizationTypeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFOrganizationType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFOrganizationType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFOrganizationType"),
			true);
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 1L;
	public static long ESFTYPEID_COLUMN_BITMASK = 2L;
	public static long ESFORGANIZATIONTYPEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFOrganizationType"));

	public ESFOrganizationTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfOrganizationTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfOrganizationTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfOrganizationTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFOrganizationType.class;
	}

	@Override
	public String getModelClassName() {
		return ESFOrganizationType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("esfOrganizationTypeId", getEsfOrganizationTypeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("esfTypeId", getEsfTypeId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long esfOrganizationTypeId = (Long)attributes.get(
				"esfOrganizationTypeId");

		if (esfOrganizationTypeId != null) {
			setEsfOrganizationTypeId(esfOrganizationTypeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		Long esfTypeId = (Long)attributes.get("esfTypeId");

		if (esfTypeId != null) {
			setEsfTypeId(esfTypeId);
		}
	}

	@Override
	public long getEsfOrganizationTypeId() {
		return _esfOrganizationTypeId;
	}

	@Override
	public void setEsfOrganizationTypeId(long esfOrganizationTypeId) {
		_esfOrganizationTypeId = esfOrganizationTypeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_columnBitmask |= ESFORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalEsfOrganizationId) {
			_setOriginalEsfOrganizationId = true;

			_originalEsfOrganizationId = _esfOrganizationId;
		}

		_esfOrganizationId = esfOrganizationId;
	}

	public long getOriginalEsfOrganizationId() {
		return _originalEsfOrganizationId;
	}

	@Override
	public long getEsfTypeId() {
		return _esfTypeId;
	}

	@Override
	public void setEsfTypeId(long esfTypeId) {
		_columnBitmask |= ESFTYPEID_COLUMN_BITMASK;

		if (!_setOriginalEsfTypeId) {
			_setOriginalEsfTypeId = true;

			_originalEsfTypeId = _esfTypeId;
		}

		_esfTypeId = esfTypeId;
	}

	public long getOriginalEsfTypeId() {
		return _originalEsfTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ESFOrganizationType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFOrganizationType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFOrganizationType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFOrganizationTypeImpl esfOrganizationTypeImpl = new ESFOrganizationTypeImpl();

		esfOrganizationTypeImpl.setEsfOrganizationTypeId(getEsfOrganizationTypeId());
		esfOrganizationTypeImpl.setGroupId(getGroupId());
		esfOrganizationTypeImpl.setCompanyId(getCompanyId());
		esfOrganizationTypeImpl.setUserId(getUserId());
		esfOrganizationTypeImpl.setUserName(getUserName());
		esfOrganizationTypeImpl.setCreateDate(getCreateDate());
		esfOrganizationTypeImpl.setModifiedDate(getModifiedDate());
		esfOrganizationTypeImpl.setEsfOrganizationId(getEsfOrganizationId());
		esfOrganizationTypeImpl.setEsfTypeId(getEsfTypeId());

		esfOrganizationTypeImpl.resetOriginalValues();

		return esfOrganizationTypeImpl;
	}

	@Override
	public int compareTo(ESFOrganizationType esfOrganizationType) {
		long primaryKey = esfOrganizationType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFOrganizationType)) {
			return false;
		}

		ESFOrganizationType esfOrganizationType = (ESFOrganizationType)obj;

		long primaryKey = esfOrganizationType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFOrganizationTypeModelImpl esfOrganizationTypeModelImpl = this;

		esfOrganizationTypeModelImpl._originalEsfOrganizationId = esfOrganizationTypeModelImpl._esfOrganizationId;

		esfOrganizationTypeModelImpl._setOriginalEsfOrganizationId = false;

		esfOrganizationTypeModelImpl._originalEsfTypeId = esfOrganizationTypeModelImpl._esfTypeId;

		esfOrganizationTypeModelImpl._setOriginalEsfTypeId = false;

		esfOrganizationTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFOrganizationType> toCacheModel() {
		ESFOrganizationTypeCacheModel esfOrganizationTypeCacheModel = new ESFOrganizationTypeCacheModel();

		esfOrganizationTypeCacheModel.esfOrganizationTypeId = getEsfOrganizationTypeId();

		esfOrganizationTypeCacheModel.groupId = getGroupId();

		esfOrganizationTypeCacheModel.companyId = getCompanyId();

		esfOrganizationTypeCacheModel.userId = getUserId();

		esfOrganizationTypeCacheModel.userName = getUserName();

		String userName = esfOrganizationTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			esfOrganizationTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			esfOrganizationTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			esfOrganizationTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			esfOrganizationTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			esfOrganizationTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		esfOrganizationTypeCacheModel.esfOrganizationId = getEsfOrganizationId();

		esfOrganizationTypeCacheModel.esfTypeId = getEsfTypeId();

		return esfOrganizationTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{esfOrganizationTypeId=");
		sb.append(getEsfOrganizationTypeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", esfTypeId=");
		sb.append(getEsfTypeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFOrganizationType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>esfOrganizationTypeId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfTypeId</column-name><column-value><![CDATA[");
		sb.append(getEsfTypeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFOrganizationType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFOrganizationType.class
		};
	private long _esfOrganizationTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _esfOrganizationId;
	private long _originalEsfOrganizationId;
	private boolean _setOriginalEsfOrganizationId;
	private long _esfTypeId;
	private long _originalEsfTypeId;
	private boolean _setOriginalEsfTypeId;
	private long _columnBitmask;
	private ESFOrganizationType _escapedModel;
}