/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.ethica.esf.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.ethica.esf.model.ESFOrganization;
import it.ethica.esf.model.ESFOrganizationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ESFOrganization service. Represents a row in the &quot;ESF_ESFOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.ethica.esf.model.ESFOrganizationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESFOrganizationImpl}.
 * </p>
 *
 * @author Ethica
 * @see ESFOrganizationImpl
 * @see it.ethica.esf.model.ESFOrganization
 * @see it.ethica.esf.model.ESFOrganizationModel
 * @generated
 */
public class ESFOrganizationModelImpl extends BaseModelImpl<ESFOrganization>
	implements ESFOrganizationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e s f organization model instance should use the {@link it.ethica.esf.model.ESFOrganization} interface instead.
	 */
	public static final String TABLE_NAME = "ESF_ESFOrganization";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "esfOrganizationId", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "vat", Types.VARCHAR },
			{ "fiscalCode", Types.VARCHAR },
			{ "establishmentDate", Types.TIMESTAMP },
			{ "closureDate", Types.TIMESTAMP },
			{ "groupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ESF_ESFOrganization (uuid_ VARCHAR(75) null,esfOrganizationId LONG not null primary key,code_ VARCHAR(75) null,vat VARCHAR(75) null,fiscalCode VARCHAR(75) null,establishmentDate DATE null,closureDate DATE null,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ESF_ESFOrganization";
	public static final String ORDER_BY_JPQL = " ORDER BY esfOrganization.esfOrganizationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ESF_ESFOrganization.esfOrganizationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.ethica.esf.model.ESFOrganization"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.ethica.esf.model.ESFOrganization"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.ethica.esf.model.ESFOrganization"),
			true);
	public static long CODE_COLUMN_BITMASK = 1L;
	public static long FISCALCODE_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long VAT_COLUMN_BITMASK = 16L;
	public static long ESFORGANIZATIONID_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.ethica.esf.model.ESFOrganization"));

	public ESFOrganizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _esfOrganizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEsfOrganizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _esfOrganizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESFOrganization.class;
	}

	@Override
	public String getModelClassName() {
		return ESFOrganization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("esfOrganizationId", getEsfOrganizationId());
		attributes.put("code", getCode());
		attributes.put("vat", getVat());
		attributes.put("fiscalCode", getFiscalCode());
		attributes.put("establishmentDate", getEstablishmentDate());
		attributes.put("closureDate", getClosureDate());
		attributes.put("groupId", getGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long esfOrganizationId = (Long)attributes.get("esfOrganizationId");

		if (esfOrganizationId != null) {
			setEsfOrganizationId(esfOrganizationId);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		String vat = (String)attributes.get("vat");

		if (vat != null) {
			setVat(vat);
		}

		String fiscalCode = (String)attributes.get("fiscalCode");

		if (fiscalCode != null) {
			setFiscalCode(fiscalCode);
		}

		Date establishmentDate = (Date)attributes.get("establishmentDate");

		if (establishmentDate != null) {
			setEstablishmentDate(establishmentDate);
		}

		Date closureDate = (Date)attributes.get("closureDate");

		if (closureDate != null) {
			setClosureDate(closureDate);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEsfOrganizationId() {
		return _esfOrganizationId;
	}

	@Override
	public void setEsfOrganizationId(long esfOrganizationId) {
		_esfOrganizationId = esfOrganizationId;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@Override
	public String getVat() {
		if (_vat == null) {
			return StringPool.BLANK;
		}
		else {
			return _vat;
		}
	}

	@Override
	public void setVat(String vat) {
		_columnBitmask |= VAT_COLUMN_BITMASK;

		if (_originalVat == null) {
			_originalVat = _vat;
		}

		_vat = vat;
	}

	public String getOriginalVat() {
		return GetterUtil.getString(_originalVat);
	}

	@Override
	public String getFiscalCode() {
		if (_fiscalCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _fiscalCode;
		}
	}

	@Override
	public void setFiscalCode(String fiscalCode) {
		_columnBitmask |= FISCALCODE_COLUMN_BITMASK;

		if (_originalFiscalCode == null) {
			_originalFiscalCode = _fiscalCode;
		}

		_fiscalCode = fiscalCode;
	}

	public String getOriginalFiscalCode() {
		return GetterUtil.getString(_originalFiscalCode);
	}

	@Override
	public Date getEstablishmentDate() {
		return _establishmentDate;
	}

	@Override
	public void setEstablishmentDate(Date establishmentDate) {
		_establishmentDate = establishmentDate;
	}

	@Override
	public Date getClosureDate() {
		return _closureDate;
	}

	@Override
	public void setClosureDate(Date closureDate) {
		_closureDate = closureDate;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ESFOrganization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ESFOrganization toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ESFOrganization)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESFOrganizationImpl esfOrganizationImpl = new ESFOrganizationImpl();

		esfOrganizationImpl.setUuid(getUuid());
		esfOrganizationImpl.setEsfOrganizationId(getEsfOrganizationId());
		esfOrganizationImpl.setCode(getCode());
		esfOrganizationImpl.setVat(getVat());
		esfOrganizationImpl.setFiscalCode(getFiscalCode());
		esfOrganizationImpl.setEstablishmentDate(getEstablishmentDate());
		esfOrganizationImpl.setClosureDate(getClosureDate());
		esfOrganizationImpl.setGroupId(getGroupId());

		esfOrganizationImpl.resetOriginalValues();

		return esfOrganizationImpl;
	}

	@Override
	public int compareTo(ESFOrganization esfOrganization) {
		long primaryKey = esfOrganization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ESFOrganization)) {
			return false;
		}

		ESFOrganization esfOrganization = (ESFOrganization)obj;

		long primaryKey = esfOrganization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ESFOrganizationModelImpl esfOrganizationModelImpl = this;

		esfOrganizationModelImpl._originalUuid = esfOrganizationModelImpl._uuid;

		esfOrganizationModelImpl._originalCode = esfOrganizationModelImpl._code;

		esfOrganizationModelImpl._originalVat = esfOrganizationModelImpl._vat;

		esfOrganizationModelImpl._originalFiscalCode = esfOrganizationModelImpl._fiscalCode;

		esfOrganizationModelImpl._originalGroupId = esfOrganizationModelImpl._groupId;

		esfOrganizationModelImpl._setOriginalGroupId = false;

		esfOrganizationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ESFOrganization> toCacheModel() {
		ESFOrganizationCacheModel esfOrganizationCacheModel = new ESFOrganizationCacheModel();

		esfOrganizationCacheModel.uuid = getUuid();

		String uuid = esfOrganizationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			esfOrganizationCacheModel.uuid = null;
		}

		esfOrganizationCacheModel.esfOrganizationId = getEsfOrganizationId();

		esfOrganizationCacheModel.code = getCode();

		String code = esfOrganizationCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			esfOrganizationCacheModel.code = null;
		}

		esfOrganizationCacheModel.vat = getVat();

		String vat = esfOrganizationCacheModel.vat;

		if ((vat != null) && (vat.length() == 0)) {
			esfOrganizationCacheModel.vat = null;
		}

		esfOrganizationCacheModel.fiscalCode = getFiscalCode();

		String fiscalCode = esfOrganizationCacheModel.fiscalCode;

		if ((fiscalCode != null) && (fiscalCode.length() == 0)) {
			esfOrganizationCacheModel.fiscalCode = null;
		}

		Date establishmentDate = getEstablishmentDate();

		if (establishmentDate != null) {
			esfOrganizationCacheModel.establishmentDate = establishmentDate.getTime();
		}
		else {
			esfOrganizationCacheModel.establishmentDate = Long.MIN_VALUE;
		}

		Date closureDate = getClosureDate();

		if (closureDate != null) {
			esfOrganizationCacheModel.closureDate = closureDate.getTime();
		}
		else {
			esfOrganizationCacheModel.closureDate = Long.MIN_VALUE;
		}

		esfOrganizationCacheModel.groupId = getGroupId();

		return esfOrganizationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", esfOrganizationId=");
		sb.append(getEsfOrganizationId());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", vat=");
		sb.append(getVat());
		sb.append(", fiscalCode=");
		sb.append(getFiscalCode());
		sb.append(", establishmentDate=");
		sb.append(getEstablishmentDate());
		sb.append(", closureDate=");
		sb.append(getClosureDate());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("it.ethica.esf.model.ESFOrganization");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>esfOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEsfOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vat</column-name><column-value><![CDATA[");
		sb.append(getVat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fiscalCode</column-name><column-value><![CDATA[");
		sb.append(getFiscalCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>establishmentDate</column-name><column-value><![CDATA[");
		sb.append(getEstablishmentDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>closureDate</column-name><column-value><![CDATA[");
		sb.append(getClosureDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ESFOrganization.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ESFOrganization.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _esfOrganizationId;
	private String _code;
	private String _originalCode;
	private String _vat;
	private String _originalVat;
	private String _fiscalCode;
	private String _originalFiscalCode;
	private Date _establishmentDate;
	private Date _closureDate;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private ESFOrganization _escapedModel;
}